### ISSUE TITLE
Delete letter suffix from the year in authorstring

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#107]
Some authorstrings in Sepidiini dataset have letter suffixes such as _Koch, 1953**a**_,     _Haag-Rutenberg, 1871**a**_,  _Gridelli, 1939**b**_

Please delete letters from year.

**Comment by gdower** [comment]
Fixed https://github.com/gdower/data-sepidiini/commit/a0cf9246a68d6a6b4e025dc29a605b74ff1726b0
