### ISSUE TITLE
Necessary steps towards next monthly edition (starts on 2020-02-11):

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#108]
@olafbanki @mdoering @gdower 

**Software tests** (Github issue #605 EditorialDecision cannot be re-matched to dataset - multiple names like SPECIES https://github.com/Sp2000/colplus-backend/issues/605 ):
Geoff and Yuri need to do tests of a new software version at https://data.dev.catalogue.life/.
Datasets for test should be uploaded in dev-Clearinghouse. Easiest solution: use Scarabs of March 2019 (ACEF), complete editorial decisions in the Clearinghouse, upload Scarabs of May 2019 (ACEF), check decision match and make report in Github – _2-5 working days_.
Upload a new software version in production (Markus).

**Content assembly** (Geoff & Yuri): 
3 databases are scheduled for next edition: 
•	World Spider Catalog in ACEF, 1st update in year cycle (done in Clearinghouse);
•	Sepidiini, a new GSD in ACEF (completed, but tribe and subtribe ranks are missed) or a new view in CoLdp (needs testing; editorial decisions should be made – _1 day_);
•	Scarabs of 2019-11-02 in CoLdp when ready, 3rd update in year cycle (should be completed after #605 fixes) – _3-5 days_.
Optional (is time allows): replace algae taxa with new data from IRMNG of 2019-03-02. 

Update CoL metadata, where it is required in the Clearinghouse and patches (special attention to the title, GSD500 management classification, updates in acknowledgement, what’s new) – _1 day_.

Data should be converted and published at testcol (_16-18 hours_).

Results should be checked “manually” and with DIF tool; also should be shared for final approval with data custodians (WSC, Sepidini checklist & Scarabs) – _4 days_. If further fixes needed, conversion will be repeated; plus new tests where needed (_+ 2-3 days_). 

Final editorial approval at testcol.

Deployment on production server.

**Comment by mdoering** [comment]
Thanks Yuri. As testing still means exporting to testcol and using the diff tool this is obviously a much slower process than it needs to be. Could you think whats missing from the Clearinghouse so that we could assess the catalogue right there without exporting it? I am sure @thomasstjerne would like to know about this

**Comment by yroskov** [comment]
We have completed tests for issue #605 on 2020-02-12. All work fine, in my opinion. Please deploy latest code at production site.

**Comment by yroskov** [comment]
The only software stopper towards next monthly edition is a front-end bug #488 (Unable to edit metadata in production Clearinghouse).

**Comment by yroskov** [comment]
Scarabs of 2019-11-02 will be processed in ACEF. CoLdp view needs more days of work.

**Comment by yroskov** [comment]
Assembly prototype for February is completed in the Clearinghouse on 2020-02-18. Final changes in Sepidiini tribe were added on 2020-02-18. 
Waiting for results of interim conversion.
