### ISSUE TITLE
TAXON HIERARCHY ERROR (Ari Örn, Feb edition)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#115]
1. TAXON HIERARCHY ERROR

There are 1052 records (taxonId range 3926184 - 3927235) that are duplicates and violate the taxon hierarchy. All of them depict family names. Each of them has a parentNameUsageID that refers to a taxon that is an identical duplicate of this one (apart from the parent id). So, the family is the parent of itself! The error is shown in the taxonomic tree of the UI as well, try Search "Pseudosquillidae" as an example. Ignoring these records makes it possible to build a valid taxon hierarchy.

I guess this problem is related to the known problem you mention in your message, 'loss of some higher taxa'.

**Comment by mdoering** [comment]
I cannot spot the problem in the february edition nor the working draft.
Should the family [Pseudosquillidae](http://www.catalogueoflife.org/col/browse/tree/id/912dd57a502f51d651e85b9d9caa332a) be duplicated?

**Comment by yroskov** [comment]
Pseudosquillidae appears once in Feb edition via user interface: http://www.catalogueoflife.org/col/browse/tree/id/912dd57a502f51d651e85b9d9caa332a
Can somebody check DwC-A?

**Comment by yroskov** [comment]
Incorrect presentation in Feb edition: http://www.catalogueoflife.org/col/search/all/key/neoaemula+vector/fossil/1/match/1

**Comment by gdower** [comment]
Ari is right that there are duplicates in the [DarwinCore Archive](http://workbench.catalogueoflife.org/DCA_Export/zip-fixed/2020-02-24-archive-complete.zip):

```
grep Pseudosquillidae *
grep: dataset: Is a directory
grep: import-scripts: Is a directory
taxa.txt:3923507        912dd57a502f51d651e85b9d9caa332a        Species 2000    Catalogue of Life in Species 2000 & ITIS Catalogue of Life: 2020-02-24          3923506         family          Pseudosquillidae        Animalia        Arthropoda      Malacostraca    Stomatopoda     Gonodactyloidea Pseudosquillidae                                                                                                                        false
taxa.txt:3926184        912dd57a502f51d651e85b9d9caa332a        Species 2000    Catalogue of Life in Species 2000 & ITIS Catalogue of Life: 2020-02-24          3923507         family          Pseudosquillidae        Animalia        Arthropoda      Malacostraca    Stomatopoda     Gonodactyloidea Pseudosquillidae                                                                                                                        false
```

There are not duplicates in the ac-export families.csv though:

```
grep Pseudosquillidae families.csv        
6211    \N      Animalia        Arthropoda      Malacostraca    Stomatopoda     Pseudosquillidae        Gonodactyloidea 500     009bced6-5d94-476d-a787-0ce4d906faa2    1
```

It might be a DCA_Export bug.

**Comment by gdower** [comment]
Because it probably is a DCA_Export bug, we probably won't fix it as the Clearinghouse will likely have its own DCA exporter.
