### ISSUE TITLE
STRANGE BINOMIAL NAMES (Ari Örn, Feb edition)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#116]
3. STRANGE BINOMIAL NAMES

The following 12 weird binomial names appear in taxa.txt:

Neoaemula neoaemula vector mackinnon, hiller, long & marshall, 2008
Cryptops cryptops (cryptops) vector chamberlin, 1939
Tidabius tidabius vector chamberlin, 1931
Dasyproctus dasyproctus cevirus leclercq, 1963
Psenulus psenulus trevirus leclercq, 1961
Euragallia euragallia prion kramer, 1976
Hilara hilara vector miller, 1923
Aspilota aspilota vector belokobylskij, 2007
Exochus exochus virus gauld & sithole, 2002
Ophion ophion virus gauld & mitchell, 1981
Microgoneplax microgoneplax prion castro, 2007
Ceylonesmus ceylonesmus vector chamberlin, 1941
Common to all of them is that the generic name has been doubled, the specific name has something to do with virology (vector, virus,  cevirus, trevirus, prion) and the authorship string has been appended to the binomial!?!? Visible also in WebUI, try Search "Hilara hilara", for example.

**Comment by mdoering** [comment]
Again fine in the Clearinghouse draft:
https://data.catalogue.life/dataset/3/taxon/17ff8f38-8589-4224-a775-29ee70c6d93c

BUT, the name is marked as `"type": "virus"`! It is sth the name parser does when spotting virus related epithets, it is the only way to identify virus names. That triggers a different method how to export as the [conversion tool expects virus names differently](https://github.com/Sp2000/ConversionTool/issues/11) than other names.

As there are very few names like that I suggest to manually place a decision for each of them to change the name type to `SCIENTIFIC` and these names should then be treated like regular species names. @thomasstjerne We should also add a new task that checks for virus type names without decision outside the virus kingdom. Here is a check for [virus names in Animalia](https://data.catalogue.life/dataset/3/names?TAXON_ID=061950e4-9782-4d1a-9c87-dcf375788e6b&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic&type=virus).

**Comment by mdoering** [comment]
I have tried adding a name type decision to the Brachiopoda Database:

https://data.catalogue.life/catalogue/3/dataset/1057/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0

The name type is not persisted, I have created a [backend/UI issue](https://github.com/CatalogueOfLife/backend/issues/674). We should test this in dev to make sure we can update virus names to scientific names fine

**Comment by yroskov** [comment]
CoL gets all virus names from only one GSD - ICTV. All names from ICTV should be marked as virus names. Parser should behave with ICTV names differently than with the rest of names

**Comment by yroskov** [comment]
Epithets _vector, virus, prion_ are absolutely valid epithets in zoological databases. Parser shouldn't do anything with this names.

**Comment by yroskov** [comment]
Correct presentation in AC19:
http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/neoaemula+vector/fossil/1/match/1
Incorrect presentation in Feb edition: 
http://www.catalogueoflife.org/col/search/all/key/neoaemula+vector/fossil/1/match/1

**Comment by yroskov** [comment]
Are they present in export file from the Clearinghouse?

**Comment by mdoering** [comment]
> Epithets vector, virus, prion are absolutely valid epithets in zoological databases. Parser shouldn't do anything with these names.

I know they are. But the parser does not know about the context of a name. It just parses a name and needs to decide what it is. And in >99% of the cases this behavior is correct. I believe GNA Parser does a very similar thing. There is enough on our plate right now, can we simply apply decisionsin those few cases for now?

**Comment by yroskov** [comment]
dmozzherin@ What would be a solution for parser to deal with such species/subspecies names such as: 
Neoaemula vector 
Cryptops (Cryptops) vector 
Tidabius vector 
Dasyproctus cevirus 
Psenulus trevirus 
Euragallia euragallia prion 
Exochus exochus virus
Ophion virus 
Microgoneplax microgoneplax prion

**Comment by gdower** [comment]
@mdoering re-configured the name parser to handle non-virus names with vector, virus, or prion as the species epithet, but to fix the issue we'll have to re-import and re-sync the following databases, which I'm working on now:

[Taxapad Ichneumonoidea](https://data.catalogue.life/dataset/1068)
[MilliBase](https://data.catalogue.life/dataset/1200)
[A World Catalogue of Centipedes (Chilopoda) for the Web](https://data.catalogue.life/dataset/1042)
[Systema Dipterorum](https://data.catalogue.life/dataset/1101)
[Hymenoptera Information System](https://data.catalogue.life/dataset/1118)
[MolluscaBase](https://data.catalogue.life/dataset/1130)
[Membracoidea MOWD](https://data.catalogue.life/dataset/1096)
[World List of marine Brachyura](https://data.catalogue.life/dataset/1108)
[Brachiopoda](https://data.catalogue.life/dataset/1057)

**Comment by gdower** [comment]
This issue is now [fixed](https://data.catalogue.life/dataset/3/names?TAXON_ID=061950e4-9782-4d1a-9c87-dcf375788e6b&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic&type=virus), but still needs testing after we run conversion

**Comment by dimus** [comment]
for gnparser see https://gitlab.com/gogna/gnparser/-/issues/78

**Comment by yroskov** [comment]
@gdower re-synced GSDs with these epithets. @yroskov tested results after conversion Catalogue of Life: 2020-04-06 (http://dev4.species.id:2200/col_plus): all names are correct now.
