### ISSUE TITLE
MALFORMED TRINOMIALS (Ari Örn, Feb edition)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#117]
4. MALFORMED TRINOMIALS

The scientificName column of subspecific synonym records in taxa.txt are systematically malformed. They are all expressed according to the botanical code, with "subsp." between the specific and subspecific name. For example:
Anguilla anguilla subsp. oxycephala De la Pylaie, 1835
This error is not visible in WebUI.

**Comment by mdoering** [comment]
Looks fine in the draft and API:
https://data.catalogue.life/dataset/3/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Anguilla%20anguilla%20oxycephala&sortBy=taxonomic

https://api.catalogue.life/dataset/3/synonym/0fc827de-1a0b-4322-90e1-c3eb999041e3

Must be an export, conversion or dwca generation problem

**Comment by yroskov** [comment]
Presentation is correct in Feb edition via user interface: http://www.catalogueoflife.org/col/details/species/id/b81dfd849eb83bca1705a2f0c0e671dd/synonym/cb6b32fcb61d3a9b00687f050923aaef
Does it mean, a problem is in DwC-A exporter?

**Comment by gdower** [comment]
Yes, it's a problem with the legacy DwC-A exporter, which we won't fix:

```
3416080         10      FishBase in Species 2000 & ITIS Catalogue of Life: 2020-04-16 Beta      2080012         ambiguous synonym       infraspecies    subsp.  Anguilla anguilla subsp. oxycephala De la Pylaie, 1835  Animalia                                                Anguilla        Anguilla             anguilla        oxycephala      De la Pylaie, 1835                                                      0fc827de-1a0b-4322-90e1-c3eb999041e3    http://www.catalogueoflife.org/col/details/species/id/b81dfd849eb83bca1705a2f0c0e671dd/synonym/cb6b32fcb61d3a9b00687f050923aaef
```
