### ISSUE TITLE
DROPPED OUT TAXA IN CCW (Ari Örn, Feb edition)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#118]
5. DROPPED OUT TAXA IN CCW

The ~100 CCW taxa listed below are dropped out from the Jan 2020 edition, obviously due to subgenus name 'Unplaced'. Just removing it would be enough, as "Erioptera amamiensis Alexander, 1956".

Erioptera (Unplaced) amamiensis Alexander, 1956
Erioptera (Unplaced) balioptera Alexander, 1966
Erioptera (Unplaced) fuscoradialis Alexander, 1950
Erioptera (Unplaced) grumula Alexander, 1957
Erioptera (Unplaced) incerta Brunetti, 1912
Erioptera (Unplaced) incompleta Senior-White, 1922
Erioptera (Unplaced) paivai Alexander, 1927
Erioptera (Unplaced) perpictula Alexander, 1931
Erioptera (Unplaced) regina Alexander, 1959
Erioptera (Unplaced) rex Alexander, 1952
Erioptera (Unplaced) rhadinostyla Alexander, 1957
Erioptera (Unplaced) rogersi Alexander, 1923
Erioptera (Unplaced) tiro Alexander, 1954
Limnophila (Unplaced) bigladia Alexander, 1945
Limnophila (Unplaced) bryanti Alexander, 1927
Limnophila (Unplaced) byersi Alexander, 1973
Limnophila (Unplaced) canifrons Edwards, 1932
Limnophila (Unplaced) chilensis Blanchard, 1852
Limnophila (Unplaced) decasbila (Wiedemann, 1828)
Limnophila (Unplaced) flavicauda (Bigot, 1888)
Limnophila (Unplaced) galactopoda Alexander, 1943
Limnophila (Unplaced) lobifera Alexander, 1955
Limnophila (Unplaced) mcdunnoughi Alexander, 1926
Limnophila (Unplaced) micropriapus Alexander, 1981
Limnophila (Unplaced) nigrofemorata Alexander, 1927
Limnophila (Unplaced) pectinifera Alexander, 1964
Limnophila (Unplaced) poetica Osten Sacken, 1869
Limnophila (Unplaced) subpilosa Edwards, 1928
Limnophila (Unplaced) tetonicola Alexander, 1945
Molophilus (Unplaced) micropteryx Alexander, 1927
Molophilus (Unplaced) subapterogyne Alexander, 1927
Phylidorea (Unplaced) contraria (Wollaston, 1858)
Rhabdomastix (Unplaced) caudata (Lundbeck, 1898)
Rhabdomastix (Unplaced) leptodoma Alexander, 1943
Rhabdomastix (Unplaced) monticola Alexander, 1916
Rhabdomastix (Unplaced) parva (Siebke, 1863)
Rhabdomastix (Unplaced) subarctica Alexander, 1933
Rhabdomastix (Unplaced) subcaudata Alexander, 1927
Tipula (Unplaced) baileyi Alexander, 1953
Tipula (Unplaced) bipendula Alexander, 1934
Tipula (Unplaced) bispathifera Savchenko, 1960
Tipula (Unplaced) cladomera Alexander, 1936
Tipula (Unplaced) compressiloba Alexander, 1938
Tipula (Unplaced) coxitalis Alexander, 1935
Tipula (Unplaced) demeijerei Edwards, 1915
Tipula (Unplaced) depressiloba Oosterbroek and Theowald, 1992
Tipula (Unplaced) depressa Alexander, 1931
Tipula (Unplaced) flavicosta Alexander, 1915
Tipula (Unplaced) formosicola Alexander, 1920
Tipula (Unplaced) frigida Walker, 1848
Tipula (Unplaced) gressitti Alexander, 1935
Tipula (Unplaced) idiopyga Alexander, 1949
Tipula (Unplaced) imanoensis Alexander, 1954
Tipula (Unplaced) incisurata Alexander, 1940
Tipula (Unplaced) inordinans Walker, 1859
Tipula (Unplaced) johanseni Alexander, 1919
Tipula (Unplaced) kusunokiana Alexander, 1955
Tipula (Unplaced) lanio Alexander, 1945
Tipula (Unplaced) liui Alexander, 1941
Tipula (Unplaced) maculatipennis Say, 1824
Tipula (Unplaced) melanonotalis Alexander, 1954
Tipula (Unplaced) microcellula Alexander, 1923
Tipula (Unplaced) nippoalpina Alexander, 1931
Tipula (Unplaced) opinata Alexander, 1940
Tipula (Unplaced) otiosa Alexander, 1924
Tipula (Unplaced) palesoides Alexander, 1942
Tipula (Unplaced) percommoda Alexander, 1938
Tipula (Unplaced) perelegans Alexander, 1921
Tipula (Unplaced) elegans Brunetti, 1911
Tipula (Unplaced) perlata Alexander, 1938
Tipula (Unplaced) pluriguttata Alexander, 1920
Tipula (Unplaced) praeses Alexander, 1942
Tipula (Unplaced) fumipennis Alexander, 1912
Tipula (Unplaced) prolongata Alexander, 1936
Tipula (Unplaced) puncticornis Macquart, 1850
Tipula (Unplaced) repugnans Alexander, 1940
Tipula (Unplaced) reservata Alexander, 1941
Tipula (Unplaced) sexlobata Alexander, 1938
Tipula (Unplaced) spectata Alexander, 1940
Tipula (Unplaced) sternosetosa Alexander, 1940
Tipula (Unplaced) sternotuberculata Alexander, 1935
Tipula (Unplaced) strix Alexander, 1918
Tipula (Unplaced) subdepressa Alexander, 1941
Tipula (Unplaced) subnata Alexander, 1949
Tipula (Unplaced) subpolaris Alexander, 1919
Tipula (Unplaced) subyusou Alexander, 1929
Tipula (Unplaced) superciliosa Alexander, 1924
Tipula (Unplaced) tantula Alexander, 1924
Tipula (Unplaced) terebrata Edwards, 1921
Tipula (Unplaced) trimaculata (Emmons, 1854)
Tipula (Unplaced) tropica de Meijere, 1913
Tipula (Unplaced) varaha Alexander, 1953
Tipula (Unplaced) xanthomelaena Edwards, 1926
Tipula (Unplaced) yanoana Alexander, 1953
Tipula (Unplaced) yusou Alexander, 1914
Tipula (Unplaced) yusouoides Alexander, 1929

**Comment by yroskov** [comment]
I thought, we fixed this issue after Jan edition, but seems, not

**Comment by yroskov** [comment]
Well, correct binomial appears in Clearinghouse: https://data.catalogue.life/catalogue/3/dataset/1005/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Erioptera%20amamiensis
Did we forget to sync updated CCW?

**Comment by mdoering** [comment]
Yes, that could be the reason. The last sync was on 6th January:
https://data.catalogue.life/catalogue/3/sector/sync?sectorKey=4424

**Comment by yroskov** [comment]
Geoff, is there possibility to do sync and full conversion for CCW on local server?

**Comment by yroskov** [comment]
I have started sync in prod

**Comment by yroskov** [comment]
All binomial names are back in the Catalogue of Life: 2020-04-03. ("Unplaces" word in subgenus field was removed in the source. CCW was re-synced).
