### ISSUE TITLE
DROPPED OUT TAXA IN DOTHIDEOMYCETES (Ari Örn, Feb edition)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#119]
6. DROPPED OUT TAXA IN DOTHIDEOMYCETES

The following two taxa along with their synonyms have been dropped out for unknown reason. I checked Species Fungorum, where they exist exactly as in 2019 Annual.

Mycoporum californicum (Zahlbr.) R. C. Harris, 1995
syn. Mycoporellum californicum Zahlbr., 1912
syn. Mycoporopsis californica (Zahlbr.) Riedl, 1962
syn. Mycoporopsis californica (Zahlbr.) Riedl, 1963
syn. Tomasellia californica (Zahlbr.) R. C. Harris, 1987

Phyllobathelium chlorogastricum (Müll. Arg.) Aptroot & Lücking, 2016
syn. Campylothelium chlorogastricum (Müll. Arg.) Aptroot, 2008
syn. Cryptothelium chlorogastricum (Müll. Arg.) Zahlbr., 1922
syn. Heufleria chlorogastrica Müll. Arg., 1883

**Comment by mdoering** [comment]
They are in the draft, not sure what has happened:
https://data.catalogue.life/dataset/3/taxon/e504dfd8-7341-463d-aee2-5d49a9e2cd73

https://data.catalogue.life/dataset/3/taxon/8f499669-0761-4b7e-baa1-eb426e5825ec

**Comment by gdower** [comment]
I'm not sure why, but those names are missing in [export-2081](http://api.catalogue.life/download/export-2081.zip). Maybe it was a sync failure? I checked export-3, and those names are included although that was after attaching the new Index Fungorum 2073 dataset. I'll keep this open for now to make sure that we check it for the April release.

**Comment by yroskov** [comment]
I have completed sync for CCW.
