### ISSUE TITLE
Steps towards April edition

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#122]
@gdower I have checked conversion of 2020-04-15 at http://dev4.species.id:2200/col_plus/ 

Sp Fungorum & Eumycetozoa data look good. Both Paul & Carlos gave us green light.

I have checked split taxa Sp Fungorum: all look as expected. However, I failed to prove/disprove that names outside taxonomic catalogue (i.e. taxonomically unplaced names from Index Fungorum) are not included in CoL. Geoff, do we have any names from Paul in Clearinghouse without statuses "Accepted" or "Synonym"? If yes, are they included in CoL or left outside?

We need to complete following steps before deployment:

1.	- [x] Add word “Beta” in the title: Catalogue of Life: 2020-04-15 Beta

2.	- [x] Remove not-in-use GSDs from database: Dothideomycetes, Glomeromycota, Phyllachorales, Rhytismatales, Saccharomycetes, Trichomycetes, Xylariaceae & Zygomycetes. 
But keep LIAS.
http://dev4.species.id:2200/col_plus/info/databases 

3.	- [x] Remove links to these GSDs at http://dev4.species.id:2200/col_plus/info/ac = YR, done in ac.phtml file

4.	- [x] Apply latest Info pages from https://github.com/Sp2000/AC_Interface/tree/col%2B/application/views/scripts/info 

5.	- [x] Do corrections for New & Updated flags. 
New 1: Sepidiini tribe. 
Updated 4 gsds: Scarabs, WSC, Species Fungorum Plus, Nomen.eumycetozoa.com

Further improvements 
- [ ] Lot of missing estimates in the Tree – what’s happened? How to bring figures back?

- [ ] Coordinate date in the title with date in What’s New at http://dev4.species.id:2200/col_plus/info/special   Can it be automated through HTML template similar to stats in Info and to CoL title in bibliographic citations?

**Comment by mdoering** [comment]
GSD metadata is provided in the AC export based on actually existing sectors in the draft. So when there is no sector left, the GSD should not appear anymore in the export.

Dothideomycetes for examples still seems to have lots of sectors:
https://data.catalogue.life/dataset/1098/sectors?limit=500&offset=0

Why would you then remove it? This looks pretty weird to be honest. All the sectors in Dothideomycetes do not appear in the assembly tree:

<img width="1490" alt="Screenshot 2020-04-15 at 20 56 31" src="https://user-images.githubusercontent.com/327505/79377206-9b270a80-7f5b-11ea-88d1-9829864170aa.png">

@thomasstjerne do you have any explanation for this?

**Comment by mdoering** [comment]
Looks like all data was removed but the sector mapping still exists and is not even broken.
How did this happen? To avoid this in the future we might need to have an overview of sectors or even source datasets that contribute no data to a project.

**Comment by mdoering** [comment]
I guess this is what "Source datasets" does:
https://data.catalogue.life/catalogue/3/sources

@thomasstjerne The species count sorting just does not work to show the zero ones!

**Comment by mdoering** [comment]
For the April edition I think you should delete all sectors for these zero datasets if your intention is that they indeed get replaced by IF

**Comment by yroskov** [comment]
Entire kingdom Fungi has only one sector entirely covered by Sp Fungorum Plus: https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=4f547792-7bea-4b6e-8f13-3e320c84b6b1. There is no any other GSD in assembly tree. If sectors should be deleted somewhere else, it is malfunction of the system.

**Comment by gdower** [comment]
> Geoff, do we have any names from Paul in Clearinghouse without statuses "Accepted" or "Synonym"? If yes, are they included in CoL or left outside?

@yroskov, I just sent you a full list of bare names that are not attached to taxa as accepted names or synonyms, but here's several:

_Toruloidea tulipiferae
Stigmina obclavata
Myxosporium stillatum
Oospora martinii
Schizocephalum atrobrunneum
Oligostroma graphis
Oospora fungicola
Acrosporium compactum
Polystomella salvadorae
Schizocephalum griseum
Pyonema assimile_

**Comment by yroskov** [comment]
Fantastic! sampled names are not in CoL. Now I have an answer.

**Comment by mdoering** [comment]
> There is no any other GSD in assembly tree. If sectors should be deleted somewhere else, it is malfunction of the system.

It was how we jointly designed it. When a subtree is deleted, we do no delete the sectors that are attached to the deleted data. Only the data is removed. We were then thinking these sectors show up as broken sectors cause the target taxon is missing after a deletion. But in this case the SF data has the same names we attached other sectors to, so they are not even broken. Just do not contain any data.

One of the problems is that the UI does not show sectors in the assembly tree without data. @thomasstjerne Maybe we should include a list of sectors in the catalogue view with the target usage in addition to the sectorKey which a usage originated from? It would easily mess up the UI, but how else could we best deal with this?

This might warrant a new backend issue to change how the system behaves, but I am not clear what the best solution is.

**Comment by yroskov** [comment]
From the point of editor view, the system behaves correctly: as soon as I deleted/disconnected sector in Assembly Tree, no any taxa from deleted sector syncs in the CoL. The only malfunction is: datasets still stay in a list of contributing GSDs.

**Comment by mdoering** [comment]
Well, if you hit sync all these sectors would sync data again. Or if you trigger them individually.
We could also filter out all sectors with no data from releases. This would also remove them from the exports of these releases. That would at least solve the immediate problem.

But it will leave over time more and more dataless sectors dangling around which should not be there. How exactly did we end up in this situation? You created a new Fungi sector by attaching it to Biota and then manually deleted the previous Fungi kingdom? Should we maybe also simply delete any sectors in such subtrees?

**Comment by gdower** [comment]
Yuri's vision for the assembly user interface has always been to implement it like the Windows file system explorer, so if you deleted a folder, all the subfolders and subfiles would be recursively deleted. (Actually the Windows model would be moving it to "trash," which isn't a bad idea because then we could restore accidentally deleted sectors. Being able to restore deleted sectors would also allow us to temporarily remove sectors from assembly and put them back if we haven't gotten feedback from a GSD on time for including their update in a release.)

I didn't see the assembly process but my guess is that Yuri probably did delete a higher level sector expecting that the sub-sectors would be deleted. If a large sector needs to be replaced, it could be pretty tedious having to manually delete all the sub-sectors. On the other hand, if someone accidentally deletes a high level sector, a recursive delete could potentially do a lot of damage. If recursive delete is added to the frontend, there probably ought to be a pop-up confirming that you want to delete 1000 sectors with 1,000,000 species from the catalogue.

Listing sectors with 0 species in the broken sectors interface could help us identify and remove them without the risk of adding recursive delete in assembly, although I think recursive delete would be more intuitive to use because it follows the file system user interface model that most people are already familiar with. It's just risky without a restore system.
