### ISSUE TITLE
Conversion reports 2020-05-28, 2020-06-01, 2020-06-03, 2020-06-04 (final)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#129]
Tests at http://dev4.species.id:2204/col_plus

**Collembola.org** (excluded in 2020-06-01)
So far, so good.
**Issue:** complex decision for spp in genus Neanuratobeassignedtopropergenus. Note _Should be re-assigned to a proper genus_ was not passed in Additional Data field. Fixed in 2020-06-03

**FLOW**
**Problems to fix**: 
- [x] All extinct species (>300) have been assembled as extant. 0 extinct spp shown in stats. Remains in 2020-06-01 (extinct spp are not flagged through whole CoL 2020-06-01). Fixed in 2020-06-04
- [x] Missing Refs (all or some?). Fixed in 2020-06-01
- [x] Incorrect Release Date. Fixed in 2020-06-01
- [ ] Empty genus in Not Assigned family (empty genus - need to be blocked in Issues). **Remains in 2020-06-01, despite of blocking name in Clearinghouse**
![image](https://user-images.githubusercontent.com/28574252/83272270-8eb7e380-a190-11ea-8bd0-0d46b9ca345a.png)

**Scarabs in CoLDP**
- [x] Missing Refs (all or some?). Fixed in 2020-06-01

**Sp Fungorum Plus, Refs fixes**
- [x] It would be nice to keep ONLY AUTHOR(s), which stay after right bracket. Now full authorstring included:
(remains in 2020-06-01, GO fixed, but SpFung was not synced before conversion - YR to do Tasks again). Fixed in 2020-06-03
![image](https://user-images.githubusercontent.com/28574252/83273896-a55f3a00-a192-11ea-8b7e-875c49e86046.png)

**Eumycetozoa, Refs fixes**
- [x] Refs: missing portion "In:" at the beginning of Source/Details field.  Fixed in 2020-06-01
![image](https://user-images.githubusercontent.com/28574252/83281360-99c54080-a19d-11ea-9f4f-5b904b4618e7.png)

**Comment by yroskov** [comment]
General: still some estimate figures are missing in the Tree

**Comment by yroskov** [comment]
Towards early June edition: I have deleted Collembola sector in Assembly, because we have no yet a green light from Frans (2020-06-01, 10 am)

**Comment by yroskov** [comment]
**Tests of 2020-06-01:** 
- [ ] Extinct spp are not flagged through whole CoL 2020-06-01

**Comment by yroskov** [comment]
**Scarabs, refs in 2020-06-01**

**Missing Change Reference** with accepted names (where acc. name is a combination = with a flag in the field Parenthesis).

**Comment by yroskov** [comment]
**Tests of 2020-06-03** (http://dev4.species.id:9191/col_plus)
- [ ] Extinct spp are not flagged through whole CoL 2020-06-03
- [ ] Collembola logos are missed
- [ ] Info pages were not updated

**Comment by yroskov** [comment]
2020-06-03 at 8.00 am (perhaps, conversion is not finished yet). 
Strange appearance: 

Browse - Taxonomic Classification (missing authorstrings)
![image](https://user-images.githubusercontent.com/28574252/83639529-6b19e200-a570-11ea-813c-9ae4424418a6.png)

Tree (see stats and credits)
![image](https://user-images.githubusercontent.com/28574252/83639626-90a6eb80-a570-11ea-8286-cbbb97169df0.png)

**Comment by yroskov** [comment]
**2020-06-04: tests** at http://workbench.catalogueoflife.org/col_plus

- [ ] Product title: missing portion Beta. Should be **Catalogue of Life: 2020-06-04 Beta**

- [ ] Bibliographic citations need correction: replace "Working Draft" with "Beta"; delete duplicated date.
![image](https://user-images.githubusercontent.com/28574252/83877634-7e5bb780-a700-11ea-8752-2fdc0a7a81ac.png)

- [ ] Info-What's new: change date in top title for 2020-06-04 (i.e. take the latest version of special.phtml file   
AC_Interface/application/views/scripts/info/special.phtml ).
 
- [ ] Pls, correct flags Is_New with GSDs: New (value 1) & Updated (value 2). New - two GSDs: Collembola.org & Sepidini. Updated 5 GSDs: Scarabs, WSC, FLOW, SpFungorum Plus, Eumycetozoa

**Comment by mdoering** [comment]
A note on title and citation of releases. There are templates that should be used in the main project settings to generate the correct title and citation of the release. These templates allow to use variables in curly brackets incl `{date}` for the current date and any of the dataset metadata properties already defined for the project. Please adapt these templates to your likings:

https://data.catalogue.life/catalogue/3/options


PS: the citation template is not yet deployed but will be done later today
PPS: I will also add an alias template

**Comment by yroskov** [comment]
- [ ] Geoff, would it be possible to update stats for genera, families, orders, classes & phyla at http://www.catalogueoflife.org/col/info/ac? ("Not Assigned" values should be excluded from stats).

**Comment by yroskov** [comment]
Duplicated GSD Short Names (such as MOWD: MOWD: Membracoidea of the World Database) fixed in the Clearinghouse - available for a next month.

**Comment by yroskov** [comment]
**Analyses of total stats in 2020-06-04 vs 2020-04-16 reveals unexpected loss of ~4.5K synonyms.**
Synonyms, total
2020-06-04 1,710,621
2020-04-16 1,710,428
                           +193

Whereas, new Collebola.org contributed +4,709 new synonyms.
4,709 - 193 = 4,516‬ - a number of synonyms which CoL lost from 2020-04-16 to 2020-06-04.

Explanation:
FLOW via a new pipeline decreased number of synonyms from 9,089 to 4,743; it explains all: -4,346‬ synonyms. (FLOW view in CoL+ need to be re-confirmed by Thierry).

Scarabs also decreased number of synonyms from 28,473 to 28,578. -105 synonyms.

**Comment by yroskov** [comment]
Geoff: in FLOW there are 4817 not interpreted synonyms: https://data.catalogue.life/dataset/1011/verbatim?issue=not%20interpreted
It looks like a cause for a lost of synonyms. In the past, those names were included in CoL. For example, Flata rufilinea Stål, 1862 ( https://www.hemiptera-databases.org/flow/?lang=en&card=name&id=7930&page=explorer&db=flow). 

In old CoL: 
Paranotus rufilinea  (Walker, 1858) (accepted name) |  
Flata rufilinea Stål, 1862 (synonym)                                                                                                                                                                                         Poeciloptera rufilinea Walker, 1858 (synonym) 

The name is absent in new CoL.

**Comment by yroskov** [comment]
Geoff: I think it's because the synonym ID is 18796 but there's an accepted name with ID 18796.

Needs investigation whether CoL+ backend allows identical IDs in accepted and synonyms or not, and how to handle such situation in CoL+

**Comment by yroskov** [comment]
Geoff: SQL FLOW template in Webmin concatenated an s- onto the synonym IDs.

It was a solution to create unique IDs in a case of overlap between accepted and synonym IDs. However, references with synonyms were lost; synonym references might be incorrectly linked to accepted names.

**Comment by yroskov** [comment]
Seems, there is a problem with Refs in FLOW export file. If I am correct, all Refs (incl. synonym refs) linked to accepted ID

**Comment by yroskov** [comment]
We cannot resolve identical acc & syn IDs in proxy datasets. Correct?

**Comment by mdoering** [comment]
> Needs further investigation whether CoL+ backend allows identical IDs in accepted and synonyms or not, and how to handle such situation in CoL+

No, ColDP mandates unique "name usage" ids, i.e. synonyms and accepted names share the same id namespace and have to be unique. You cannot reuse the same id for a synonym if an accepted name uses it already. 

As you can see - and I think I mentioned this to Thierry in some mail - FLOW has a very serious [ID NOT UNIQUE issue](https://data.catalogue.life/dataset/1011/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=id%20not%20unique ) with 4769 accepted names affected. Red ID issues should always be taken serious -  they do cause problems

**Comment by mdoering** [comment]
The easiest solution to fix this would be to prefix all synonym ids with an S. But as I understand we cannot change the Paris exports. Hm. What if we had a new `prefix` parameter for mapped coluns in the proxy definition? Might be difficult.

**Comment by yroskov** [comment]
**!!!** Incorrect metadata in Brentids GSD (id 161) http://www.catalogueoflife.org/col/details/database/id/161 

Metadata mixed with The White Files: Full Name, Authors, Abstract, Website, Bibl.Citation.

@gdower 

![image](https://user-images.githubusercontent.com/28574252/88594898-b1973480-d027-11ea-965f-6dea9173119f.png)
