### ISSUE TITLE
Fix sectors for missing taxa

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/data#130]
Fix the sector registration for the missing taxa brought back in #111.

**Comment by yroskov** [comment]
**Fixed sectors:** 

Mites GSD Phytoseiidae - sector Superfamily Phytoseioidea. **Fixed & synced 2020-06-04**   (incl. Mites GSD Ologamasidae, Phytoseiidae, Rhodacaridae)

FADA Halacaridae - sector Family Halacaridae. **Fixed & synced 2020-06-04**

TITAN - sector Family Cerambycidae. **Fixed & synced 2020-06-04**

**Comment by yroskov** [comment]
**Re-adjusted sectors:**

BdelloideaBase -  sectors families Bdellidae, Cunaxidae. **Fixed & synced 2020-07-27**

Brassicaceae -  sector family Brassicaceae (not an order Brassicales). **Fixed & synced 2020-07-27**

**Comment by yroskov** [comment]
ITIS sectors should be adjusted during re-assembly of global ITIS checklists.
