### ISSUE TITLE
Information unrelated to the scientific name follows after authorstring in the classification paragraph (World Ferns)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#143]
Frontend version: c99dba2 June 17, 2020 9:47 AMBackend version: 507800e June 17, 2020 8:53 AM

I am not sure what's happened in the classification paragraph in the Clearinghouse: why information unrelated to the name follows after authorstring (example from World Ferns): 

![image](https://user-images.githubusercontent.com/28574252/85047708-d6120e00-b157-11ea-9743-15ab42e09ed4.png)

@gdower @mdoering Is it crawler problem or clearinghouse problem?

**Comment by gdower** [comment]
It's an already known issue caused by @mdoering working on the according to issue: 

https://github.com/CatalogueOfLife/backend/issues/760
