### ISSUE TITLE
Estimates in World Plants/World Ferns source files

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#144]
World Ferns CSV file contain estimates with taxa of higher ranks in the field Remarks:

Lycopodiales | 1 family (3-)16 genera, ca. 460 spp.
Lycopodiaceae | (3-)16 genera, ca. 480 spp. According to &Oslash;llgaard (2012) and molecular results, all genera should be accepted.
Lycopodium | 9 spp. mainly temperate and subarctic regions

@gdower Is there any way to crawl estimates for species from free text Remarks?

**Comment by gdower** [comment]
Yes, but there is no way to provide estimates in CoLDP. I could add an estimates column to the taxa table anyway, which would be imported as a verbatim column. An additional tool would have to be developed to apply the estimates from the verbatim column to the API.

**Comment by mdoering** [comment]
Please do so @gdower . We could also consider adding estimates to ColDP, I was wondering about that before. But that would then probably have to be a new table with a reference link as we can have potentially multiple estimates per taxon

**Comment by gdower** [comment]
Added but not imported yet.
