### ISSUE TITLE
Delete ghost sectors

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/data#151]
Somehow we ended up with 2275 ghost sectors from the old Species Fungorum dataset, which need to be deleted:

https://api.catalogue.life/dataset/3LR/sector?subjectDatasetKey=1028

@mdoering, these don't show up as [broken sectors](https://api.catalogue.life/dataset/3LR/sector?subjectDatasetKey=1028&broken=true), possibly because the taxa are there from the new dataset. My guess is that @yroskov might have deleted the Fungi kingdom in modify tree, which didn't delete the sectors. If we ran a sync all, these might end up back in the catalogue. If there isn't a way to do it already, we might need a way to search for unsynced sectors with 0 taxa.

**Comment by mdoering** [comment]
We could add a usage count to the sector table, based on the latest sync attempt:
https://data.catalogue.life/catalogue/3/sector?limit=100&offset=0

... and then make that also searchable (min/max) or sortable

**Comment by mdoering** [comment]
We actually have already a `lastSync` search parameter that filters out all sectors that have been synced after the given limit, leaving only sectors that have never been synced or synced before the given date. If you use a really old date this basically lists all sectors that have never been synced:
https://api.catalogue.life/dataset/3LR/sector?lastSync=2011-01-01

We would just need to integrate this into the UI somewhere

**Comment by mdoering** [comment]
well, the releases do not have the sync history, so the lastSync always shows all sectors for a release.
It only works on the project itself: https://api.catalogue.life/dataset/3/sector?lastSync=2010-01-01
116 sectors that have never been synced from the following source datasets:

```
1098
1098
1140
1140
1140
1140
1140
1502
1502
1502
1502
1502
1502
1502
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
2007
```

**Comment by mdoering** [comment]
That means all Species Fungorum sectors are fine, not broken and have been synced. It is just that you need to check against the project not the release

**Comment by gdower** [comment]
@yroskov and I resolved all empty sectors, including Species Fungorum: https://data.catalogue.life/catalogue/3/sector?limit=100&offset=0&withoutData=true
