### ISSUE TITLE
Narcissus triandrus subsp. triandrus

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#191]
**Describe the problem**:
Narcissus triandrus subsp. triandrus in COL has a very large number of heterotypic synonyms that do not seem to match the species. Kews on page only lists 3 homotypic synonyms, see below

**Link to effected CoL webpages**:
https://data.catalogue.life/dataset/3LR/taxon/80ce0a11-e207-44ce-8c5f-263a7c98faef

**Literature references**:
https://wcsp.science.kew.org/synonomy.do?name_id=282111
https://en.wikipedia.org/wiki/Narcissus_triandrus

**Comment by mdoering** [comment]
This is already present in AC19: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/8abedee2e8b480058738183d950d0723

**Comment by mdoering** [comment]
Hm, it seems WSCP indeed has that list of synonyms:
https://wcsp.science.kew.org/synonomy.do?name_id=477317

**Comment by mdoering** [comment]
One of the synonyms is actually a hybrid and it is parsed very badly with its authorship containing epithets:
https://data.catalogue.life/dataset/1024/name/282673

It comes from our original ACEF exports with bad verbatim synonym data:
https://data.catalogue.life/dataset/1024/verbatim?q=jonquilla%20subsp.%20fernandesii

**Comment by mdoering** [comment]
It is actually not even a proper hybrid name and seems to mix 2 subspecific epithets. The latest version we have from Kew directly does not contain this hybrid:
https://data.catalogue.life/dataset/2000/taxon/urn%3Alsid%3Aipni.org%3Anames%3A77169973-1

@yroskov maybe we should update our WSCP sectors from the "PoWo" version?

**Comment by yroskov** [comment]
We definitely need to update WCSP, when we be ready to work on this. Now we have another urgent priorities for updates.

See a list of synonyms in POWO ;): http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77169973-1#synonyms

**Comment by yroskov** [comment]
Now in the Clearinghouse: Narcissus concolor (Haw.) Link (syn)
