### ISSUE TITLE
Possible source data: Catalogue of Afrotropical Bees

### ISSUE THREAD

**Issue by kcopas** [CatalogueOfLife/data#192]
I don't know if you want these added as issues to this repo, but I just wanted to register the fact that this [checklist of Afrotropical bees](https://doi.org/10.15468/u9ezbh) available through GBIF appears to have broad coverage outside COL (see metrics).

The South African researchers responsible for it have also just published a data paper in a Pensoft journal: https://doi.org/10.3897/afrinvertebr.60.37752 

Hope this helps!

**Comment by yroskov** [comment]
Afrotropical Bees might be included as a regional resource in CoL+ right now (i.e. outside scrutinized CoL). 

ITIS, as a responsible data provider for global bees checklist in CoL, may have plans to update their data with Afrotropical Bees. I'll ask ITIS.

**Comment by yroskov** [comment]
Dear Yuri,

ITIS continues to update the bees on a rolling basis, and John Ascher continues to integrate all sources, including this one, into his dataset that we use to update ITIS. It is time-consuming, but the results are solid. I believe we have updated bee groups covering 7000 species in the last couple of years, for context.

I hope that helps,
Dave [Nicolson]

**Comment by camiplata** [comment]
It is now part of the xrelease ;)
