### ISSUE TITLE
Engage with Systema Diptera

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#194]
A valuable nomenclator source:
http://www.diptera.org/

Engage with Thomas Pape to publish it as DwC-A

**Comment by yroskov** [comment]
In November 2016, Thomas Pape promised to send a new export of Systema Dipterorum to CoL. Still waiting. Thomas, as GT member, is aware of this.

**Comment by deepreef** [comment]
This is my bad -- I've been too busy to generate the export.  I am activating this process now.

**Comment by olafbanki** [comment]
Thanks Rich, that would be great!
