### ISSUE TITLE
Abacoceraphron Dessart, 1975 shows up twice

### ISSUE THREAD

**Issue by olafbanki** [CatalogueOfLife/data#214]
This genus shows up twice:
https://www.catalogue.life/data/taxon/52GY9 This one is originating from ITIS
Here the source of the data is unclear: https://www.catalogue.life/data/taxon/52GY8 

Through COL ChecklistBank I cannot figure out from which source one of the names is coming from:
https://data.catalogue.life/dataset/2230/name/85b69dbc-6b99-4d61-8fea-03beaa2bb334

I wil log a separate issue on why author name and year show up with some genera: https://github.com/CatalogueOfLife/data/issues/215

**Comment by mdoering** [comment]
If no source is given it is from no source, but manually curated in COL itself.
This case is likely from the deletion of the previous ITIS source which @yroskov wants to only delete species and below, but leave genera and higher taxa in place no attributed to the COL. @yroskov probably that is and oversight and (ITIS) work in progress still?

**Comment by yroskov** [comment]
Duplication of family Ceraphronidae: one branch in Ceraphronoidea another in Not assigned superfamily. FIXED in the clearinghouse. 

Duplicates created during re-assembly.
