### ISSUE TITLE
Some genera have author and year included

### ISSUE THREAD

**Issue by olafbanki** [CatalogueOfLife/data#215]
Here a couple of examples where the author and year appear in the genus name search:
https://www.catalogue.life/data/search.html?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&rank=genus&sortBy=taxonomic

A couple of genera highlighted that originate from different datasources (there are much more cases where this occurs):
https://www.catalogue.life/data/taxon/5QJT9 from Collembola
https://www.catalogue.life/data/taxon/4KD3E from World Plants
https://www.catalogue.life/data/taxon/UKGR from ITIS

**Comment by mdoering** [comment]
@olafbanki What exactly is the problem? Some genera have an authorship, others don't. That's expected as we slowly migrate to ColDP and not all sources even track authorship of genera.

**Comment by olafbanki** [comment]
I am just observing that some have it some do not. Did not know this is because of ColDP. Think it would be good to flag this in a frequently asked questions for users of the COL portal.

**Comment by mdoering** [comment]
The old format did not allow to share genus information, it was just about species. So no authorship ever existed for genera or higher taxa in COL. DwC & ColDP allow that

**Comment by olafbanki** [comment]
I was aware of this. It just did not sink in this would mean the author name and year would appear in the title of a genus name in a search. No worries it is understood now. For a user who is not aware of this it would be good to have this down in a FAQ. There may be more issues that could be captured in a FAQ. Perhaps I make an issue under portal to establish a FAQ, if it does not exist already.
