### ISSUE TITLE
Unranked Synonyms?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#217]
should the synonym not have a proper rank, e.g. genus?

<img width="1245" alt="Screenshot 2020-12-14 at 12 39 46" src="https://user-images.githubusercontent.com/327505/102077366-78f6cc80-3e09-11eb-8aaa-63d3d9522413.png">

https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Diptera&sortBy=taxonomic&type=EXACT

There are over 13.000 unranked synonyms, no accepted names. All of them from plants:

https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&rank=unranked&sortBy=taxonomic&type=EXACT

**Comment by yroskov** [comment]
Both links are empty on my screen. What's wrong?

![image](https://user-images.githubusercontent.com/28574252/102088530-aa0ed700-3de0-11eb-80ba-bbab3c9f6942.png)

![image](https://user-images.githubusercontent.com/28574252/102088577-b85cf300-3de0-11eb-8626-c7fb9f8c535e.png)

**Comment by mdoering** [comment]
see screenshot above for Diptera. The synonyms do not have any rank

**Comment by yroskov** [comment]
I cannot repeat your result for diptera.

In the Clearinghouse, I have only one Diptera as uninomial:

![image](https://user-images.githubusercontent.com/28574252/102094126-92871c80-3de7-11eb-8c5e-2ffd573e48c1.png)

Search in the portal is down:
![image](https://user-images.githubusercontent.com/28574252/102094010-6e2b4000-3de7-11eb-9d23-22622b8861dd.png)

**Comment by mdoering** [comment]
13.712 synonyms with `UNRANKED`: 
https://data.catalogueoflife.org/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&rank=unranked&sortBy=taxonomic

**Comment by yroskov** [comment]
My general answer, if the source database/checklist cannot provide us rank for synonym, automatically, this field will be empty during import in CoLDP.

**Comment by mdoering** [comment]
And with Capital "Diptera" you get it:
https://data.catalogueoflife.org/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Diptera&rank=unranked&sortBy=taxonomic

**Comment by mdoering** [comment]
Looks like this is a world plants issue. Is it wrong to infer rank genus for synonyms of a genus?
https://www.worldplants.de/world-plants-complete-list/complete-plant-list#1607956899

<img width="1127" alt="Screenshot 2020-12-14 at 15 44 20" src="https://user-images.githubusercontent.com/327505/102094993-43f77380-3e23-11eb-8eb4-0861a4a7ddd6.png">

**Comment by yroskov** [comment]
World Plant does not specify rank of synonym. Synonym for genus might be genus, as well as, subgenus, section or series. It will be risky for Geoff to estimate rank for synonym when he is crawling data in CoLDB.

**Comment by gdower** [comment]
As @yroskov mentioned, it's risky to add this data when it is not provided. When ranks are provided for synonyms, I add them.

**Comment by chantalhuijbers** [comment]
I will add this for our FAQ list.
