### ISSUE TITLE
Opiliones species

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#220]
COL has no species for Opiliones anymore which is a big loss. We have 374 genera, but no species. This is a major loss for an import, globally omnipresent group. I have provided links in #187 for alternative sources on suborder level with global coverage that could be used instead to fix at least the major groups.

**Comment by yroskov** [comment]
It's for Taxonomy Group

**Comment by mdoering** [comment]
How can we bring this best to their attention? There should be monthly meeting now. It would be great to get them to manage some of the issues here and always review them in their monthly meeting - if not already done before. How about labelling these issues with TaxonomyGroup? On the other hand all [source dataset request](https://github.com/CatalogueOfLife/data/labels/source%20dataset%20request) issues should be addressed by them I reckon.

**Comment by chuijbers** [comment]
We are starting monthly meetings with the Taxonomy Working Group as of this week (first meeting is this Wednesday 6 Jan). I will be supporting these meetings and will discuss how we can best list these kind of issues/requests to be discussed in the meetings.

**Comment by DaveNicolson** [comment]
I provided some info on Opiliones coverage in #187 that I should probably have put here... Basically, there are almost 1000 accepted species in ITIS in four completed superfamilies of Opiliones:
Superfamily: Travunioidea [1012404] (3 families)
Superfamily: Triaenonychoidea [1012405] (2 families)
Superfamily: Samooidea [1012406] (5 families)
Superfamily: Zalmoxoidea [1012407] (4 families)
Those superfamilies could be considered GSDs if you like. I'm not sure what complications, if any, there might be.

**Comment by mdoering** [comment]
@DaveNicolson that sounds like an easy addition we should immediately make
