### ISSUE TITLE
Botanical autonym with authorship and strange synonymy

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#221]
Alectoria sarmentosa from Kew exists twice in COL. Once without authorship and once with authorship.
The second one is considered a synonym for its autonym whic wrongly carries an authorship.

https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Alectoria%20sarmentosa%20%20%20%20%20&sortBy=taxonomic

https://www.catalogueoflife.org/data/taxon/5FHH7

**Comment by yroskov** [comment]
I guess, this is a problem in **Species Fungorum Plus** data delivered in CoLDP format. 

Trinomials in Species Fungorum often have no parent binomial. If parent binomial is built by the software, it has empty authorstring. Much more cases may appear in SFP checklist.

Not sure, what we can do with this. @gdower?

**Comment by yroskov** [comment]
I cannot see Alectoria sarmentosa with empty authorstring in the Cleringhouse/Workbench: 

 https://data.catalogueoflife.org/catalogue/3/dataset/2073/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Alectoria%20sarmentosa

![image](https://user-images.githubusercontent.com/28574252/103779021-c3c6c700-4ff8-11eb-8399-ddccad7325cf.png)

**Comment by yroskov** [comment]
Only 2 accepted names for Alectoria sarmentosa are in the Workbench. Both are trinomials (there is no parent binomial):

![image](https://user-images.githubusercontent.com/28574252/103779332-38016a80-4ff9-11eb-9e12-e21d6946a38b.png)

**Comment by yroskov** [comment]
Second problem in Species Fungorum dataset: parent binomial was moved to another accepted combination, but appropriate combinations for trinomials were not published yet. Paul delivers these trinomials as accepted taxa with "old names", but without parent binomial. Because, parent binomial placed in synonyms. We have tried to detect and manage such cases in old procedures (ac09-19).

**Comment by mdoering** [comment]
I see. When we sync infraspecific taxa into COL the sync always also creates a matching accepted species if it is missing.
In this case the species is considered a synonym, so the accepted species is missing and it is created without authorship. This leads to the duplication.

Frankly I do not quite understand what it means to have a subspecies with no parent species but instead treat the implicit species as a synonym for the autonym. Is this just wrong in SF and a data issue or is this a legid, meaningful treatment?

**Comment by yroskov** [comment]
I think, it because SF built as a taxonomic checklist on top of IF as nomenclator. When taxonomic decision was made, but new trinomial combinations were not published yet, SF keep "strange" records.

In the past, we have eliminated those accepted trinomials which have no accepted parent binomials.

**Comment by mdoering** [comment]
That makes sense. Should we maybe add a check for trinomials with a missing binomial to the tasks board?

**Comment by yroskov** [comment]
Good idea! Add a check for **accepted** trinomials with a missing **accepted** parent binomial to the tasks board. Note: such check has no meaning for synonyms.

It is better to place it in "Issues"

**Comment by mdoering** [comment]
adding this to issues during import checks
