### ISSUE TITLE
Angelica p. min. p.

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#228]
`Angelica p. min. p.` is a weird authorship in Synonymic Checklists of the Vascular Plants of the World:
https://www.catalogueoflife.org/data/taxon/W4K

It exists like this in the ColDP sources:
https://data.catalogueoflife.org/dataset/1141/verbatim?type=col%3AName&col:ID=Apiales-Apiaceae-Apioideae-Angelica&termOp=OR

and worse, it exists 3 times and the name id is not unique!
ID NOT UNIQUE is a rather serious issue we should never ignore

One of them is correct, but not used: Angelica L.

**Comment by yroskov** [comment]
Angelica pro minimam parte, means, genus Angelica in its narrow sense, excluding majority of other species currently belonging to other (probably unnamed yet) genera.

**Comment by yroskov** [comment]
It's funny: search for "p. min. p." does not work in the workbench. Is it because software removed it from the authorstring?

**Comment by mdoering** [comment]
sth like s.str. then, good to know.
The non unique ids needs fixing as the Linneaus version never gets used

**Comment by yroskov** [comment]
Angelica and few other genera resolved. 

Unfortunately, clearinghouse cannot give me a report on p.min.p., p.p., s.l., s.str. etc. cases.

**Comment by mdoering** [comment]
what are you looking for?

You can search verbatim data for anything, e.g `min.`: https://data.catalogueoflife.org/dataset/1141/verbatim?q=min.&type=col%3AName

And you can search names with `min.`:
https://data.catalogueoflife.org/dataset/1141/names?q=min.

**Comment by mdoering** [comment]
Unfortunately the name parser is not aware of `p. min. p.` yet, so its considered as the authorship:
https://data.catalogueoflife.org/dataset/1141/name/Apiales-Apiaceae-Apioideae-Conioselinum

Otherwise you would be able to list all names that do have a "name phrase" as part of their usage:
https://data.catalogueoflife.org/dataset/1141/names?field=name%20phrase
