### ISSUE TITLE
Missing synonyms for orchid Cymbidium

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#229]
WCVP does contain synonyms for the species in this genus:
https://data.catalogueoflife.org/dataset/1024/names?TAXON_ID=xHC&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0

But there are none in the latest COL release:
https://www.catalogueoflife.org/data/search?TAXON_ID=3YG4&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&rank=species

**Comment by Australis86** [comment]
Previous editions of the COL (last time I checked under the old infrastructure) correctly included these synonyms as well. They are present in the source KEW WSCP dataset as well and plenty are still in common use.

**Comment by yroskov** [comment]
CoL would be happy to update WCSP families with WCVP data. Unfortunately, available WCVP export in the clearinghouse has very limited data which do not match CoL requirements.

**Comment by mdoering** [comment]
Understood. But where has the old data gone? Should we not be able to bring back those missing synonyms?

**Comment by yroskov** [comment]
CoLs of 2005-2019 never had synonyms with taxa above species.

**Comment by mdoering** [comment]
We do not talk here about family or genus synonyms. It is the regular species synonyms that are missing, read above!

**Comment by yroskov** [comment]
All synonyms in AC19 sectors should be in their place. At least, I did not hear that synonyms were lost during migration from old to a new infrastructure.

**Comment by mdoering** [comment]
Well, then compare this example:

https://www.catalogueoflife.org/data/taxon/336F2

http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/aea2e72c5462a51a19ce1531e8dc70e8

We did lose synonyms. Please verify the amount of loss yourself!

**Comment by yroskov** [comment]
As I can see, all synonyms are available in the clearinghouse:
https://data.catalogueoflife.org/catalogue/3/dataset/1024/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Cymbidium

**Comment by mdoering** [comment]
I also linked at the top to the WCVP dataset in current use which *does* contain synonyms

**Comment by mdoering** [comment]
maybe just a matter of syncing again then

**Comment by yroskov** [comment]
OK, I'll re-sync WCSP Orchidaceae now.

**Comment by yroskov** [comment]
If it resolve the problem, I'll re-sync all WCSP sectors.

**Comment by yroskov** [comment]
The question, did CoL lost something else since we proved correct migration in a new software?

**Comment by yroskov** [comment]
383 synonyms are back after sync: 

https://data.catalogueoflife.org/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=500&offset=0&q=Cymbidium&reverse=false&sortBy=taxonomic&status=synonym

**Comment by yroskov** [comment]
Kick off sync of all WCSP sectors.

**Comment by yroskov** [comment]
The question remain, **did CoL lost something else since we proved correct migration in a new software?**
@gdower, any ideas for necessary steps?

**Comment by mdoering** [comment]
Cymbidium synonyms are present now in the draft!

Looking at the sync history for Asparagales all synonyms should have been there all the time.
There was just one sync over a year ago that had zero distributions - probably due to a bug then.

<img width="1199" alt="Screenshot 2021-01-20 at 03 31 56" src="https://user-images.githubusercontent.com/327505/105119267-44dd8e00-5ad0-11eb-9881-36faa195d0b8.png">

**Comment by Australis86** [comment]
Glad to hear that this is being resolved. Hopefully the underlying issue can be identified and won't reoccur.
