### ISSUE TITLE
Plant authorship BÃ¢n

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#242]
some plant names have UTF8 garbaged author `BÃ¢n`, e.g. [Goniothalamus dolichopetalus var. basilensis BÃ¢n](https://www.catalogueoflife.org/data/taxon/5P72C) which should be `Bân` as in the references and IPNI.

**Comment by yroskov** [comment]
Given example is from AnnonBase. We cannot fix encoding until we get a new export from the GSD or replace it with alternative resource.

**Comment by yroskov** [comment]
Hmm, it is strange, encoding is correct for majority of names: e.g. Goniothalamus gracilipes Bân (https://preview.catalogueoflife.org/data/taxon/3GXRH)

**Comment by mdoering** [comment]
You can just modify the ACEF file for AnnonBase and don't need to wait for an update.

**Comment by gdower** [comment]
Fixed: e5f4e20732858b758a189cd2ed03dfc72c3be77f

And also fixed distribution and lifezone: 9b395fcbe44f0e7dc84e196615e6b8857fea2dce
