### ISSUE TITLE
Use World Odonata List

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#244]
**Dataset title**
World Odonata List
**Dataset contact & access**
https://www.pugetsound.edu/academics/academic-resources/slater-museum/biodiversity-resources/dragonflies/world-odonata-list2/

There is an Excel sheet for download

**Taxonomic group & CoL sector**
Odonata

**Dataset description**
A global list actively maintained.

**Motivation for changing/adding**
The Odonata list in COL is static and from 2005, the base publication from the 1980ies.
It is coordinated with IUCN redlist names.
See also this very interesting discussion on iNaturalist about its use there: https://www.inaturalist.org/posts/11694-world-odonata-list

**Comment by jhnwllr** [comment]
I will try to make contact with the publishers of the **World Odonata List** and see if I can convince them to publish it as a dwc archive. 

I might be able to create the archive myself if they need help.

**Comment by mdoering** [comment]
Thanks! It would be good to get regular updates of the list in the future if we include them. At least once a year.

**Comment by jhnwllr** [comment]
We got a positive response from Dennis Paulson, and he would like the **World Odonata List** to be part of CoL. 

He also pointed to another list on Odonata Central
https://www.odonatacentral.org/#/

The list on Odonata Central is a copy of the Dennis Paulson list, but he says that he will eventually host his list on Odonata Central rather than on Slater Museum.   

**Odonata Central are already a GBIF publisher**, so could be nice to convince them to publish a checklist as well at least to GBIF, but it will probably just be a copy of the Dennis Paulson list.   
https://www.gbif.org/publisher/76591189-6f20-4784-8576-94eafe7a0aee

**I will proceed to convert the Dennis Paulson list into a dwc-a**, and we can probably do this until the list is hosted on Odonata Central exclusively...

**Comment by jhnwllr** [comment]
Indolestes divisus (Hagen in Selys, 1862)

These ok too? "Hagen in" meaning the author changed I guess?

**Comment by mdoering** [comment]
Yes, means the author Hagen described the species in the book/article of Selys. Thats part of regular name parsing too

**Comment by jhnwllr** [comment]
Wondering about "junior synonyms"? Is there a special way to handle these? 

"Macromia junior Pinhey, 1961"

**Comment by mdoering** [comment]
You can declare the dwc:taxonomicStatus to be "junior synonym", otherwise no. Just make sure you have the acceptedNameUsageID given. If possible please use parent/accepted/originalNameUsageID, and not the corresponding literal value terms. If you setup a hierarchy via IDs you also do not need any additional Linnean classification ranks like family.

**Comment by jhnwllr** [comment]
Ok I have made a dwca of the World Odonata List. 
https://github.com/jhnwllr/world-odonata-list-dwca
https://github.com/jhnwllr/world-odonata-list-dwca/blob/main/world-odonata-list-dwca.zip

Let me know if something needs to be changed...

**Comment by mdoering** [comment]
Excellent! I have created a new dataset in COL CLB here, currently importing: https://data.catalogueoflife.org/dataset/2335/about

**Comment by mdoering** [comment]
Can we add ORCIDs to the EML, a website & logo link?
And should @jhnwllr be part of the creators or rather metadata provider or an associated party? the first creator in COL will be the main author in the citation ...

**Comment by jhnwllr** [comment]
Yes I think Dennis Paulson should be the first author. And I should be some technical contact. 

I will ask Dennis for a Slater Museum logo. 

I can also see some issues that need to fixed still. 
https://data.catalogueoflife.org/dataset/2335/issues

**Comment by jhnwllr** [comment]
I fixed some of the CoL issues. I think the others can be ignored. 
https://github.com/jhnwllr/world-odonata-list-dwca/blob/main/world-odonata-list-dwca.zip

Will work on the meta data.

**Comment by jhnwllr** [comment]
OK @mdoering I have updated the meta-data. 

Dennis Paulson does not want to add a logo or ORCID ids at this time.

**Comment by mdoering** [comment]
@jhnwllr it might be simpler to use githubs zipping which removes the need to place a zip file into the repository.
if the world-odonata-list-dwca files are placed in the repos root folder you can access the entire zipped up repo like that:

https://github.com/jhnwllr/world-odonata-list-dwca/archive/refs/heads/main.zip

Using tags/releases one can even access older versions as zip files still.

It then does include the excel source and readme files, but I personally like that a lot and it does not break anything.
I regularly do this for all the dwca I create with the help of github.

**Comment by mdoering** [comment]
The latest version has lots of parent name mismatch issues: https://data.catalogueoflife.org/dataset/2335/issues

That actually is a problem for me to work on as the importer currently does not expect any authorship given in higher ranks such as the genus field. You can see it ends up with authorship as the uninomial: https://data.catalogueoflife.org/dataset/2335/name/xL9

Would you be able to create explicit genus records instead of relying on the flat classification? Using `parentNameUsageID` is much more robust and preferred in checklists than the flat ranks. If needed you can still mix the 2, e.g. use kingdom, phylum, class for the fixed context and family, genus, species and below as explicit records via parentNameUsageID.

**Comment by jhnwllr** [comment]
I have: 

- added a **parentNameUsageID** for the genus to species relationship 
- put everything into the main dir so that the github zipping trick works (thanks for that tip)
- removed authorships from genus

https://github.com/jhnwllr/world-odonata-list-dwca/archive/refs/heads/main.zip

**Comment by mdoering** [comment]
Great, looks much better:
https://data.catalogueoflife.org/dataset/2335/issues

There are still a few hundred infraspecies that are wrongly marked with rank=SPECIES. Example:
https://data.catalogueoflife.org/dataset/2335/name/8708

**Comment by jhnwllr** [comment]
I have added 
- **infraspecificEpithet** term
- **taxonRank**(s) present : genus, species, subspecies

**Comment by mdoering** [comment]
Looking good!
 https://data.catalogueoflife.org/dataset/2335/issues

**Comment by olafbanki** [comment]
World Odonata list (central) was added to the COL Checklist in January 2023 https://www.checklistbank.org/dataset/9859/about
