### ISSUE TITLE
Species Fungorum - Peltigera fuscopraetextata

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#270]
**Describe the problem**:
This is a request originally forwarded to the GBIF Helpdesk.
The person writing the feedback is asking if _Peltigera fuscopraetextata_ could be added to the taxonomy.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/6KFT

**Literature references**:
See the articles attached:
[Magain 2018.pdf](https://github.com/CatalogueOfLife/data/files/6598512/Magain.2018.pdf)
[miadlikowska2003.pdf](https://github.com/CatalogueOfLife/data/files/6598514/miadlikowska2003.pdf)
[obrien2009.pdf](https://github.com/CatalogueOfLife/data/files/6598516/obrien2009.pdf)

**Comment by yroskov** [comment]
Forwarded to Paul Kirk

**Comment by yroskov** [comment]
Paul's respond: 
The ‘name’ referred to below is a provisional name, a ‘designation’ sensu ICNafp and in the references cited there is no intention by the authors to formally publish the name, all mentions are enclosed in double quotes. As such, I am not inclined to add it to either Index Fungorum or Species Fungorum.

**Comment by ManonGros** [comment]
Thanks for letting me know, I will make sure that the people who sent us the request are informed.
