### ISSUE TITLE
Zygoneura genus accepted twice in Diptera

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#273]
https://www.catalogueoflife.org/data/search?q=Zygoneura&rank=genus

**Comment by yroskov** [comment]
Sent to Systema Dipterorum.

Genus Zygoneura (with 1 sp) in Mycetophilidae might be flagged as "provisionally accepted", if authors have no other solution.

**Comment by yroskov** [comment]
From: Thomas Pape 
Sent: Monday, June 14, 2021 10:51

Subject: RE: Systema Dipterorum v 3.1 in CoL

Dear Yury,

This relates to a record for the nominal taxon “Zygoneura winthemii Macquart, 1834”, which we treat as a “nomen dubium”.

These “nomina dubia” are old names, for which types have been lost, and we therefore cannot decide whether they represent an accepted name or not. Many of these most likely represent known species, but we cannot place them into synonymy without the types.

In this case we are dealing with a nominal species described in the genus Zygoneura (= Sciaridae), but which belongs in the family Mycetophilidae (based on the original illustration). Due to lack of data, we cannot place the species in any of the known genera, so we have -- for now -- kept it in the genus Zygoneura, where it was originally placed.

The “nomina dubia” in Systema Dipterorum will be given a better annotation for future versions, and they may actually better be excluded from the COL Checklist.

/Thomas

**Comment by yroskov** [comment]
Both, species and its parent genus, are blocked in CoL. 
Systema Dipterorum re-synced 2021-06-14.

**Comment by mdoering** [comment]
This looks like another case of a [species with an unplaced genus](https://github.com/CatalogueOfLife/coldp/issues/48), which can be dealt with in CLB by assigning the status provisionally accepted to the species and linking it straight to the family Mycetophilidae _without_ a redundant genus record for Zygoneura.

**Comment by TonyRees** [comment]
Hmmm... I checked my records and found only one record for the genus
Zygoneura (Meigen, 1830 in Sciaridae), as per Nomenclator Zoologicus and
www.diptera.org. It seems most likely to me that the assigned problem
species (Zygoneura winthemii Macquart, listed as Mycetophilidae, which
apparently formerly included Sciaridae), is simply misclassified to the
wrong family in Systema Dipterorum as per here:
http://www.diptera.org/Nomenclator/Details/204729, and that there are not 2
instances of Zygoneura. Maybe this could be clarified with a query to the
Systema Dipterorum responsible authors.

Regards - Tony

**Comment by TonyRees** [comment]
Sorry, I just saw that Thomas Pape has already commented above regarding
this name. So the species was assigned to the genus Zygoneura of Meigen,
1830 in Sciaridae, but is believed to belong in Mycetophilidae based on the
illustration. However taxonomic databases, and taxonomy generally, do not
permit a genus to exist in multiple families at the same time; therefore I
would submit that  Zygoneura winthemii should be assigned to Sciaridae,
where the genus name resides, in conflict with its present treatment in
www.diptera.org, with a note that this species probably belongs in the
Mycetophilidae (where it would of course require a different generic
name)... Not sure if Thomas is reading this, but that would be my solution
- unless you want to go down the "pro parte" route, not recommended by me!

Regards - Tony

Tony Rees, New South Wales, Australia
https://about.me/TonyRees

**Comment by mdoering** [comment]
... or keep the species under Mycetophilidae, flag it as provisional and do not link it to another Zygoneura genus, but straight to the family. That would be the recommended way in COL as the species then basically has an unknown current genus but can still use the old binomial.

**Comment by DaveNicolson** [comment]
Marcus’ solution sounds appropriate to me, for what it’s worth.
Dave N

Sent from my iPhone

On Jun 14, 2021, at 6:43 PM, Markus Döring ***@***.***> wrote:

﻿
External Email - Exercise Caution

... or keep the species under Mycetophilidae, flag it as provisional and do not link it to another Zygoneura genus, but straight to the family. That would be the recommended way in COL as the species then basically has an unknown current genus but can still use the old binomial.

**Comment by TonyRees** [comment]
OK... interesting that CoL can do this, whereas WoRMS and also IRMNG
require every species to have a parent at genus level - thus the species
record holds only the specific name, the genus is picked up via the parent,
which improves consistency and taxonomy drill-down (also makes
philosophical sense, to me at least). However if CoL can accommodate
"floating" binomials then maybe that works here. I still find it a bit of a
weird data model, though...
<https://about.me/TonyRees>
Regards - Tony

**Comment by mdoering** [comment]
COL separates names from taxonomy, so you can name taxa entirely independent from their classification. There are validations though that check for inconsistencies with the implicit classification given by a bi/trinomial.

**Comment by TonyRees** [comment]
OK ... not wishing to extend this discussion unduly, but if I as a user
downloaded CoL data expecting every genus name (initial portion of a
binomen) to be placed in a single point in the classification (homonyms
excepted), and it was not, that would cause me problems for data import...

I am guessing someone else thought it was an acceptable situation,
however...

Regards - Tony
