### ISSUE TITLE
Infraorder Spiruromorpha twice

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#280]
The infraorder Spiruromorpha exists twice, one being marked as provisional:

https://www.catalogueoflife.org/data/search?TAXON_ID=N&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&q=Spiruromorpha&rank=infraorder&sortBy=taxonomic

Provisional helps, but I would still expect the COL hierarchy to better curated to not have duplicates and take a decision on which placement is correct. Pushing the decision to users of COL is a pain.

**Comment by yroskov** [comment]
FIXED
