### ISSUE TITLE
Species Fungorum twice with many bare names

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#296]
Species Fungorum exists twice in CLB, we should delete the older one not used by COL anymore:

https://data.catalogueoflife.org/dataset/1028/about
https://data.catalogueoflife.org/dataset/2073/about

The 2073 version has 475k names compared to just 248k in 1028. There are 169k bare names which are probably wrong for a taxon database?

https://data.catalogueoflife.org/dataset/2073/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic&status=bare%20name

**Comment by yroskov** [comment]
These are two different datasets. 1028 is Species Fungorum as it is. 2073 is Species Fungorum Plus, which includes checklists from other authors, plus taxonomically unvetted names from Index Fungorum. Somebody has changed alias for 2073 without my knowledge.

**Comment by yroskov** [comment]
Forwarded to Neal

**Comment by mdoering** [comment]
It would be good to explain that in the metadata, both are called just `Species Fungorum` and are from Kew.
The Index Fungorum dataset hardly has any metadata

**Comment by mdoering** [comment]
What about the bare names?

Dacrymyces corticioides for example exists just as a bare name:
https://data.catalogueoflife.org/dataset/2073/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Dacrymyces%20corticioides&sortBy=taxonomic

It is apparently not part of SF, but found in IF: http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=242431
Does that mean all of IF is included as names and SF adds the Taxon/Synonym usage?
