### ISSUE TITLE
World Plants - Sambucus wightiana Wall. should be Sambucus wightiana Wall. ex Wight & Arn.

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#298]
**Describe the problem**:
A GBIF user claims (https://github.com/gbif/portal-feedback/issues/2968) that

**Sambucus wightiana Wall.** should be  **Sambucus wightiana Wall. ex Wight & Arn.**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/6XHXK (Sambucus wightiana Wall.)
https://www.catalogueoflife.org/data/dataset/1141 (World Plants)

**Literature references**:
https://tropicos.org/name/50009472

**Comment by yroskov** [comment]
Forwarded to Michael.
