### ISSUE TITLE
Systema Dipterorum - Culcio0myia

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#322]
Culcio0myia looks like a typo...

https://data.catalogueoflife.org/dataset/1101/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Culcio0myia&sortBy=taxonomic

**Comment by yroskov** [comment]
@fleshflyguy

**Comment by TonyRees** [comment]
The spelling is given in Neave as Culiciomyia Theobald, 1907, presumably this is the correct one (also in IRMNG, from that source).

**Comment by yroskov** [comment]
Fixed now in the source by Neal and in the CoL as a "complex decision"

![image](https://user-images.githubusercontent.com/28574252/132758653-5d7183ef-083d-4d86-a39f-3f14fe63ed89.png)
