### ISSUE TITLE
WSC - Pinkfloydia harveyi should be spelled Pinkfloydia harveii

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#341]
**Describe the problem**:
Issue originally logged on the GBIF Feedback portal: https://github.com/gbif/portal-feedback/issues/2020:

Pinkfloydia harveyi should be spelled Pinkfloydia harveii.

(I know you already forwarded the comment to the WSC, if they replied that the name should remain Pinkfloydia harveyi, please close this issue).

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/4HYQG

**Literature references**:
Dimitrov &Hormiga's 2011 paper
https://doi.org/10.1111/j.1096-3642.2010.00662.x

**Comment by yroskov** [comment]
Sent to WSC 2021-11-03

**Comment by yroskov** [comment]
Daniel Gloor: 
>Thanks for forwarding the issue. Please see the comment at https://wsc.nmbe.ch/species/36676
"The species epithet is a patronym after the Australian arachnologist Mark S. Harvey"; lapsus calami, cf. ICZN Article 32.5.1. - there is no note that the authors intended to latinize"
According to Theo Blick from the WSC Board, **there is no need to correct the specific epithet**.
Best regards, Daniel
