### ISSUE TITLE
LepIndex - possible synonym missing - Attacus atlas Linnaeus, 1758

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#344]
**Describe the problem**:
Would it make sense to add Phalaena atlas Linnaeus, 1758 as a synonym of Attacus atlas Linnaeus, 1758?

On GBIF, we seem to have both (https://github.com/gbif/portal-feedback/issues/2159) where Phalaena atlas Linnaeus, 1758 is from a PLAZI interpretation of a publication from Linnaeus: https://www.gbif.org/species/7376260 (see reference below). On the CoL/LepIndex, I couldn't see any synonym of Attacus atlas Linnaeus, 1758 nor any entry from P. atlas Linnaeus, 1758.

I assume that this is a question/issue for @dhobern?

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/JMDM

**Literature references**:
Systema Naturae per regna tria naturae: secundum classes, ordines, genera, species, cum characteribus, differentiis, synonymis, locis. Stockholm: Laurentius Salvius, DOI: https://doi.org/10.5962/bhl.title.542, URL: https://archive.org/download/mobot31753000798865/mobot31753000798865.pdf

**Comment by yroskov** [comment]
Yeah, it's for @dhobern. CoL will be happy to update LepIndex data with improved checklist.

**Comment by dhobern** [comment]
I've fixed SFG LepIndex to use Phalaena atlas as the original combination. I'm struggling to get the time to push these data to COL, but I hope it will be soon. Once we shift to using the SFG version, fixes can be made more easily.
