### ISSUE TITLE
WoRMS Mollusca - Mancinella bufo (Lamarck, 1822) should be Mancinella bufo Lamarck, 1822

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#348]
**Describe the problem**:
https://github.com/gbif/portal-feedback/issues/3730

**Mancinella bufo (Lamarck, 1822)** should be **Mancinella bufo Lamarck, 1822**
https://www.gbif.org/species/6125804

**Purpura bufo Lamarck, 1822** should be **Purpura bufo (Lamarck, 1822)**
https://www.gbif.org/species/5726043

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/4QK7R

**Comment by yroskov** [comment]
@bart-v, MolluscaBase team might be interested

**Comment by bart-v** [comment]
On it...

**Comment by bart-v** [comment]
The original combination is Purpura bufo Lamarck, 1822 (without brackets). See:
https://www.biodiversitylibrary.org/item/47433#page/249/mode/1up
Any other combination will have brackets

So there is no issue with WoRMS, MolluscaBase or CoL
