### ISSUE TITLE
Reptile DB with language as part of common name

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#352]
some vernacular names have the language given at the front of the actual name e.g. `(E) Freckled Monitor` or `(G) Trauerwaran`

https://data.catalogueoflife.org/dataset/1008/taxon/Reptilia-Squamata-Platynota-Varanidae-Varanus%20tristis-41ecd4c74f9a68152e708c6f4640ae6f

**Comment by yroskov** [comment]
@gdower, can your convertor script resolve this?

**Comment by gdower** [comment]
It only affects 2 records, so it would be best to report the issue to ReptileDB.

**Comment by yroskov** [comment]
2022-01-14, Peter wrote:
>Thanks for pointing that out.

I have changed it to the more common notation with single letter codes at the beginning of the line:

E: Black-tailed Monitor, Black-headed Monitor [tristis]
E: Freckled Monitor [orientalis]
G: Trauerwaran, Getüpfelter Baumwaran [orientalis]

However, note that subspecies require that I add them at the end of the line in square brackets.

There are a few other exceptions in non-European languages, such as Chinese (which are spelled out), e.g.

E: Spiny-headed seasnake 
Chinese: 棘眦海蛇

Cheers, Peter
