### ISSUE TITLE
1362 bare names in COL

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#369]
1362 bare names are present in COL incl higher ones that are immediately visible in the portal search:

https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&sortBy=taxonomic&status=bare%20name

I believe this was probably caused by a partial deletion or changes in sectors.

**Comment by yroskov** [comment]
Indeed, bare names should not be present in the CoL. 

Need to be deleted. Probably, after this issue will be resolved: 
![image](https://user-images.githubusercontent.com/28574252/145226858-65a4e5fc-b6e0-48d6-8296-85eee1d3a1b2.png)

**Comment by TonyRees** [comment]
I believe that we make an exception for genera in sectors that come from IRMNG, since IRMNG does not not supply species names... in any case I do not see any IRMNG-originating names there, at first glance, so that is probably accounted for...

- Tony

**Comment by yroskov** [comment]
@TonyRees, don't worry, IRMING names with accepted and synonymic statuses are not "bare names" in Markus sense.

**Comment by yroskov** [comment]
2021-12-15: 1,208 bare names blocked in dataset ID 3

https://data.catalogueoflife.org/catalogue/3/dataset/3/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=1000&offset=0&reverse=false&status=bare%20name

**Comment by yroskov** [comment]
Well, names blocked, but I have doubts that checklistbank can handle this correctly:

1) Selected all bare names, decision "Block" applied to all:
![image](https://user-images.githubusercontent.com/28574252/146211324-9e53fd12-1323-4313-81e5-2e3981e71a15.png)

2) Results:
![image](https://user-images.githubusercontent.com/28574252/146213010-6a5ea278-ff2d-4a69-9cc8-a8793b9b520c.png)

3) Page refreshed in the browser, and... no one decision saved!
![image](https://user-images.githubusercontent.com/28574252/146213325-a9d01cca-6fe7-4e94-9d8f-10fdb08e0b2a.png)

**Comment by yroskov** [comment]
@mdoering, if you wish, you can delete these names with your tools.

**Comment by mdoering** [comment]
Thanks @yroskov. I will try to delete all bare names as soon as I can. Blocking them will probably have no effect

**Comment by mdoering** [comment]
All 1340 bare names removed. There was a bug in the search that did not remove them from the search index, but I have fixed this. And turned on a new project setting that will delete all bare names before a project on release time.
