### ISSUE TITLE
Add ITIS contributor to metadata

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#374]
on request from Thomas Orrell:

> Can you add: Perez-Gelabert, Daniel My ORCID: orcid.org/0000-0003-3270-9551, Smithsonian Institution, Washington, D.C., United States of America - ITIS to the contributors.  Daniel is a primary data development specialist and entomologist and has added many GSD via ITIS to the COL

**Comment by mdoering** [comment]
@yroskov ITIS already contains metadata, so this ideally should go into their metadata.yaml.
Otherwise this needs to be a patch.

**Comment by mdoering** [comment]
the metadata included in the original ITIS archive does not seem to be hand crafted as it contains properties which are generated by the API and should not be present, e.g.:

```
private: false
size: 869110
attempt: 44
citation: '<div class="csl-entry"><span style="font-style: italic">The Integrated
  Taxonomic Information System</span> (Version 2021-12-02). (2021). https://itis.gov</div>'
imported: '2021-12-08T11:11:05.224554'
createdBy: 102
released: '2021-12-02'
```


None of these exist or ever existed in our [metadata.yaml reference](https://github.com/CatalogueOfLife/coldp/blob/master/metadata.yaml).

**Comment by yroskov** [comment]
@gdower, does clb able to use those metadata with ITIS updates? 

If yes, can we start to use them in Jan release and further, please? (@DaveNicolson, is it OK?)

**Comment by DaveNicolson** [comment]
Yes, you can implement whatever the change is in the next update (expected late December, possibly into January, what with people's vacations etc.).

**Comment by gdower** [comment]
@mdoering @yroskov, metadata for ITIS can be updated in clb. As a last step before uploading the new update, the converter fetches the metadata from the API and only updates the release date and version based on the release date in the ITIS zip archive, so the other metadata won't get overwritten.

**Comment by mdoering** [comment]
Thats good to know. You probably use the JSON endpoint, so that also explains where the non ColDP fields are coming from. They should simply be ignored, so that does not matter much.

**Comment by mdoering** [comment]
done: https://data.catalogueoflife.org/dataset/2144/about

**Comment by gdower** [comment]
@mdoering, it does look maybe I can update some fields that I probably shouldn't be able to update. After importing the Dec ITIS edition, it still says modifiedBy 101 (you) even though my user updated the metadata and dataset: http://api.catalogueoflife.org/dataset/2144.json

Is that the expected behavior? I can modify the script to drop those extra fields.

**Comment by mdoering** [comment]
Those extra fields incl createdBy and modifiedBy should just be ignored. Did your script to the last update at
> "modified":"2021-12-23T21:22:47.865407",

using your personal account?
