### ISSUE TITLE
LepIndex - Loxerebia phyllis Leech, 1891 -  possibly missing parenthesis

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#378]
**Describe the problem**:
Feedback originally provided on the GBIF Feedback portal: https://github.com/gbif/portal-feedback/issues/3818
I assume that the user is reporting missing parenthesis and suggests to update the name to: Loxerebia phyllis (Leech, 1891)

They don't provide any reference (but I can see that this is how wikipedia spells it). Feel free to discard the issue isn't relevant.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3W8WG

**Literature references**:
None.

**Comment by yroskov** [comment]
@dhobern, it's for you

(Parentheses are lost in all subsequent combinations in LepIndex CoL view of 2012)

**Comment by dhobern** [comment]
This one is already correct in SFG LepIndex - another incentive for me to hurry up and replace the current version on COL. Working on it.
