### ISSUE TITLE
Asaphodes - New Zealand endemic moth genus 

### ISSUE THREAD

**Issue by SiobhanLeachman** [CatalogueOfLife/data#391]
The taxonomy of many of the species currently within this genus have out of date taxonomy in the CoL database, likely as a result of the LepIndex being out of date. Some species are not listed in the CoL database. If this issue could be assigned to @dhobern I would be grateful as I believe it falls within the LepIndex Lepidoptera project. 
...

**Link to effected CoL webpages**:
I've collated all the CoL webpage links here in this [google sheet](https://docs.google.com/document/d/1t83xA89ww3rrAPEuxBKMqSb0MYZzYE9waEuRD6G6QZg/edit?usp=sharing) but will copy the same below.
Asaphodes abrogata  (Walker, 1862) No Catalogue of life link to species.    
Asaphodes adonis (Hudson, 1898) https://www.catalogueoflife.org/data/taxon/6NXXW (Larentia adonis Hudson, 1928) 
Asaphodes aegrota (Butler, 1879)  https://www.catalogueoflife.org/data/taxon/6NXY8 (Larentia aegrota Butler, 1879)
Asaphodes albalineata (Philpott, 1915) https://www.catalogueoflife.org/data/taxon/6NXXV (Larentia albalineata Philpott, 1915)
Asaphodes aphelias (Prout, 1939) https://www.catalogueoflife.org/data/taxon/7G939 (Xanthorhoe aphelias Prout, 1939) 
Asaphodes beata (Butler, 1877) https://www.catalogueoflife.org/data/taxon/6NXXQ (Larentia beata Butler, 1877)
Asaphodes camelias (Meyrick, 1888) https://www.catalogueoflife.org/data/taxon/5C7VL (Xanthorhoe camelias Meyrick, 1887) 
Asaphodes campbellensis (Dugdale, 1964) https://www.catalogueoflife.org/data/taxon/5C7VM   (Xanthorhoe campbellensis Dugdale, 1964)
Asaphodes cataphracta (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/5C7VP (Xanthorhoe cataphracta Meyrick, 1883)
Asaphodes chionogramma (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/7G8QK    Xanthorhoe chionogramma Meyrick, 1883
Asaphodes chlamydota (Meyrick, 1883 https://www.catalogueoflife.org/data/taxon/6NXY4)   Larentia chlamydota Meyrick, 1883
Asaphodes chlorocapna (Meyrick, 1925) https://www.catalogueoflife.org/data/taxon/5C7VV  (Xanthorhoe chlorocapna Meyrick, 1925) 
Asaphodes cinnabari (Howes, 1912) https://www.catalogueoflife.org/data/taxon/5C7VW (Xanthorhoe cinnabari Howes, 1912) 
Asaphodes citroena (Clarke, 1934) https://www.catalogueoflife.org/data/taxon/5C7VX (Xanthorhoe citroena Clarke, 1934)
Asaphodes clarata (Walker, 1862) https://www.catalogueoflife.org/data/taxon/5C7VZ  Xanthorhoe clarata Walker, 1862
Asaphodes cosmodora (Meyrick, 1888) No Catalogue of life link to species. Synonym does have page https://www.catalogueoflife.org/data/taxon/5C7VF   Xanthorhoe bryopis Meyrick, 1887
Asaphodes declarata (Prout, 1914) https://www.catalogueoflife.org/data/taxon/5C7WH (Xanthorhoe declarata Prout, 1914)  
Asaphodes dionysias (Meyrick, 1907) https://www.catalogueoflife.org/data/taxon/6NY9M  (Larentia dionysias Meyrick, 1907)
Asaphodes exoriens (Prout, 1912) https://www.catalogueoflife.org/data/taxon/6NY9N (Larentia exoriens Prout, 1912)  
Asaphodes frivola (Meyrick, 1913) https://www.catalogueoflife.org/data/taxon/7G92L (Xanthorhoe frivola Meyrick, 1913)
Asaphodes glaciata (Hudson, 1925) https://www.catalogueoflife.org/data/taxon/5C7XK (Xanthorhoe glaciata Hudson, 1928)
Asaphodes helias (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/5C7XS (Xanthorhoe helias Meyrick, 1883)  
Asaphodes ida (Clarke, 1926) https://www.catalogueoflife.org/data/taxon/5C7Y6 (Xanthorhoe ida Clarke, 1926)  
Asaphodes imperfecta (Philpott, 1905) https://www.catalogueoflife.org/data/taxon/6NY9K (Larentia imperfecta Philpott, 1905) 
Asaphodes limonodes (Meyrick, 1888) https://www.catalogueoflife.org/data/taxon/6NY9D (Larentia limonodes Meyrick, 1887)
Asaphodes mnesichola (Meyrick, 1888) https://www.catalogueoflife.org/data/taxon/5C7Z7 (Xanthorhoe mnesichola Meyrick, 1887) 
Asaphodes nephelias (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/5C7ZG (Xanthorhoe nephelias Meyrick, 1882) 
Asaphodes obarata (Felder & Rogenhofer, 1875) https://www.catalogueoflife.org/data/taxon/5C7ZK (Xanthorhoe obarata Felder, 1875) 
Asaphodes omichlias (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/47YBB (Notoreas omichlias Meyrick, 1883) 
Asaphodes oraria (Philpott, 1903) https://www.catalogueoflife.org/data/taxon/6NXXB (Larentia oraria Philpott, 1903)
Asaphodes oxyptera (Hudson, 1909)  https://www.catalogueoflife.org/data/taxon/5C7ZV (Xanthorhoe oxyptera Hudson, 1909)
Asaphodes periphaea (Meyrick, 1905) https://www.catalogueoflife.org/data/taxon/5C826 (Xanthorhoe periphaea Meyrick, 1905)   - GBIF lists Asaphodes peripheraea as this species’ name however this is a misspelling of the species originally by Dugdale in 1971 and repeated by him in 1988.
Asaphodes philpotti (Prout, 1927) No catalogue of life link to species.
Asaphodes prasinias (Meyrick, 1883) https://www.catalogueoflife.org/data/taxon/6NY8X (Larentia prasinias Meyrick, 1884)
Asaphodes prymnaea (Meyrick, 1911) https://www.catalogueoflife.org/data/taxon/5C82N (Xanthorhoe prymnaea Meyrick, 1910) 
Asaphodes recta (Philpott, 1905) https://www.catalogueoflife.org/data/taxon/6NXWW   (Larentia recta Philpott, 1905 ) 
Asaphodes sericodes (Meyrick, 1915) https://www.catalogueoflife.org/data/taxon/6NXWZ (Larentia sericodes Meyrick, 1915)  
Asaphodes stephanitis Meyrick, 1907 No Catalogue of life link to species.   
Asaphodes stinaria (Guenee, 1868) https://www.catalogueoflife.org/data/taxon/5C83H (Xanthorhoe stinaria Guenée, 1868)  

**Literature references**:
I've already updated all the Wikipedia pages for each of these species and these pages link to all the appropriate scientific literature. You can reach those pages via the [Asaphodes](https://en.wikipedia.org/wiki/Asaphodes) genus wikipedia page.
Some of the main resources referred to are as follows:
George Vernon Hudson (1898), New Zealand moths and butterflies (Macro-lepidoptera), Illustrator: George Hudson, London, p. 63, doi:10.5962/BHL.TITLE.7912, OCLC 980865393, Wikidata Q19073637
George Vernon Hudson (1928), The butterflies and moths of New Zealand, Illustrator: George Hudson, Wellington, p. 120, OCLC 25449322, Wikidata Q58593286
J. S. Dugdale (10 November 1971). "Entomology of the Aucklands and other islands south of New Zealand: Lepidoptera, excluding non-crambine Pyralidae" (PDF). Pacific Insects Monographs. 27: 93–95. ISSN 0078-7515. Wikidata Q64006453.
John Stewart Dugdale (23 September 1988). "Lepidoptera - annotated catalogue, and keys to family-group taxa" (PDF). Fauna of New Zealand. Department of Scientific and Industrial Research. 14: 171. doi:10.7931/J2/FNZ.14. ISSN 0111-5383.
[New Zealand Organisms Register](https://www.nzor.org.nz/search)
Gordon, Dennis P., ed. (2010). New Zealand inventory of biodiversity: Kingdom animalia : chaetognatha, ecdysozoa, ichnofossils. Vol. 2. p. 459. ISBN 978-1-877257-93-3. OCLC 973607714. OL 25288394M. Wikidata Q45922947.

**Comment by dhobern** [comment]
Thanks @SiobhanLeachman - I'll get to it soon.

**Comment by dhobern** [comment]
@SiobhanLeachman @yroskov This issue made my day. When I went to make the necessary changes to the TaxonWorks version of Asaphodes, I found that Ian Kitching had already made every single change. This genus will be fixed as soon as we but over to that version.

See the names in ChecklistBank now: https://data.catalogueoflife.org/dataset/2272/names?TAXON_ID=260517

**Comment by dhobern** [comment]
FYI - I see this as an arbitrary but valuable piece of validation for the new version.

**Comment by SiobhanLeachman** [comment]
So pleased that others are interested in NZ endemic moths! Also really pleased to see so many folk working hard on the new version of CofL as it will have a massive flow on effect.
