### ISSUE TITLE
Unexpected decision logs

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#397]
Here are some log entries I found that warn about a decision that tries to change the status of an accepted taxon to a synonym.
This is not allowed/supported. These decisions will be ignored during a sync. But maybe it is worht looking through them and potentially deleting or updating them? The list here is far from being complete and just some help to investigate the situation:

```
Cannot convert SPECIES ACCEPTED Astragalus ameghinoi Speg. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Astragalus assadabadensis F. Ghahrem. & Podlech into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Astragalus pelecinus (L.) Barneby into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Capparis viminea Hook. fil. & Thomson into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Ficus microsyce Ridl. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Ficus pachyclada Baker into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Ficus gasparriniana Miq. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Dorstenia ramosa (Desv.) Carauta, C. Valente & Sucre into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Morus microphylla Buckley into AMBIGUOUS_SYNONYM
Cannot convert SPECIES SYNONYM Taraxacum venustum Koidz. into PROVISIONALLY_ACCEPTED
Cannot convert SUBSPECIES ACCEPTED Youngia japonica subsp. longiflora Babc. & Stebbins into AMBIGUOUS_SYNONYM
Cannot convert SUBSPECIES ACCEPTED Lapsana communis subsp. alpina (Boiss. & Balansa) P. D. Sell into AMBIGUOUS_SYNONYM
Cannot convert SUBSPECIES ACCEPTED Hieracium schmidtii subsp. residuum Norrl. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES SYNONYM Hieracium atriglandulosum P. D. Sell into PROVISIONALLY_ACCEPTED
Cannot convert SUBSPECIES ACCEPTED Hieracium laevigatum subsp. stricticaule (Jord. ex Boreau) Zahn into AMBIGUOUS_SYNONYM
Cannot convert SUBSPECIES ACCEPTED Hieracium murorum subsp. carcarophyllum (Johanss.) Zahn into AMBIGUOUS_SYNONYM
Cannot convert SUBSPECIES ACCEPTED Hieracium subramosum subsp. subramosum into AMBIGUOUS_SYNONYM
Cannot convert VARIETY ACCEPTED Artemisia anomala var. acuminatissima Y. R. Ling into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Saussurea acuminata Turcz. ex Fisch. & C. A. Mey. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Centaurea sarandinakiae N. B. Illar. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Centaurea tauscheri A. Kern. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Centaurea aristata Hoffmanns. & Link into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Centaurea ainetensis Boiss. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Psephellus abchasicus Albov into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Carduus fissurae Ny?r. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Carthamus lanatus L. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Carduncellus dianius Webb into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Cirsium ?  wettsteinii Petr. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Cirsium hypopsilum Boiss. & Heldr. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Jurinea ledebourii Bunge into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Jurinea gilliatii Turrill into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Pleiotaxis antunesii O. Hoffm. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Elephantopus tomentosus L. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Berkheya echinacea (Harv.) Burtt Davy into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Taraxacum dentosum M. P. Christ. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Taraxacum pallescens Dahlst. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Taraxacum subexpallidum Dahlst. into AMBIGUOUS_SYNONYM
Cannot convert SPECIES ACCEPTED Taraxacum subdahlstedtii M. P. Christ. into AMBIGUOUS_SYNONYM

```

**Comment by yroskov** [comment]
It's not clear to me, how these decisions may appear?

**Comment by yroskov** [comment]
Investigation: name status as now 2022-02-28 vs status in ac21 2021-07-29:  

**Astragalus ameghinoi**

Now:
![image](https://user-images.githubusercontent.com/28574252/156023539-33eb09b2-321e-4745-9150-5d611722794a.png)

In ac21:
![image](https://user-images.githubusercontent.com/28574252/156024958-96b623a8-e892-4a41-aec5-a5f55f76f96a.png)

**Astragalus assadabadensis**

Now:
![image](https://user-images.githubusercontent.com/28574252/156024010-d73f8296-5577-439e-a5de-40f06b32ab5c.png)
![image](https://user-images.githubusercontent.com/28574252/156024160-ce9440c0-725f-4efb-8417-656ebc0b1818.png)

In ac21:
![image](https://user-images.githubusercontent.com/28574252/156025115-e1480417-e6a2-4a32-8731-367e7e776525.png)

**Jurinea ledebourii**

Now:
![image](https://user-images.githubusercontent.com/28574252/156024398-32db4066-fdc9-419b-b793-a854a90ee686.png)

In ac21:
![image](https://user-images.githubusercontent.com/28574252/156025262-738bf99c-3d8c-4a0b-a5db-fff4305bfef5.png)

**Comment by yroskov** [comment]
_My conclusion:_ it looks like, position of the name in the classification in the source checklist was changed, but my editorial decision remains glued to the name (or nameID ?).

For example, there were 2 names **Astragalus ameghinoi** in the past (one as an accepted, second as a synonym), and there is only one name in recent checklist, and now old decision attached to this single name. This is incorrect.

1) Do we have similar cases in GSDs other than World Plants? (I will not be surprisedm that the case might be specific to the WPlants, because there are no name IDs in the source).

2) How to manage this situation? 
(My initial idea for a quick simple solution is to identify and delete all decisions through all GSDs which change name status from Acc to Ambig Syn).

**Comment by gdower** [comment]
Originally back in [AC2019](https://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Astragalus+ameghinoi/fossil/1/match/1) and version 2020-12-17, there was an accepted name _Astragalus ameghinoi_ with the accepted ID `Fabales-Fabaceae-Astragalus-ameghinoi-Speg.`, and an ambiguous synonym  _Astragalus ameghinoi_ for the accepted name _Astragalus vesiculosus_ with the synonym ID `Fabales-Fabaceae-Astragalus-vesiculosus-Clos-Astragalus ameghinoi Speg.` so I don't think it's a bug with IDs in the World Plants converter because the accepted and synonym IDs weren't the same.

@mdoering, is it correct for the decision subject ID to be `Fabales-Fabaceae-Astragalus-ameghinoi-Speg.` which is the accepted ID? If not, I'm not sure how that was set.

```json
{
    "created": "2020-10-08T19:07:21.579545",
    "createdBy": 102,
    "modified": "2021-12-10T17:56:15.807503",
    "modifiedBy": 102,
    "datasetKey": 3,
    "id": 203340,
    "subject": {
        "id": "Fabales-Fabaceae-Astragalus-ameghinoi-Speg.",
        "name": "Astragalus ameghinoi",
        "authorship": "Speg.",
        "rank": "species",
        "broken": false,
        "label": "Astragalus ameghinoi Speg.",
        "labelHtml": "<i>Astragalus ameghinoi</i> Speg."
    },
    "originalSubjectId": "Fabales-Fabaceae-Astragalus-vesiculosus-Clos-Fabales-Fabaceae-Astragalus-vesiculosus-Clos-Astragalus ameghinoi Speg.",
    "subjectDatasetKey": 1141,
    "mode": "update",
    "status": "ambiguous synonym"
}
```

**Comment by mdoering** [comment]
This seems important to understand and to get right to not apply wrong decisions. So let me explain how things are working - then we can better discuss if sth should be changed in the code & procedures, if it's just wrong data or sth else.

Decision just like sectors are linked to source data via the unique identifier of the record. This id is given in subject.id, e-g. `Fabales-Fabaceae-Astragalus-ameghinoi-Speg.` in the example above. As we know ids can change in sources. That is why we allow for rematching of broken subjects. A decision (and sector) is considered broken, if the subject ID does no longer exist in the source dataset. When a subject is rematched, all the other subject properties are considered to find the right record. In the case above the newly matched record MUST have all of these:
 -  "name": "Astragalus ameghinoi"
 -  "authorship": "Speg."
 -  "rank": "species"

If the source record changes, e.g. the Author now is "Sp.", there will be no match and the decision remains as broken and will not be applied during syncs.  If there are _multiple_ matches, also no match will be returned and the decision remains broken.

This means the number of properties stored for a decision is very important for its "stability".
In addition to `name`, `authorship` and `rank` there are also `status` and `parent` to make sure the record has a specific status and parent. That is key for the duplicate detection and ambiguous synonyms. I am not sure what the UI actually does when you create a decision. @thomasstjerne does the UI always populate all fields including the status & parent? Or do we add the parent only for certain decisions? In the case above there is no parent or status, so it will match to any record of species Astragalus ameghinoi Speg., no matter where it is placed and which status it has.

When a source is newly imported the default behaviour is to do nothing. If the IDs are stable the decision and sectors are still linked correctly, unless the record was removed in the source. There is a dataset setting `REMATCH_DECISIONS` that can be turned on to always rematch all of its decisions and sectors whenever a new import happens. This is true for most of our GSDs as far as I can see:

```
 key  |         alias          | rematch 
------+------------------------+---------
 1502 | Animal Biodiversity    | true
 1040 | AnnonBase              | true
 2130 | Collembola.org         | true
 1011 | FLOW                   | true
 2141 | HymIS Pompilidae       | true
 2144 | ITIS                   | true
 2253 | MilliBase dev          | true
 2154 | Neuropterida CoLDP     | true
 1199 | Pterophoroidea         | true
 1206 | Sepidiini tribe        | true
 2073 | Species Fungorum Plus  | true
 1164 | The Scorpion Files     | true
 1029 | WSC                    | true
 1176 | WoRMS Actiniaria       | true
 1202 | WoRMS Amphipoda        | true
 1194 | WoRMS Antipatharia     | true
 1178 | WoRMS Appendicularia   | true
 1186 | WoRMS Ascidiacea       | true
 1095 | WoRMS Asteroidea       | true
 1086 | WoRMS Bochusacea       | true
 2299 | WoRMS Brachiopoda      | true
 1087 | WoRMS Brachypoda       | true
 1108 | WoRMS Brachyura        | true
 1081 | WoRMS Bryozoa          | true
 1154 | WoRMS Cephalochordata  | true
 1179 | WoRMS Ceriantharia     | true
 1127 | WoRMS Cestoda          | true
 1132 | WoRMS Chaetognatha     | true
 1191 | WoRMS Copepoda         | true
 1195 | WoRMS Corallimorpharia | true
 2300 | WoRMS Crinoidea        | true
 1180 | WoRMS Ctenophora       | true
 1181 | WoRMS Cubozoa          | true
 1058 | WoRMS Cumacea          | true
 1106 | WoRMS Echinoidea       | true
 2277 | WoRMS Echiura          | true
 2301 | WoRMS Euphausiacea     | true
 1157 | WoRMS Foraminifera     | true
 1122 | WoRMS Gastrotricha     | true
 1125 | WoRMS Gnathostomulida  | true
 1107 | WoRMS Holothuroidea    | true
 1112 | WoRMS Hydrozoa         | true
 1094 | WoRMS Isopoda          | true
 1153 | WoRMS Kinorhyncha      | true
 1105 | WoRMS Leptostraca      | true
 1182 | WoRMS Loricifera       | true
 1152 | WoRMS Merostomata      | true
 1200 | WoRMS MilliBase        | true
 1130 | WoRMS Mollusca         | true
 1126 | WoRMS Monogenea        | true
 1088 | WoRMS Mystacocarida    | true
 1129 | WoRMS Myxozoa          | true
 1085 | WoRMS Nemertea         | true
 2302 | WoRMS Nemys            | true
 1131 | WoRMS Octocorallia     | true
 1099 | WoRMS Oligochaeta      | true
 1059 | WoRMS Ophiuroidea      | true
 1149 | WoRMS Orthonectida     | true
 1175 | WoRMS Ostracoda        | true
 2323 | WoRMS Ostracoda        | true
 1123 | WoRMS Placozoa         | true
 1090 | WoRMS Polychaeta       | true
 1109 | WoRMS Polycystina      | true
 1044 | WoRMS Porifera         | true
 1124 | WoRMS Priapulida       | true
 1183 | WoRMS Pycnogonida      | true
 1091 | WoRMS Remipedia        | true
 1150 | WoRMS Rhombozoa        | true
 1196 | WoRMS Scleractinia     | true
 1188 | WoRMS Scyphozoa        | true
 1184 | WoRMS Staurozoa        | true
 1103 | WoRMS Strepsiptera     | true
 1110 | WoRMS Tanaidacea       | true
 1092 | WoRMS Tantulocarida    | true
 1185 | WoRMS Thaliacea        | true
 1093 | WoRMS Thermosbaenacea  | true
 1128 | WoRMS Trematoda        | true
 1193 | WoRMS Turbellarians    | true
 1100 | WoRMS Xenoturbellida   | true
 1197 | WoRMS Zoantharia       | true
 1140 | World Ferns            | true
 1141 | World Plants           | false
 2124 |                        | true
 2155 |                        | true
 2158 |                        | true
 2160 |                        | true
 2276 |                        | true

```

**Comment by mdoering** [comment]
I forgot one more thing: `originalSubjectId`. This is the ID of the source record that existed when the decision was created.
Rematching will always try first to reuse that. If it still exists in the source and still matches the other properties then it will be used preferrably.

**Comment by mdoering** [comment]
> @mdoering, is it correct for the decision subject ID to be `Fabales-Fabaceae-Astragalus-ameghinoi-Speg.` which is the accepted ID? If not, I'm not sure how that was set.

The id has changed because of rematching when the old id was removed, which is stored in `"originalSubjectId": "Fabales-Fabaceae-Astragalus-vesiculosus-Clos-Fabales-Fabaceae-Astragalus-vesiculosus-Clos-Astragalus ameghinoi Speg."`. And because there is no status or parent part of the decision subject data, the decision also matches the accepted name. In this case the decision is not executed as there is a blocker that prevents turning an accepted name into a synonym and vice versa. But it's not good we now have a wrong match.

To prevent that from happening at least the status should have been recorded. If I look at newly created decisions in dev, both status and parent is recorded, e.g. https://api.dev.checklistbank.org/dataset/2088/decision/4

```
{
    "created": "2022-02-24T11:53:07.742562",
    "createdBy": 100,
    "modified": "2022-02-24T11:53:07.742562",
    "modifiedBy": 100,
    "datasetKey": 2088,
    "id": 4,
    "subject": {
        "id": "family:thaspiviridae",
        "name": "Thaspiviridae",
        "rank": "family",
        "code": "virus",
        "status": "accepted",
        "parent": "Viruses",
        "broken": false,
        "label": "Thaspiviridae",
        "labelHtml": "Thaspiviridae"
    },
    "originalSubjectId": "family:thaspiviridae",
    "subjectDatasetKey": 1014,
    "mode": "block"
}
```

@thomasstjerne did this maybe change over time? I suspect we did not record all details in the very beginning.
I will look up counts for that...

**Comment by thomasstjerne** [comment]
Yes I believe it changed at some point. The UI tries to populate the decision object with all known information about the subject (name, authorship rank, status, parent, code).
But it has been like this for a long time now

**Comment by mdoering** [comment]
All decisions by month and creator:

```
col=> select u.username, date_trunc('month', d.created), count(*) from decision d join "user" u on u.key=d.created_by where dataset_key=3 group by 1,2 order by 2;
 username |     date_trunc      | count 
----------+---------------------+-------
 gdower   | 2020-01-01 00:00:00 |     2
 yroskov  | 2020-01-01 00:00:00 |  1411
 yroskov  | 2020-02-01 00:00:00 |     7
 yroskov  | 2020-03-01 00:00:00 |  4126
 markus   | 2020-04-01 00:00:00 |     2
 yroskov  | 2020-04-01 00:00:00 |   155
 yroskov  | 2020-05-01 00:00:00 |  1620
 yroskov  | 2020-06-01 00:00:00 |  9962
 gdower   | 2020-07-01 00:00:00 |     2
 markus   | 2020-07-01 00:00:00 |     1
 yroskov  | 2020-07-01 00:00:00 |   984
 yroskov  | 2020-08-01 00:00:00 |    38
 yroskov  | 2020-09-01 00:00:00 |  8631
 yroskov  | 2020-10-01 00:00:00 | 24062
 yroskov  | 2020-12-01 00:00:00 |   475
 yroskov  | 2021-01-01 00:00:00 |  1586
 yroskov  | 2021-02-01 00:00:00 |   351
 yroskov  | 2021-03-01 00:00:00 |  6790
 yroskov  | 2021-04-01 00:00:00 |  1049
 yroskov  | 2021-05-01 00:00:00 |  9938
 gdower   | 2021-06-01 00:00:00 |  1155
 yroskov  | 2021-06-01 00:00:00 |  3900
 yroskov  | 2021-07-01 00:00:00 |   152
 yroskov  | 2021-08-01 00:00:00 |  5827
 yroskov  | 2021-09-01 00:00:00 |  1809
 yroskov  | 2021-10-01 00:00:00 | 24642
 yroskov  | 2021-11-01 00:00:00 |   998
 yroskov  | 2021-12-01 00:00:00 |  2347
 yroskov  | 2022-01-01 00:00:00 |    75
 yroskov  | 2022-02-01 00:00:00 |   409
```

Here is a summary of decisions which miss both status & parent:
```
 username |     date_trunc      | count 
----------+---------------------+-------
 yroskov  | 2020-01-01 00:00:00 |  1411
 yroskov  | 2020-03-01 00:00:00 |  4123
 yroskov  | 2020-04-01 00:00:00 |   118
 yroskov  | 2020-05-01 00:00:00 |  1060
 yroskov  | 2020-06-01 00:00:00 |  9931
 yroskov  | 2020-07-01 00:00:00 |   908
 yroskov  | 2020-08-01 00:00:00 |    36
 yroskov  | 2020-09-01 00:00:00 |  8585
 yroskov  | 2020-10-01 00:00:00 | 23212
 yroskov  | 2020-12-01 00:00:00 |   422
 yroskov  | 2021-01-01 00:00:00 |  1551
 yroskov  | 2021-02-01 00:00:00 |    69
 yroskov  | 2021-03-01 00:00:00 |  6697
 yroskov  | 2021-04-01 00:00:00 |   992
 yroskov  | 2021-05-01 00:00:00 |  5434
 yroskov  | 2021-06-01 00:00:00 |  3172
 yroskov  | 2021-07-01 00:00:00 |   151
 yroskov  | 2021-08-01 00:00:00 |  5811
 yroskov  | 2021-09-01 00:00:00 |  1311
 yroskov  | 2021-10-01 00:00:00 | 21737
 yroskov  | 2021-11-01 00:00:00 |   870
 yroskov  | 2021-12-01 00:00:00 |    86
 yroskov  | 2022-01-01 00:00:00 |    51
 yroskov  | 2022-02-01 00:00:00 |   391
```


And the same also broken down also by the decision mode:

```
col=> select u.username, date_trunc('month', d.created), mode, count(*) from decision d join "user" u on u.key=d.created_by where dataset_key=3 and subject_parent is null and subject_status is null group by 1,2,3 order by 2;
 username |     date_trunc      |  mode  | count 
----------+---------------------+--------+-------
 yroskov  | 2020-01-01 00:00:00 | BLOCK  |     6
 yroskov  | 2020-01-01 00:00:00 | UPDATE |  1405
 yroskov  | 2020-03-01 00:00:00 | UPDATE |  4123
 yroskov  | 2020-04-01 00:00:00 | BLOCK  |    21
 yroskov  | 2020-04-01 00:00:00 | UPDATE |    97
 yroskov  | 2020-05-01 00:00:00 | BLOCK  |    26
 yroskov  | 2020-05-01 00:00:00 | UPDATE |  1034
 yroskov  | 2020-06-01 00:00:00 | BLOCK  |   229
 yroskov  | 2020-06-01 00:00:00 | UPDATE |  9702
 yroskov  | 2020-07-01 00:00:00 | BLOCK  |    22
 yroskov  | 2020-07-01 00:00:00 | UPDATE |   886
 yroskov  | 2020-08-01 00:00:00 | BLOCK  |     2
 yroskov  | 2020-08-01 00:00:00 | UPDATE |    34
 yroskov  | 2020-09-01 00:00:00 | BLOCK  |   137
 yroskov  | 2020-09-01 00:00:00 | UPDATE |  8448
 yroskov  | 2020-10-01 00:00:00 | BLOCK  |   315
 yroskov  | 2020-10-01 00:00:00 | UPDATE | 22897
 yroskov  | 2020-12-01 00:00:00 | BLOCK  |    39
 yroskov  | 2020-12-01 00:00:00 | UPDATE |   383
 yroskov  | 2021-01-01 00:00:00 | BLOCK  |    10
 yroskov  | 2021-01-01 00:00:00 | UPDATE |  1541
 yroskov  | 2021-02-01 00:00:00 | BLOCK  |     8
 yroskov  | 2021-02-01 00:00:00 | UPDATE |    61
 yroskov  | 2021-03-01 00:00:00 | BLOCK  |    39
 yroskov  | 2021-03-01 00:00:00 | UPDATE |  6658
 yroskov  | 2021-04-01 00:00:00 | BLOCK  |     7
 yroskov  | 2021-04-01 00:00:00 | UPDATE |   985
 yroskov  | 2021-05-01 00:00:00 | BLOCK  |   429
 yroskov  | 2021-05-01 00:00:00 | UPDATE |  5005
 yroskov  | 2021-06-01 00:00:00 | BLOCK  |  2247
 yroskov  | 2021-06-01 00:00:00 | UPDATE |   925
 yroskov  | 2021-07-01 00:00:00 | BLOCK  |     4
 yroskov  | 2021-07-01 00:00:00 | UPDATE |   147
 yroskov  | 2021-08-01 00:00:00 | BLOCK  |     9
 yroskov  | 2021-08-01 00:00:00 | UPDATE |  5802
 yroskov  | 2021-09-01 00:00:00 | BLOCK  |   407
 yroskov  | 2021-09-01 00:00:00 | UPDATE |   904
 yroskov  | 2021-10-01 00:00:00 | BLOCK  |  8366
 yroskov  | 2021-10-01 00:00:00 | UPDATE | 13371
 yroskov  | 2021-11-01 00:00:00 | BLOCK  |   122
 yroskov  | 2021-11-01 00:00:00 | UPDATE |   748
 yroskov  | 2021-12-01 00:00:00 | BLOCK  |     9
 yroskov  | 2021-12-01 00:00:00 | UPDATE |    77
 yroskov  | 2022-01-01 00:00:00 | BLOCK  |     2
 yroskov  | 2022-01-01 00:00:00 | UPDATE |    49
 yroskov  | 2022-02-01 00:00:00 | BLOCK  |     7
 yroskov  | 2022-02-01 00:00:00 | UPDATE |   384
```

**Comment by mdoering** [comment]
If I create an ambiguous synonym UPDATE decision in the duplicates tool status and parent are missing!!!
https://api.dev.checklistbank.org/dataset/2088/decision/5

```
"subject":{
"id":"214-215",
"name":"Alucita montana",
"authorship":"Cockerell, 1889",
"rank":"species"
}
```

**Comment by mdoering** [comment]
If I apple an IGNORE decision in the workbench to a synonym both status & parent are recorded:
https://api.dev.checklistbank.org/dataset/2088/decision/6

@thomasstjerne this seems to be a problem of the duplicate UI!

**Comment by mdoering** [comment]
@yroskov what shall we do with all the old decisions now?
I could revert them all to the original subject ID which we gladly recorded and then copy status & parent from the source if that record still exists? And if not we simply delete all broken decisions? That sounds much safer than applying wrong decisions.

**Comment by thomasstjerne** [comment]
> It seem though, that the parent is not given in the duplicates section, only in the workbench. Whether this is a bug or there is a reason, I don´t know.

Yes - the duplicate UI doesn´t record the parent

**Comment by mdoering** [comment]
@thomasstjerne can we also include the status please? For duplicates I suppose both parent and status are key

**Comment by mdoering** [comment]
Break down of decision with missing parent & status property and the number of those decisions that still matches based on their `original_subject_id`:

```
DATASET | MISSING | ORIG ID EXISTS
-- | -- | --
3 | 2258 | 0
1005 | 3 | 3
1008 | 159 | 157
1011 | 31 | 31
1015 | 3 | 3
1018 | 11 | 11
1021 | 72 | 72
1024 | 7 | 7
1039 | 1437 | 1222
1044 | 7 | 7
1046 | 1 | 1
1050 | 62 | 62
1051 | 215 | 215
1053 | 21 | 21
1057 | 1 | 1
1058 | 1 | 1
1059 | 1 | 1
1061 | 645 | 645
1062 | 5 | 5
1065 | 148 | 148
1068 | 1 | 1
1085 | 2 | 2
1089 | 7 | 7
1090 | 2 | 2
1094 | 3 | 3
1095 | 1 | 1
1101 | 3588 | 3588
1106 | 2 | 2
1107 | 4 | 4
1108 | 3 | 3
1109 | 1 | 1
1110 | 18 | 18
1113 | 1 | 1
1126 | 5 | 5
1129 | 1 | 1
1130 | 9 | 9
1131 | 3 | 3
1133 | 118 | 118
1134 | 50 | 50
1140 | 242 | 240
1141 | 970 | 891
1146 | 1 | 1
1158 | 5 | 5
1164 | 2 | 2
1166 | 658 | 644
1169 | 1 | 1
1170 | 4 | 3
1171 | 1 | 1
1173 | 177 | 177
1175 | 2 | 2
1176 | 11 | 11
1183 | 21 | 21
1189 | 2 | 0
1191 | 5 | 5
1193 | 7 | 7
1200 | 3 | 3
1203 | 40 | 35
1204 | 3 | 3
2073 | 39 | 39
2130 | 558 | 558
2141 | 42 | 42
2144 | 87 | 87
2147 | 32 | 0
2300 | 6 | 6
2302 | 11 | 11
2305 | 765 | 765
2317 | 1775 | 1775
```

**Comment by mdoering** [comment]
The only datasets which do not 100% match based on the original id are:

 - 2147 (0 out of 32)
 - 1203 (35 out of 40)
 - 1189 (0 out of 2)
 - 1166 (644 out of 658)
 - 1141 (891 out of 970)
 - 1039 (1222 of 1437)

**Comment by mdoering** [comment]
@yroskov I will link all decisions based on their original source id - the few ones above will have a few broken ones afterwards I would then delete???

**Comment by mdoering** [comment]
I am able to update 79.702 out of 98.129 decisions based on the original subject id - @yroskov shall I proceed?

**Comment by mdoering** [comment]
23 sources left with 1008 and 1140 and 1141 being the bulk:

```
 subject_dataset_key | count 
---------------------+-------
                   3 |     3
                1008 |  1223
                1027 |   819
                1044 |     2
                1090 |     1
                1107 |     1
                1126 |     1
                1127 |     1
                1128 |     1
                1130 |    56
                1131 |     1
                1140 |  3609
                1141 | 12150
                1157 |    32
                1175 |     5
                1189 |   448
                1191 |     8
                1193 |     9
                1196 |     2
                1200 |    42
                1202 |     3
                1203 |     2
                2144 |     8

```


```
select d.subject_dataset_key, count(*) from decision d left join name_usage u on u.dataset_key=d.subject_dataset_key and u.id=d.original_subject_id where d.dataset_key=3 and d.subject_parent is null and d.subject_status is null group by 1 order by 1;
```

**Comment by yroskov** [comment]
_Top seven:_

World Plants (1141) | 12150
World Ferns (1140) |  3609
ReptileDB (1008) |  1223
Scarabs (1027) |   819
3i Auchenorrhyncha (1189) |   448
WoRMS Mollusca (1130) |    56
WoRMS MilliBase (1200) |    42

**Comment by yroskov** [comment]
>shall I delete the other ones or leave them as they are?

@mdoering, please delete them. I'll re-do TASK decisions for 'top seven" GSDs.

**Comment by mdoering** [comment]
ok, gone. All decisions now have a parent and status!
