### ISSUE TITLE
environment of taxa in NameUsage.tsv

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#403]
Hi @yroskov and @gdower ! Greetings from Finland. I am back again!

According to COLDP documentation, the environment property is a comma separated list of environment enums.

However, the data in the environment column of NameUsage.tsv looks like this "FRESHWATER|TERRESTRIAL".
The enums are in upper case and separated by vertical bars ( | ).

**Comment by mdoering** [comment]
Indeed the exports wrongly used pipes. Fixed in code and will be deployed to prod later this week!

**Comment by yroskov** [comment]
Thank you, Ari, for spotting this! @aoern, welcome back to CoL
Thank you, Markus, for fixing it!
