### ISSUE TITLE
Update World Spider Catalog?

### ISSUE THREAD

**Issue by kcopas** [CatalogueOfLife/data#414]
Just to note, the World Spider Catalog has [just reached 50,000 species](https://wsc.nmbe.ch/statistics/), after adding several hundred new names each of the past 2-3 years.

Given that COL still uses the [2019 version of WSC](https://www.catalogueoflife.org/data/dataset/1029), perhaps it's a good time for a refresh?

**Comment by yroskov** [comment]
Forwarded to WSC

**Comment by mdoering** [comment]
@gdower @yroskov can't we use their [downloads or API](https://wsc.nmbe.ch/dataresources) to create an archive so we can have frequent automated updates at some point?

**Comment by mdoering** [comment]
Will that still be an ACEF file then?

**Comment by mdoering** [comment]
I have tried to use their API and it's pretty straight forward to generate a ColDP archive from that. Gonna test that in dev soon and then we can see if we can automate WSC every month?

**Comment by mdoering** [comment]
@yroskov there is a version on dev now to test: https://www.dev.checklistbank.org/dataset/123262/

**Comment by yroskov** [comment]
Daniel said clear: a new export will be available around June 15
