### ISSUE TITLE
LepIndex - Acraea terpsichore Linnaeus, 1758 should be Acraea terpsicore Linnaeus, 1758

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#420]
**Describe the problem**:

A GBIF user has given the following feedback
https://github.com/gbif/portal-feedback/issues/4037

**Acraea terpsichore Linnaeus, 1758**
https://www.gbif.org/species/5135694

should be 

**Acraea terpsicore Linnaeus, 1758**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/64MJT
https://www.catalogueoflife.org/data/dataset/1018

**Literature references**:
https://biodiversity.org.au/afd/taxa/Acraea_terpsicore

**Comment by dhobern** [comment]
What a mess ... I've fixed this in TaxonWorks. It should now show Acraea terpsicore (Linnaeus, 1758) as the species name, with Papilio terpsicore Linnaeus, 1758, Papilio terpsichore Linnaeus, 1758 and Acraea violae (Fabricius, 1775) as basionym, misspelling and subjective synonym respectively.
