### ISSUE TITLE
CoL Checklist 2022-04-26 not downloadable

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#430]
The Download page states that 2022-04-26 edition is ready for download. However, it is not:
{"code":404,"message":"ColDP archive for dataset 9817 not found"}

**Comment by mdoering** [comment]
For some reason no downloads have been created during the release. Odd.
I have manually triggered them now and will link them once ready

**Comment by aoern** [comment]
Thanks @mdoering ! It is there now.
