### ISSUE TITLE
Scientific names of nothospecies malformed

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#431]
Scientific names of nothospecies are malformed in NameUsage.tsv. There are two spaces between the multiplication sign and the specific name.
Example:
"Asplenium ×  mitsutae" instead of
"Asplenium × mitsutae".

**Comment by aoern** [comment]
Applies to World Ferns and World Plants taxa only.

**Comment by aoern** [comment]
Fix to the example:
Example:
"Asplenium ×  mitsutae" instead of
"Asplenium × mitsutae".

**Comment by yroskov** [comment]
@gdower, I think, it is on our side (extra space in names with hybrid mark WPlants & WFerns only)
