### ISSUE TITLE
Genera by name Group in Global Lepidoptera Index

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#447]
There are 76 genera by name Group in June 2022 edition of CoL. They appear in subfamilies Oecophorinae (72), Depressariinae (1) and Tortricinae (3).

Example (from Oecophorinae)
In CoL:
Name: Group lacteola (Turner, 1939)
Basionym: Pleurota lacteola Turner, 1939

In Natural History Museum pages:
Current Comb:  LACTEOLA GROUP lacteola Turner, 1939
Original Comb: PLEUROTA  Turner, 1939

Maybe 'LACTEOLA GROUP' should be parsed to something else than genus name 'Group'?

**Comment by aoern** [comment]
@yroskov, @mdoering
Any comments on this issue?

**Comment by yroskov** [comment]
Should be fixed in August

**Comment by aoern** [comment]
Yes, fixed in 2022 Annual.

**Comment by yroskov** [comment]
Thank you, Ari, for keeping eye on CoL releases and helping us to fix mistakes!
