### ISSUE TITLE
Duplicates in SF Psocodea?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#451]
@yroskov can you remind me why there are many of these duplicates in SF Psocodea?
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/327505/185148263-65056843-7e81-4669-acde-b59fa3a3e1fa.png">

There is a canonical species without authorship always given as a synonym for the same name with authorship?
Is that useful?

**Comment by yroskov** [comment]
@gdower, let's look during next round of SF updates what could be adjusted in the TW-CoLDP export to block "synonym" without authorstrings which are identical to parent accepted name.

**Comment by yroskov** [comment]
FIXED
