### ISSUE TITLE
Fix WoRMS Scleractinia metadata

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#454]
The World List of Scleractinia has the editors in wrong order in the source archive provided by WoRMS:
[World List of Scleractinia
](https://www.marinespecies.org/export/coldp/WoRMS_Scleractinia.zip)

Hoeksema should be the first editor according to https://www.marinespecies.org/scleractinia/
The editors are also listed there wrongly though and only the citation is correct.

Access to the URL is restricted, here is the metadata:

```
09:26:16 UTC colprodapps-vh ~/worms $ cat metadata.yml 
---
title: 'World List of Scleractinia'
alias: 'WoRMS Scleractinia'
description: 'This global marine species list is part of the World Register of Marine Species database, which aims to provide the most authoritative list of names of all marine species globally. Data have been contributed to the Catalogue of Life via the WoRMS, hosted by the Flanders Marine Institute (VLIZ).'
geographicScope: Global
taxonomicScope: 'hard corals'
temporalScope: 1758-2022
confidence: '4'
completeness: '95'
license: CC-BY
version: 'ver. (08/2022)'
released: '2022-08-01'
website: 'https://www.marinespecies.org/scleractinia'
logo: 'https://www.marinespecies.org/documents/WoRMS%20branding/WoRMS_logo_blue_negative.png'
citation: 'Hoeksema, B. W.; Cairns, S. (2022). World List of Scleractinia. Accessed at https://www.marinespecies.org/scleractinia on 2022-08-01'
code: zoological
gazetteer: mrgid
contact:
    - { givenName: Bert, familyName: Hoeksema, email: bert.hoeksema@naturalis.nl }
editors:
    - { givenName: Stephen, familyName: Cairns, email: cairnss@si.edu }
    - { givenName: Bert, familyName: Hoeksema, email: bert.hoeksema@naturalis.nl, orcid: 0000-0001-8259-3783 }
organisations:
    - { name: 'Smithsonian Institution; National Museum of Natural History Department of Invertebrate Zoology', country: USA }
    - { name: 'Naturalis Biodiversity Center Department of Marine Zoology', country: Netherlands }
    - { name: 'Vlaams Instituut voor de Zee', country: Belgium }

```

**Comment by mdoering** [comment]
please add also orcid 0000-0001-7209-9271 for stephen cairns

**Comment by mdoering** [comment]
Excellent! Will this also be true for the [other WoRMS datasets in ChecklistBank](https://www.checklistbank.org/dataset?limit=50&offset=0&origin=external&q=worms&reverse=false)?

**Comment by bart-v** [comment]
Yes, normally it should

**Comment by olafbanki** [comment]
Thanks Bart, I hope this resolves the authorship issue with WoRMS data sets in COL.

**Comment by olafbanki** [comment]
@bart-v just checking two datasets https://www.checklistbank.org/dataset/1193/about and https://www.checklistbank.org/dataset/1196/about The authorships look good, but I notice that the names of the persons are in the editor field and their organisations are in the contributor field. Just so you know, both person and ORCID and organisation can be put into the same field: https://www.checklistbank.org/catalogue/3/metadata

**Comment by DianRHR** [comment]
@bart-v  we checked all WoRMS datasets metadata at ChecklistBank vs. their citations at marinespecies.org and found mismatch  in 35 datasets. You can find them in the file attached, where differences are highlighted in bold letters. 

[Worms metadata check 20230510.csv](https://github.com/CatalogueOfLife/data/files/11445567/Worms.metadata.check.20230510.csv)

please let us know if you have any comments.

**Comment by bart-v** [comment]
Thanks, we'll look into this

**Comment by camiplata** [comment]
Hi Bart! Here are the details of the mismatch:

- Nemertea: [Worms citation](https://www.marinespecies.org/nemertea/) has the following authors Norenburg, J.; Gibson, R.; Herrera Bachiller, A.; Strand, M. , while in [CLB](https://www.checklistbank.org/dataset/1085/about) has one more author `Artois, T.`, Norenburg, J., Gibson, R., Herrera Bachiller, A., & Strand, M.

- Copepoda: [Worms citation](https://www.marinespecies.org/copepoda/) has the following authors Walter, T.C.; Boxshall, G.  , while in [CLB](https://www.checklistbank.org/dataset/1191/about) has many more Walter, T. C., Boxshall, `G., Bernot, J., Böttger-Schnack, R., Cornils, A., Costa Corgosinho, P. H., Defaye, D., Di Capua, I., Dippenaar, S., Figueroa, D., Gaviria-Melo, S., Gómez-Noguera, S. E., Ho, J.-s., Ivanenko, V. (., Kouwenberg, J., Piasecki, W., Suárez-Morales, E., Tang, D., & Uribe-Palomino, J.`

- Foraminifera: [Worms citation](https://www.marinespecies.org/foraminifera/) has the following authors Hayward, B.W.; Le Coze, F.; Vachard, D.; Gross, O. , while in [CLB](https://www.checklistbank.org/dataset/1157/about) has one more author`Consorti, L.`, Hayward, B. W., Le Coze, F., Vachard, D., & Gross, O. 

- Echinoidea: [Worms citation](https://www.marinespecies.org/echinoidea/) has the following authors Kroh, A.; Mooi, R. , while in [CLB](https://www.checklistbank.org/dataset/1106/about) has  many more**`Altenburger, K., Bandesha, F., Bronstein, O., Ducarme, F., Forstner, M., Grun, T. B., Krapf, A., Martínez-Melo, A., Miskelly, A., Mongiardino Koch, N., Steger, J., Ziegler, A., Sigda, L.`, Kroh, A., Mooi, R., `& Saucède, T.`

- MilliBase: [Worms citation](https://www.millibase.org/) has the following authors Sierwald, P.; Spelda, J. , while [CLB](https://www.checklistbank.org/dataset/1200/about) has many more **Sierwald, P., Spelda, J., `Barber, A., Decker, P., Akkari, N., Antić, D. Z., Barbosa, J. P., Bonato, L., Bouzan, R., Bueno-Villegas, J., Enghoff, H., Iniesta, L. F. M., Marek, P., Martínez-Muñoz, C. A., Reip, H., Shear, W., Short, M., Simmons, E., Stoev, P., et al.`

- polychaeta: [Worms citation](https://www.marinespecies.org/polychaeta/) has the following authors Read, G.; Fauchald, K. , while [CLB](https://www.checklistbank.org/dataset/1090/about) has many more   Read, G., Fauchald, K., `Carrera-Parra, L., Doner, S., Eibye-Jacobsen, D., Glasby, C., Glover, A. G., Harris, L., Paxton, H., Salazar-Vallejo, S., ten Hove, H., Zanol, J., Arvanitidis, C., Siciński, J., Londoño-Mesa, M., Reuscher, M., Fernández-Rodríguez, V., Nealova, L., & Wilson, R.`

- Ostracoda: [Worms citation](https://www.marinespecies.org/ostracoda/) has the following authors Brandão, S.N.; Antonietto, L.S; Nery, D.G.; Santos, S.G.; Karanovic, I. , while [CLB](https://www.marinespecies.org/ostracoda/) has many more  Brandão, S., Antonietto, L. S., Nery, D. G., Santos, S. G., Karanovic, I., `Camilo de Oliveira, J. P., Pereira, J. d. S., & Praxedes, R. A`.

- Amphipoda: [Worms citation](https://www.marinespecies.org/amphipoda/) has the following authors Horton, T.; Lowry, J.; De Broyer, C.; Bellan-Santini, D.; Copilaș-Ciocianu, D.; Corbari, L.; Costello, M.J.; Daneliya, M.; Dauvin, J.-C.; Fišer, C.; Gasca, R.; Grabowski, M.; Guerra-García, J.M.; Hendrycks, E.; Hughes, L.; Jaume, D.; Jazdzewski, K.; Kim, Y.-H.; King, R.; Krapp-Schickel, T.; LeCroy, S.; Lörz, A.-N.; Mamos, T.; Senna, A.R.; Serejo, C.; Souza-Filho, J.F.; Tandberg, A.H.; Thomas, J.D.; Thurston, M.; Vader, W.; Väinölä, R.; Vonk, R.; White, K.; Zeidler, W , while  in [CLB](https://www.checklistbank.org/dataset/1202/about) there is a difference on the  second and third authors order Horton, `T., De Broyer, C., Lowry, J.`, Bellan-Santini, D., and there are two more authors at the end `Desiderato, Andrea` and `Rewicz, Tomasz`.

- Gastrotricha: [Worms citation](https://www.marinespecies.org/imis.php?module=dataset&dasid=7820) has the following authors Todaro, A.; `d'Hondt, J-L.`  , while [CLB](https://www.checklistbank.org/dataset/1122/about) only has one Todaro, A.

- Placozoa: [Worms citation](https://www.marinespecies.org/placozoa/) has the following authors Schierwater, B.; Eitel, M.; DeSalle, R.  , while [CLB](https://www.checklistbank.org/dataset/1123/about) has some more Schierwater, `B., Osigus, H.-J.`, DeSalle, R., & `Eitel, M`. 

For the following two dataset CLB has ha detailed list of authors but WoRMS has a more general cite, to make such a change you need to tremove all authors and set the single editor with the name of the database for example"MolluscaBase"

- MolluscaBase:
   - Worms citation:     MolluscaBase eds. (2023). MolluscaBase. Accessed at https://www.molluscabase.org on 2023-05-11. doi:10.14284/448
  - CLB citation: Auffenberg, K., Bank, R., Bieler, R., Bouchet, P., Collins, K., Dekker, H., Faber, M., Garcia-Alvarez, O., Godoy, M. Á., Gofas, S., Herbert, D., Houart, R., Janssen, R., Kabat, A., Kantor, Y., Karapunar, B., Kovács, Z., Köhler, F., Marshall, B., et al. (2023). MolluscaBase (ver. (05/2023)). https://www.molluscabase.org/

- Nemys:
   - Worms citation:   Nemys eds. (2023). Nemys: World Database of Nematodes. Accessed at https://nemys.ugent.be on 2023-05-11. doi:10.14284/366
  - CLB citation: Bezerra, T. N., Eisendle, U., Hirsch, H., Hodda, M., Holovachov, O., Leduc, D., Mejía-Madrid, H. H., Mokievsky, V., Pedram, M., Peña Santiago, R., Pérez-García, J. A., Půža, V., Saraiva de Oliveira, J., Sharma, J., Smol, N., Tchesunov, A., Vanreusel, A., Venekey, V., Zhao, Z., et al. (2023). Nemys: World Database of Nematodes (ver. (05/2023)). https://nemys.ugent.be/


We couldn't check Brachiopoda as it is mising on the GSDs list https://www.marinespecies.org/subregisters.php

**Comment by camiplata** [comment]
Hi @bart-v ! Next COL checklist release will be on June 1st, please let us know if you need some extra hands to update the citation of the remaining datasets, so every ones authorship is better representen in the next release.

**Comment by bart-v** [comment]
Thanks, we'll manage

**Comment by camiplata** [comment]
Hi Bart, we made a full review of the citation of  the Jun version of all WORMS sources, most the differences we pointed out above have been addressed, however, we found some major an minor issues.

**Major**: significant differences on the editors information, those affecting the citation

- Cumacea: All metadata is empty on [Cumacea](https://www.checklistbank.org/dataset/1058/about137), so we were not available to check the information.
- Polychaeta: [Worms citation](https://www.marinespecies.org/polychaeta/) has the following authors Read, G.; Fauchald, K. , while [CLB](https://www.checklistbank.org/dataset/1090/about) now has a generic [citation on CLB](https://www.checklistbank.org/dataset/1090/about) without authors , World Polychaeta Database (ver. (06/2023)). (2023).. https://www.marinespecies.org/polychaeta
- Brachyura: [WoRMS link ](https://www.marinespecies.org/imis.php?module=dataset&dasid=4167)is currently broken, but looking at the [historic information from 2022](https://web.archive.org/web/20230117045610/https://www.marinespecies.org/imis.php?module=dataset&dasid=4167) the citation has two authors Ng, P.K.L.; Davie, P. , but in [CLB](https://www.checklistbank.org/dataset/1108/about) there is a generic citation without authors.
- Gastrotricha: [Worms citation](https://www.marinespecies.org/imis.php?module=dataset&dasid=7820) has the following authors Todaro, A.; d'Hondt, J-L. , while [CLB](https://www.checklistbank.org/dataset/1122/about) only has one Todaro, A.
- Brachiopoda: it is missing on the worms sub registers list https://www.marinespecies.org/subregisters.php, but we tracked the source to http://paleopolis.rediris.es/brachiopoda_database/index.html, where the citation Emig C. C., Bitner M. A. & Álvarez F., 2021. Brachiopoda database. Accessed at http://paleopolis.es/brachiopoda_database on dd-mm-2021, but in [CLB ](https://www.checklistbank.org/dataset/2299/about) has a generic citation without authors.
For this source we also noticed a difference on the license, with a CC-BY-NC-ND on the original database page vs. a CC-BY on CLB. Is Important to keep it under CC-BY on CLB to keep this GSD compatible with the entire COL list, but is just for yo to know about this difference in case it is something relevant to discuss in Worms.
- Corallimorpharia: [Worms citation](https://www.marinespecies.org/imis.php?module=dataset&dasid=7831) has the following authors Daly, M.; Fautin, D.G. while in [CLB](https://www.checklistbank.org/dataset/2299/about)  Fautin, D.G. is  missing.

**Minor:** slight differences between CLB and WoRMS in format of the citation, please just clarify if this is really a point to fix or not (to consider in future revisions).

Sources that have a range of dates on the original citation, but in CLB only one date can be added to the citation. In these cases we suggest to add this dates range on the abstract of each source:

- [WoRMS Turbellarians](https://www.checklistbank.org/dataset/1193/about)
- [WoRMS Isopoda](https://www.checklistbank.org/dataset/1094/about)
- [WoRMS Ctenophora](https://www.checklistbank.org/dataset/1180/about)

Sources with slight differences on the authors initials:

- [WoRMS Nemys](https://www.checklistbank.org/dataset/2302/about)
- [WoRMS Porifera](https://www.checklistbank.org/dataset/1044/about)
- [WoRMS Ostracoda](https://www.checklistbank.org/dataset/1175/about)
- [WoRMS Scleractinia](https://www.checklistbank.org/dataset/1196/about)
- [WoRMS Ascidiacea](https://www.checklistbank.org/dataset/1186/about)
- [WoRMS Scyphozoa](https://www.checklistbank.org/dataset/1188/about)
- [WoRMS Ctenophora](https://www.checklistbank.org/dataset/1180/about)
- [WoRMS Staurozoa](https://www.checklistbank.org/dataset/1184/about)
- [WoRMS Cubozoa](https://www.checklistbank.org/dataset/1181/about)
- [WoRMS Tantulocarida](https://www.checklistbank.org/dataset/1092/about)
- [WoRMS Thermosbaenacea](https://www.checklistbank.org/dataset/1093/about)
- [WoRMS Mystacocarida](https://www.checklistbank.org/dataset/1088/about)
- [WoRMS Brachypoda](https://www.checklistbank.org/dataset/1087/about)
- [WoRMS Bochusacea](https://www.checklistbank.org/dataset/1086/about)

Sources that in WoRMS have an specific URL and a DOI, but in CLB only have a DOI

[WoRMS Hydrozoa](https://www.checklistbank.org/dataset/1112/about)
[WoRMS Ophiuroidea](https://www.checklistbank.org/dataset/1059/about)
[WoRMS Pycnogonida](https://www.checklistbank.org/dataset/1183/about)

Sources that have a general URL to [https://www.marinespecies.org/](https://www.marinespecies.org/) but on the original citation they have a more specific one:

- [WoRMS Chaetognatha](https://www.checklistbank.org/dataset/1132/about)
- [WoRMS Nemertea](https://www.checklistbank.org/dataset/1085/about)
- [WoRMS Gnathostomulida](https://www.checklistbank.org/dataset/1125/about)
- [WoRMS Priapulida](https://www.checklistbank.org/dataset/1124/about)
- [WoRMS Copepoda](https://www.checklistbank.org/dataset/1191/about)
- [WoRMS Mollusca](https://www.checklistbank.org/dataset/1130/about)
- [WoRMS Foraminifera](https://www.checklistbank.org/dataset/1157/about)
- [WoRMS Nemys](https://www.checklistbank.org/dataset/2302/about)
- [WoRMS Oligochaeta](https://www.checklistbank.org/dataset/1099/about)
- [WoRMS Echinoidea](https://www.checklistbank.org/dataset/1106/about)
- [WoRMS Strepsiptera](https://www.checklistbank.org/dataset/1103/about)
- [WoRMS Merostomata](https://www.checklistbank.org/dataset/1152/about)
- [WoRMS MilliBase](https://www.checklistbank.org/dataset/1200/about)
- [WoRMS Bryozoa](https://www.checklistbank.org/dataset/1081/about)
- [WoRMS Brachyura](https://www.checklistbank.org/dataset/1108/about)
- [WoRMS Trematoda](https://www.checklistbank.org/dataset/1128/about)
- [WoRMS Amphipoda](https://www.checklistbank.org/dataset/1202/about)
- [WoRMS Octocorallia](https://www.checklistbank.org/dataset/1131/about)
- [WoRMS Monogenea](https://www.checklistbank.org/dataset/1126/about)
- [WoRMS Asteroidea](https://www.checklistbank.org/dataset/1095/about)
- [WoRMS Cestoda](https://www.checklistbank.org/dataset/1127/about)
- [WoRMS Holothuroidea](https://www.checklistbank.org/dataset/1107/about)
- [WoRMS Tanaidacea](https://www.checklistbank.org/dataset/1110/about)
- [WoRMS Crinoidea](https://www.checklistbank.org/dataset/2300/about)
- [WoRMS Gastrotricha](https://www.checklistbank.org/dataset/1122/about)
- [WoRMS Brachiopoda](https://www.checklistbank.org/dataset/2299/about)
- [WoRMS Myxozoa](https://www.checklistbank.org/dataset/1129/about)
- [WoRMS Polycystina](https://www.checklistbank.org/dataset/1109/about)
- [WoRMS Zoantharia](https://www.checklistbank.org/dataset/1197/about)
- [WoRMS Antipatharia](https://www.checklistbank.org/dataset/1194/about)
- [WoRMS Scyphozoa](https://www.checklistbank.org/dataset/1188/about)
- [WoRMS Thaliacea](https://www.checklistbank.org/dataset/1185/about)
- [WoRMS Ceriantharia](https://www.checklistbank.org/dataset/1179/about)
- [WoRMS Appendicularia](https://www.checklistbank.org/dataset/1178/about)
- [WoRMS Euphasiacea](https://www.checklistbank.org/dataset/2301/about)
- [WoRMS Cumacea](https://www.checklistbank.org/dataset/1058/about137)
- [WoRMS Staurozoa](https://www.checklistbank.org/dataset/1184/about)
- [WoRMS Cubozoa](https://www.checklistbank.org/dataset/1181/about)
- [WoRMS Leptostraca](https://www.checklistbank.org/dataset/1105/about)
- [WoRMS Tantulocarida](https://www.checklistbank.org/dataset/1092/about)
- [WoRMS Thermosbaenacea](https://www.checklistbank.org/dataset/1093/about)
- [WoRMS Loricifera](https://www.checklistbank.org/dataset/1182/about)
- [WoRMS Mystacocarida](https://www.checklistbank.org/dataset/1088/about)
- [WoRMS Brachypoda](https://www.checklistbank.org/dataset/1087/about)
- [WoRMS Bochusacea](https://www.checklistbank.org/dataset/1086/about)
- [WoRMS Xenoturbellida](https://www.checklistbank.org/dataset/1100/about)
- [WoRMS Actiniaria](https://www.checklistbank.org/dataset/1176/about)
- [WoRMS Kinorhyncha](https://www.checklistbank.org/dataset/1153/about)
- [WoRMS Rhombozoa](https://www.checklistbank.org/dataset/1150/about)
- [WoRMS Cephalochordata](https://www.checklistbank.org/dataset/1154/about)
- [WoRMS Orthonectida](https://www.checklistbank.org/dataset/1149/about)

**Comment by bart-v** [comment]
It's hard to rely on a comment like this if I just check one answer and it's wrong...
"Sources that have a general URL: MolluscaBase"

**Comment by DianRHR** [comment]
we didn't want to confuse you. In the specific case of Mollusca , here is the differerence, that we consider a minor issue, but still wanted to let you know: 
how it is in WoRMS: 
![image](https://github.com/CatalogueOfLife/data/assets/124217901/298d7b14-8b18-4f8f-a06f-89a30ff88651)

and how it is in CLB: 
![image](https://github.com/CatalogueOfLife/data/assets/124217901/cc82399f-8294-4d22-84ae-535625bf3dd1)

**Comment by DianRHR** [comment]
@bart-v  following your comments by e-mail I already updated citations in CLB for 5 datasets as follows: 

**Cumacea**: Metadata is visible now and NO CORRECTIONS were needed. 

**Polychaeta**: citation was corrected to Read, G., & Fauchald, K. (2023). World Polychaeta Database (ver. (06/2023)). https://www.marinespecies.org/polychaeta

**Brachyura**:  citation was corrected to Ng K.L., P., & Davie, P. (2023). World List of marine Brachyura (ver. (06/2023)). https://marinespecies.org/aphia.php?p=taxdetails&id=106673

**Gastrotricha**: citation was corrected to Todaro, A., & d’Hondt, J.-L. (2023). World Gastrotricha Database (ver. (06/2023)). https://marinespecies.org/aphia.php?p=taxdetails&id=2078

**Brachiopoda**: citation was corrected to WoRMS. (2023). World Brachiopoda Database (ver. (06/2023)). https://www.marinespecies.org/aphia.php?p=taxdetails&id=1803
Current license in CLB:  CC-BY 
Christian Emig and his e-mail were deleted from the "Contact" field in CLB. 

**Corallimorpharia**: citation was corrected to Daly, M., & Fautin, D. (2023). World List of Corallimorpharia (ver. (06/2023)). https://www.marinespecies.org/aphia.php?p=taxdetails&id=1362

Please remember that these changes are temporary  and only work for this month up to the next WoRMS update to ChecklistBank.

**Comment by bart-v** [comment]
One last update: since a few months we do have a WoRMS editor for *Brachiopoda*
So, the citation becomes: `Verhoeff, T. (2023). World Brachiopoda Database (...)`

**Comment by yroskov** [comment]
Many tanks! I'll do preview release with all these changes at the end Wd, 2023-06-14. It will available online at https://preview.catalogueoflife.org/. 

You all are very welcome to check this "proof".

**Comment by DianRHR** [comment]
Metadata for al WORMS datasets were updated and ready for the Annual release. 
However, detailed corrections will be done  by the WORMS team in each matadata file for future versions.
