### ISSUE TITLE
Systema Dipterorum - Lonchaea Fallén, 1820 (Tachinidae) should be moved to Lonchaea Fallén, 1820 (Lonchaeidae)

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#457]
**Describe the problem**:
A GBIF user has given the following feedback  
https://github.com/gbif/portal-feedback/issues/4200

regarding
https://www.gbif.org/species/1529245

The user claims that 

family: **Tachinidae**
genus: Lonchaea Fallén, 1820
https://www.catalogueoflife.org/data/taxon/99DFT

should be move to 

family: **Lonchaeidae** 
genus: Lonchaea Fallén, 1820
https://www.catalogueoflife.org/data/taxon/9CJN5

**Link to effected CoL webpages**:
http://www.catalogueoflife.org/col/...

**Comment by yroskov** [comment]
Forwarded to Systema Dipterorum editors

**Comment by yroskov** [comment]
Only one species Lonchaea discrepans placed in the family Tachinidae in CoL.

In the export file, ver. 3.8_2022-05-20, table species
it is in the family **Lonchaeidae**

Walker | 1 | 0.1971 | 1971 | Walker 1861: 322 | 990 | 1861Walker | 39408 | NT | NT | 1 |   |   | discrepansWalker1861 |   | 43992 | Neal Evenhuis | LonchaeadisWalker | Lon1861discrepaWalker | Lonchaeadiscrepa1861 | LonchaeadiscrepaWalk | 1 |   |   | Loncdiscrepa | Lonchaeidae | Lonchaea discrepans   Walker, 1861: 322. TL: Mexico (    BMNH). | Lonchaea discrepans   Walker, 1861: 322. TL: Mexico (  BMNH).   Mexico | Lonchaea discrepans.   (NT: NT) Mexico | 11610 | 20 | kiefferiana | discrepans Walker   1861, Lonchaea (Lonchaea discrepans) |   | Lonchaea discrepans | Lonchaea discrepans   Walker, 1861: 322 | Lonchaea discrepans   Walker |   |   | Lonchaeadiscrepans | 1 | Lonchaea |   |   |   |   | 322 | Lonchaea | Lonchaea |   | Mexico | (NT: NT) Mexico | (NT: NT) Mexico | 1 | 208086 | 1 | Neal Evenhuis | 5/11/2022 |   |   | discrepans. (NT: NT)   Mexico |   | discrepans |   | 212121 | 10 | (Available, Valid)   Current Valid Name |   |   |   | 0 |   | BMNH |   | TL: Mexico (  BMNH) | Mexico |   | 1 |   | 35E7946B-43E1-4A10-84C0-C955142D22B1 | Lonchaea discrepans | Lonchaea discrepans   Walker | Lonchaea discrepans | Walker | discrepans | discrepans. (NT: NT)   Mexico | 1 | Lonchaea | LonchaeadiscrepansWalke | Lonchaeadiscrepans | 99 | 1861 | 1861:   322
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

In CLB:
![image](https://user-images.githubusercontent.com/28574252/187967104-2ec69412-feaf-4761-8136-ab4c38165dcf.png)

**Comment by camiplata** [comment]
This issue has been adressed
<img width="643" alt="Captura de pantalla 2024-06-13 a la(s) 10 58 01 a m" src="https://github.com/CatalogueOfLife/data/assets/5700527/865a168a-61b7-4d7b-9720-c2f809cffd70">
