### ISSUE TITLE
COL Checklist generates ghost genera for incertae sedis species

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/data#469]
The Gelechiidae dataset includes a number of species with binomials that have not been revised to reflect modern taxonomy. These are shown in the dataset as species with the family as their immediate parent, e.g. 'Barea ectadia':

https://www.checklistbank.org/dataset/2362/taxon/11010

When this species is imported into the COL checklist, an erroneous genus Barea is created and shown as accepted. The accepted genus of this name is in a different family. COL ends up with two accepted genera with the same name.

https://www.catalogueoflife.org/data/taxon/383B - ghost genus in error in Gelechiidae
https://www.catalogueoflife.org/data/taxon/923LB - good genus in Oecophoridae

Either COL needs to change its processing so this genus doees not get created or else I need a way properly to mark these species so that they are genuinely treated as incertae sedis.

**Comment by yroskov** [comment]
@mdoering, it's for you: "COL needs to change its processing [species names without genus] so this genus does not get created [by the checklistbank]". Indeed, CLB should not create a genus in the classification, if it's not provided by GSD. 

However, as for me, the species name does not exist in the taxonomic checklist without genus (art. 5.1 ICZN). As a best practice, the GSD author should not supply incertae sedis species names without genus in the CoL. Species with unresolved taxonomic position should be kept out of the final product, or go in in the checklist under original genus with comments on  doubtful  taxonomic position in the comment field.

**Comment by mdoering** [comment]
The species needs to have a provisional status to be kept without a genus during a sync. 

This issue comes up rather frequently and we need to communicate how to express uncertain placed species. We have discussed this before. Cant find the issue now, but here is the recommendation: https://github.com/CatalogueOfLife/coldp/blob/master/README.md#species-with-an-uncertain-genus

**Comment by yroskov** [comment]
Species without genus is a nonsense. I hope, taxonomists are able to understand this as outcome of their unfinished work. Above proposal will cause a lot of confusions for CoL users outside taxonomic profession.

**Comment by dhobern** [comment]
Thanks @mdoering - I've changed them all to provisional = true and reimported into CLB.

**Comment by mdoering** [comment]
@yroskov you should also be able to change the status with decisions to avoid redundant genera

**Comment by mdoering** [comment]
> Species without genus is a nonsense. I hope, taxonomists are able to understand this as a result of their unfinished work. Above proposal will cause a lot of confusions for CoL users outside taxonomic profession.

How else would you want to treat this problem? 

We have to live with the fact that there are unresolved species placements and missing names (in botany you publish new combinations). And the discussion so far ended with the provisionally accepted status being well suited to indicate just that to users and to the assembly system. Happy to hear alternative ideas how to address this.

**Comment by mdoering** [comment]
Here is our original discussion that led to the recommendation. 

https://github.com/CatalogueOfLife/coldp/issues/45

I think it is important we agree on one way to do it and try our best to steer the COL checklist towards a consistent state.
