### ISSUE TITLE
WoRMS Asteroidea - Goniaster quinqueloba is a missing syn of Asterias quinqueloba Goldfuss, 1831

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#470]
**Describe the problem**:

A GBIF user has given the following feedback 
https://github.com/gbif/portal-feedback/issues/4308

**Goniaster quinqueloba** is a missing syn of **Asterias quinqueloba Goldfuss, 1831**.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/846SZ
https://www.catalogueoflife.org/data/dataset/1095

**Literature references**:
https://www.google.de/books/edition/Repertorium_zu_Goldfuss_Petrefakten_Deut/9107AAAAcAAJ?hl=de&gbpv=1&dq=%22Goniaster+quinqueloba%22&pg=PA36&printsec=frontcover

https://books.google.de/books?id=sXIrAAAAYAAJ&pg=RA3-PA314&lpg=RA3-PA314&dq=%22Goniaster+quinqueloba%22+asterias+quinqueloba&source=bl&ots=owhxdb3UQ4&sig=ACfU3U2b7rxVCOw1aTcGkMBxJ_ljq4evLQ&hl=de&sa=X&ved=2ahUKEwiF4aj8q7D6AhWP7KQKHa6HAIgQ6AF6BAgMEAM#v=onepage&q=%22Goniaster%20quinqueloba%22%20asterias%20quinqueloba&f=false

**Comment by yroskov** [comment]
@bart-v, it may have an interest for WoRMS authors

**Comment by bart-v** [comment]
Added in WoRMS
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1605082
Issue can be closed
