### ISSUE TITLE
Global Lepidoptera Index - Ptychopoda nitidata is missing syn of Idaea nitidata (Herrich-Schäffer, 1861)

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#473]
**Describe the problem**:

A GBIF user has given the following feedback
https://github.com/gbif/portal-feedback/issues/4248

**Ptychopoda nitidata** is missing syn of **Idaea nitidata (Herrich-Schäffer, 1861)**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3PBTP
https://www.catalogueoflife.org/data/dataset/55434

**Literature references**:
https://www.zobodat.at/pdf/MittNatVerSt_99_0143-0180.pdf

**Comment by dhobern** [comment]
Thanks - I can fix these over the next few days in the Global Lepidoptera Index, although the geometrid (like this) and pyraloid ones will be better handled by datasets we're currently exploring adding.

**Comment by dhobern** [comment]
Added to Global Lepidoptera Index - should be in next release of COL

**Comment by yroskov** [comment]
@dhobern, let me know, please, when you upload a new Global Lepidoptera Index version in CLB. We'll need to sync it before CoL release. The current version of GLI "imported Oct 4, 2022 10:44 PM".

**Comment by mdoering** [comment]
@yroskov you can always see the sources that need to be synced marked in the [sourcmetrics](https://www.checklistbank.org/catalogue/3/sourcemetrics) with an asterisk! The number in brackets is the latest import attempt, the other one the attempt last synced.

**Comment by yroskov** [comment]
I need to know here when a version with corrections logged in GitHub on Oct 12 will be ready in CLB.

**Comment by dhobern** [comment]
The only delay was because I have to export from TW before I can upload to CLB. This export completed overnight and it is now uploading to CLB. The corrections were not logged on Oct 12. They were loged on Oct 18 (yesterday).

**Comment by mdoering** [comment]
Curious, is there no version and issued date in the generated TW archive?

**Comment by dhobern** [comment]
No - there is no metadata at all. I always forget I need also to change the date on the dataset. Done now.

**Comment by mdoering** [comment]
@mjy @gdower @jlpereira could TW exports include at least some basic metadata like the title, date issued, a version and the people who created it?

**Comment by dhobern** [comment]
Thanks, @mdoering . I would just note that there is a lot of other metadata I currently have to craft outside TW (past editors, dataset description, etc.). If TW includes only simple metadata and CLB imports the dataset metadata from the COLDP package, would I have to fix it all whenever the dataset is refreshed?

**Comment by mdoering** [comment]
There is a setting in CLB that allows to merge metadata on imports. That way only fields that are included in the archive will overwrite what was there, but any others remain. So if TW started out with just the issued date that would be kept up to date and anything else could be manage manually

**Comment by dhobern** [comment]
Thanks - all good then.
