### ISSUE TITLE
Global Lepidoptera Index - Ptychopoda lutulentaria is missing syn of Idaea lutulentaria (Staudinger, 1892)

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#474]
**Describe the problem**:

A GBIF user has given the following feedback
https://github.com/gbif/portal-feedback/issues/4247

**Ptychopoda lutulentaria** is missing syn of **Idaea lutulentaria (Staudinger, 1892)**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3PBRQ
https://www.catalogueoflife.org/data/dataset/55434

**Literature references**:
https://www.google.com/search?q=%22Ptychopoda+lutulentaria%22&client=firefox-b-d&source=lnms&tbm=bks&sa=X&ved=2ahUKEwiCyuKqxY36AhVFPuwKHQuqChkQ_AUoAXoECAEQCw&biw=1600&bih=762&dpr=1.2

**Comment by yroskov** [comment]
@dhobern, it's for you

**Comment by dhobern** [comment]
Thanks - I can fix these over the next few days in the Global Lepidoptera Index, although the geometrid (like this) and pyraloid ones will be better handled by datasets we're currently exploring adding.

**Comment by dhobern** [comment]
Added to Global Lepidoptera Index - should be in next release of COL
