### ISSUE TITLE
Global Lepidoptera Index - Ptychopoda exilaria is missing syn of Idaea exilaria (Guenee, 1858)

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#476]
**Describe the problem**:

A GBIF user has given the following feedback
https://github.com/gbif/portal-feedback/issues/4245

**Ptychopoda exilaria** is missing syn of **Idaea exilaria (Guenee, 1858)**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/6MTHJ
https://www.catalogueoflife.org/data/dataset/55434

**Literature references**:
https://www.google.de/search?q=%22Ptychopoda+exilaria%22&biw=1120&bih=533&tbm=bks&ei=uzweY4eUB43dkwWD6qLICQ&ved=0ahUKEwjH3biRwo36AhWN7qQKHQO1CJkQ4dUDCAg&uact=5&oq=%22Ptychopoda+exilaria%22&gs_lcp=Cg1nd3Mtd2l6LWJvb2tzEANQAFj1f2CWhAFoAHAAeACAAX2IAcECkgEDMi4xmAEAoAECoAEBwAEB&sclient=gws-wiz-books

**Comment by dhobern** [comment]
Thanks - I can fix these over the next few days in the Global Lepidoptera Index, although the geometrid (like this) and pyraloid ones will be better handled by datasets we're currently exploring adding.
