### ISSUE TITLE
Global Lepidoptera Index - Ptychopoda fathmaria Oberthür, 1876 is missing syn of Idaea fathmaria Oberthür, 1876

### ISSUE THREAD

**Issue by jhnwllr** [CatalogueOfLife/data#477]
**Describe the problem**:

A GBIF user has given the following feedback
https://github.com/gbif/portal-feedback/issues/4244

**Ptychopoda fathmaria Oberthür, 1876** is missing syn of **Idaea fathmaria Oberthür, 1876**

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3PBMH
https://www.catalogueoflife.org/data/dataset/55434

**Literature references**:
https://www.google.de/search?q=%22Ptychopoda+fathmaria%22&source=lnms&tbm=bks&sa=X&ved=2ahUKEwib5MSmwY36AhXS66QKHcR-A7gQ_AUoAXoECAEQCw&biw=1120&bih=533&dpr=1.71

**Comment by yroskov** [comment]
@dhobern, it's for your attention

**Comment by dhobern** [comment]
Thanks - I can fix these over the next few days in the Global Lepidoptera Index, although the geometrid (like this) and pyraloid ones will be better handled by datasets we're currently exploring adding.

**Comment by dhobern** [comment]
Added to Global Lepidoptera Index - should be in next release of COL
