### ISSUE TITLE
Include World Wide Wattles again

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#485]
WWW was never supposed to be removed. The editors of the WCVP Fabaceae list have expressed concern that their list is not yet ready to replace WWW for the genera Acacia, Acaciella, Senegalia, Parasenegalia, Mariosousa, Pseudosenegalia and Vachellia.

Replace those with the WWW version until WWW gets included in WCVP Fabaceae properly.

**Comment by olafbanki** [comment]
@mdoering I have assigned this to @dhobern as this concerns the COL Taxonomy Group.

**Comment by dhobern** [comment]
I have a new and more complete version of WWW - it formerly excluded synonyms. I plan to try to format it as COLDP this weekend. If that proves difficult, we can roll back to the old WWW. Otherwise, it is the one we should use.

**Comment by mdoering** [comment]
Great! Please don't create a new dataset but reuse the one [we have](https://www.checklistbank.org/dataset/1162) to keep metrics and history. For testing you can create a dataset on dev of course. The old one is always available as the AC19 ACEF export we did: https://raw.githubusercontent.com/Sp2000/colplus-repo/master/ACEF/162.tar.gz

**Comment by dhobern** [comment]
I think I'll need to be added to the editors for WWW or something so I can
upload the new version. How does that happen?

-- 

*Donald Hobern* / ***@***.*** / +61 420511471
Araba Bioscan Project <https://stangeia.hobern.net/araba-bioscan-project/>
/ Pterophoroidea <https://pterophoroidea.hobern.net/> / Alucitoidea
<https://alucitoidea.hobern.net/> / BOLD Australia
<https://bold-au.hobern.net/>
ORCID: 0000-0001-6492-4016 <https://orcid.org/0000-0001-6492-4016> / Blog
<https://stangeia.hobern.net/> / iNaturalist
<https://inaturalist.ala.org.au/people/dhobern> / Flickr
<https://www.flickr.com/photos/dhobern/>/ GitHub
<https://github.com/dhobern> / Twitter <https://twitter.com/dhobern> /
Mastodon ***@***.***>
