### ISSUE TITLE
Where have all the StaphBase beatles gone?

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#488]
In the newest November 2022 release, all the StaphBase taxa except for the superfamilies Histeroidea, Hydrophiloidea and Staphylinoidea are missing.
Is there a particular reason for this?

**Comment by yroskov** [comment]
Thank you Ari, we know this. The only reason is an unexpected disaster with WCVP (https://github.com/CatalogueOfLife/testing/issues/211#issuecomment-1322457897). CLB software does not allow to roll back data. An interim CoL version of 2022-11-14 was deployed as monthly edition. All with StaphBase are already fine here (2022-11-29): https://www.checklistbank.org/dataset/9848/classification
