### ISSUE TITLE
name incorrectly linked to WoRMS (taxon is out of scope)

### ISSUE THREAD

**Issue by sharifX** [CatalogueOfLife/data#499]
_Adalia bipunctata_ (two-spotted ladybug) is listed in WoRMS.

https://www.checklistbank.org/dataset/2011/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A989612

https://www.marinespecies.org/aphia.php?p=taxdetails&id=989612 this gives an error "Oops! This taxon is out of scope!"

The GBIF page also links to the above link: https://www.gbif.org/species/1043097

**Comment by mdoering** [comment]
WoRMS explicitly publishes this link as you can see here :
> dcterms:references https://www.marinespecies.org/aphia.php?p=taxdetails&id=989612
https://www.checklistbank.org/dataset/2011/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A989612

@bart-v do you know those links respond like that?

**Comment by bart-v** [comment]
Yes, that is normal and expected behavior, as this is not a marine species.
To view the page, you can just un-select "marine only" on the top right of the WoRMS page.
In the future, we will provide links that point to a page that is immediately visible.

**Comment by bart-v** [comment]
So you can close this issue

**Comment by bart-v** [comment]
No, it still comes from WoRMS.
This is just a representation issue.

Of course, if a more authoritative source is available (i.e. not a marine-focused GSD), it could get a higher priority in CheckListBank
