### ISSUE TITLE
Col Checklist downloading fails

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#509]
Downloading the Col Checklist version 2023-02-07 (COLDP format) fails by:

{"code":404,"message":"ColDP archive for dataset 9880 not found"}

**Comment by mdoering** [comment]
the download failed during the release - I am recreating it as I type

**Comment by mdoering** [comment]
copied to downloads

**Comment by mdoering** [comment]
[83f88f40-e54a-4c01-b437-b34f9e211d99https://download.checklistbank.org/col/latest_coldp.zip](https://download.checklistbank.org/col/latest_coldp.zip)
