### ISSUE TITLE
Systema Dipterorum - misspelled name - Compsomyiops calllipes Bigot, 1877

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#513]
**Describe the problem**:
This issue was originally reported to the GBIF Helpdesk.

This name seems misspelled: _Compsomyiops ca**lll**ipes Bigot_, 1877
The original name was _Somomya ca**ll**ipes Bigot_, 1877.
In other’s instituionnals web site we can see the orthograph : _Compsomyiops ca**ll**ipes_

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/XHYL

**Literature references**:
https://eol.org/pages/59143559
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=142898
https://calphotos.berkeley.edu/cgi/img_query?seq_num=305596&one=T

**Comment by yroskov** [comment]
Editor of Systema Dipterorum informed. Temporary correction applied in the checklistbank. It will be available in CoL of March.
