### ISSUE TITLE
NamePhrase usage in StaphBase

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#522]
All the nominotypical subspecies taxa in StaphBase have "s.str." as their NamePhrase value (about 1040 taxa). For example:
Spelaeabraeus agazzii agazzii (NamePhrase: s.str)
This makes no sense.  Of course, every nominotypical subspecies is a kind of 'species in strict sense'.
Some applications (for example the Taxon Page of CoL) display the NamePhrase as part of taxon name like this:
Spelaeabraeus agazzii agazzii .s.str.
Looks pretty strange to me!

**Comment by yroskov** [comment]
Thank you, Ari. We'll fix it (hope, in April edition)

**Comment by gdower** [comment]
Thanks, Ari. It'll be fixed in the next release.
