### ISSUE TITLE
NamePhrase usage in Archaea and Bacteria

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#525]
There are >600 taxa in Archaea and Bacteria (ITIS) where 'emend.' phrase is duplicated. It is both as the NamePhrase property and as part of the ScientificName property.
In search and browse pages and elsewhere, this results in taxon names with duplicated emend. phrase such as:

Acidianus Segerer et al., 1986 emend. Plumb et al., 2007 emend. Plumb & al. , 2007
and
Halogranum Cui et al., 2010 emend. Cui et al., 2011 emend. Cui & al. , 2011

**Comment by aoern** [comment]
Correction: The phrase is part of Authorship property (not ScientificName).

Additional info:
It seems that in all cases NamePhrase contains "& al." but Authorship "et al.".

**Comment by aoern** [comment]
The problem is not restricted to ITIS data (Archaea and Bacteria).

In WoRMS Foraminifera there are 9 taxa that suffer from exactly same symptoms. Example:
Trocholinidae	
Authorship: Kristan-Tollmann, 1963, emend. Rigaud et al., 2013
NamePhrase: 	emend. Rigaud & al. , 2013

**Comment by aoern** [comment]
@yroskov

**Comment by yroskov** [comment]
Indeed,

In CoL: Acidianus Segerer et al., 1986 **emend. Plumb et al., 2007 emend. Plumb & al. , 2007**
In ITIS: Acidianus  Segerer et al., 1986 **emend. Plumb et al., 2007**

Verbatim in CLB (with error 404):
![image](https://user-images.githubusercontent.com/28574252/235218999-134869d6-6a7e-4e7d-b961-96eadc8d7b59.png)

@mdoering, could you please have a look if it is happened on your side.

**Comment by mdoering** [comment]
Fixed some time ago:
https://www.checklistbank.org/dataset/300004/taxon/MWB
https://www.checklistbank.org/dataset/2144/taxon/951481

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/419f0375-682e-4a84-8a22-cafd43945f9c">

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/9352d8a1-4880-4b29-bd15-ee8f495897c6">
