### ISSUE TITLE
Grindelia fraxinipratensis - wrong authorship from World Plants checklist

### ISSUE THREAD

**Issue by CecSve** [CatalogueOfLife/data#526]
**Describe the problem**:
A GBIF user has made us aware of a wrong authorship of _Grindelia fraxinipratensis_ Reveal & Barneby in the World Plants checklist according to the source used by World Plants. The correct authorship of the taxon should be _Grindelia fraxinipratensis_ Reveal & Beatley. 

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/6KT3N 

**Literature references**:
Please see attached file for source document of the taxon name
[Reveal_Beatley-1971_A New Penstemon (Scrophulariaceae) and Grindelia (Asteraceae) from Southern Nye County, NV.pdf](https://github.com/CatalogueOfLife/data/files/11261134/Reveal_Beatley-1971_A.New.Penstemon.Scrophulariaceae.and.Grindelia.Asteraceae.from.Southern.Nye.County.NV.pdf)

**Comment by yroskov** [comment]
Forwarded to the author of the World Plants.
