### ISSUE TITLE
Status unresolved

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#527]
There is a species named "Status unresolved" in genus Arabidopsis in family Brassicaceae !?!

**Comment by yroskov** [comment]
Probably, it is something which is not under our control (CLB software? external resource?). 

I do not see "status unresolved" on genus page via public interface.

@mdoering, could you please have a look on this issue?

**Comment by mdoering** [comment]
https://www.catalogueoflife.org/data/taxon/8H56S
https://www.checklistbank.org/dataset/9887/taxon/8H56S

**Comment by mdoering** [comment]
As usual @aoern is right and it is also in the source, no software artifact: https://www.checklistbank.org/dataset/2305/taxon/~Y

**Comment by yroskov** [comment]
FIXED 2023-06-12. Species with the name "Status unresolved" in Brassicaceae deleted in CoL-Draft assembly.
