### ISSUE TITLE
World Plants - possible incorrect synonyms - Trichocereus scopulicola and Echinopsis lageniformis 

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#532]
**Describe the problem**:
Issue originally reported on the GBIF Helpdesk:
> Trichocereus scopulicola is NO synonym of Echinopis lageniformis
> Tr. scopulicola = Echinopsis scopulicola
> Tr. bridgesii = Echinopsis lageniformis 
> Both are quite different cacti.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/38KFS

**Literature references**:
No reference provided.

**Comment by camiplata** [comment]
fixed
https://www.catalogueoflife.org/data/taxon/38KKM
https://www.catalogueoflife.org/data/taxon/38KFS
