### ISSUE TITLE
Excessive 'namePublishedIn'

### ISSUE THREAD

**Issue by jar398** [CatalogueOfLife/data#534]
According to Darwin Core, namePublishedIn ought to be pretty concise:

> Definition | A reference for the publication in which the scientificName was  originally established under the rules of the associated  nomenclaturalCode.

However, in the January 2023 edition of CoL, we have several rows (such as 96N8, Achelous gibbesii (Stimpson, 1859)) listing vast numbers of references, blowing past the default size limit for a CSV field in Python (which is 131072 bytes).  These cannot all be references to the original publication.

Not sure about the fix - maybe alert the source checklist provider; or maybe truncate; or both.

My apologies if I've posted to the wrong place; I have not reported an issue in this project before.

**Comment by jar398** [comment]
Yes, sorry.  I did a darwin core archive download of the whole taxonomy from the user interface, https://www.checklistbank.org/dataset/9859/download
In case it helps here are all the records I found with a field longer than 131072 bytes:

```
# Really long row: 2797171 96N8
# Really long row: 2797175 96MZ
# Really long row: 2797178 96N5
# Really long row: 2797179 96N2
# Really long row: 2797180 96NJ
# Really long row: 2797183 96NH
# Really long row: 2797186 96NL
```

**Comment by yroskov** [comment]
@bart-v, could unparsed references be sorted on your side?

Example https://preview.catalogueoflife.org/data/taxon/96N8

**Comment by mdoering** [comment]
Achelous gibbesii (Stimpson, 1859) in [COL](https://preview.catalogueoflife.org/data/taxon/96N8) comes from this reference record: 

The [verbatim name record](https://www.checklistbank.org/dataset/1108/verbatim/28707) links to this [reference record](https://www.checklistbank.org/dataset/1108/verbatim/28707) which does NOT have the excessive citation string.

**Comment by mdoering** [comment]
The bad reference record is here in the API: https://api.checklistbank.org/dataset/3LR/reference/069e92c9-83df-4617-b138-ea8b978784c9

**Comment by bart-v** [comment]
You keep on repeating the same issue over and over :)
This is exactly the same as https://github.com/CatalogueOfLife/testing/issues/39#issuecomment-1267447568

The first reference for this taxon page  https://preview.catalogueoflife.org/data/taxon/96N8 *had* an unclosed double quote, that causes all/many following references to be appended incorrectly.

The unclosed double quote was removed in Oct 2022

As said before, we don't use quotes to enclose fields.

**Comment by yroskov** [comment]
Our apology, Bart. Indeed, it is known and discussed problem. Let see, what will be happened with new update in next few hours.

**Comment by yroskov** [comment]
New WoRMS Brachyura of 2023-06-01 was successfully imported in the CLB. Reference is OK now: https://www.checklistbank.org/dataset/1108/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A557883

Many thanks!
