### ISSUE TITLE
Chresonyms in Cerambycidae TITAN database?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#537]
For example _Mallodon spinibarbe_ (Linné, 1758): https://www.checklistbank.org/dataset/9893/taxon/3XP8W
Rather unlikely that there have been so many attempts to publish this name.

Duplicates with at least 3 synonyms:
https://www.checklistbank.org/catalogue/3/duplicates?acceptedDifferent=false&authorshipDifferent=true&catalogueKey=3&category=binomial&limit=100&minSize=3&mode=STRICT&status=synonym

**Comment by yroskov** [comment]
There are lot of unresolved chresonyms in TITAN-2015@CoL. We plans to crawl TITAN website & clean up chresonyms in 2023-24 year cycle.
