### ISSUE TITLE
Papilio cingulus Stoll, 1791 accepted twice

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#551]
@dhobern the species is accepted twice as different homotypic names:
https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&q=Papilio%20cingulus&sortBy=taxonomic&type=EXACT

**Comment by dhobern** [comment]
Fixed in GLI TaxonWorks - I'll upload to CLB again tonight

**Comment by dhobern** [comment]
This is now the only instance of this name in GLI:

https://www.checklistbank.org/dataset/55434/taxon/513358
