### ISSUE TITLE
Tortricidae lost its parents

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#553]
**Describe the problem**:
...

**Link to effected CoL webpages**:
http://www.catalogueoflife.org/col/...

**Literature references**:
...

**Comment by aoern** [comment]
Tortricidae is classified as a direct child of Insecta.

**Comment by yroskov** [comment]
Thanks, Ari!

https://github.com/CatalogueOfLife/testing/issues/221#issuecomment-1645558750

**Comment by yroskov** [comment]
Fixed now. Results will be in August release.
