### ISSUE TITLE
Why does TITAN looks "empty" on COL webpage

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#555]
Why does TITAN looks "empty" on COL webpage: https://www.catalogueoflife.org/data/dataset/1032

<img width="969" alt="Captura de pantalla 2023-08-11 a la(s) 7 13 33 p m" src="https://github.com/CatalogueOfLife/data/assets/5700527/202f04c8-b4ea-4ac2-af19-808fae529dfc">

Browsing COL subfamilies are missing, is this the desired behavior?
<img width="414" alt="Captura de pantalla 2023-08-11 a la(s) 7 14 51 p m" src="https://github.com/CatalogueOfLife/data/assets/5700527/4dda19af-d5e5-4cc4-93b1-f5809b13dd17">

Everything looks ok on checklistbank: https://www.checklistbank.org/dataset/1032/classification

**Comment by mdoering** [comment]
If I look at the single TITAN sector created very recently on August  8th, it was never synced: https://www.checklistbank.org/catalogue/3/sector/sync?sectorKey=1996

It is also not present in the AC23 release: 
https://www.checklistbank.org/dataset/9910/source/1032

... where there is a broken subject in a different sector 676
https://www.checklistbank.org/catalogue/9910/sector?limit=100&offset=0&subjectDatasetKey=1032

@yroskov an oversight? Why was the old sector deleted and not fixed?

**Comment by gdower** [comment]
Potentially there's a backend bug with the released source metrics getting changed? The latest release should still have the old version TITAN included (and same for AC 2022).

https://api.checklistbank.org/dataset/3LR/source/1032/metrics
https://api.checklistbank.org/dataset/COL2022/source/1032/metrics

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/backend/issues/1243

**Comment by camiplata** [comment]
fixed long time ago
