### ISSUE TITLE
Global Lepidoptera Index – possibly misspelling of species - Paradohertya triphasia

### ISSUE THREAD

**Issue by ktotsum** [CatalogueOfLife/data#556]
**Describe the problem**:
https://github.com/gbif/portal-feedback/issues/4891
Paradohertya triphasia Bethune-Baker, 1904 should be Paradohertya trifascia according to the original description.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/6TMYG

**Literature references**:
[Novitates Zoologicae 11. 1904](https://archive.org/stream/novitateszoologi11lond#page/421/mode/1up)

**Comment by yroskov** [comment]
For attention of @dhobern

**Comment by dhobern** [comment]
Fixed in TaxonWorks - should be in next month's COL release. Thanks @ktotsum.
