### ISSUE TITLE
Strange authorship strings in WCO (Opiliones)

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#569]
Within Opiliones, there are 101 taxa that have extra " 1" at the end of the authorship string displayed by the API. For example:
Eotrogulus Thévenin, 1901 1

This is caused by erroneous NamePhrase property: For some reason, each extinct taxon in Opiliones has NamePhrase property value "1". The API then appends this "1" to the authorship string.

**Comment by yroskov** [comment]
Thank you, @aoern! 

Woops, indeed:

![image](https://github.com/CatalogueOfLife/data/assets/28574252/7e4de15a-902a-4b1c-98f4-3835d1029249)

@gdower , would it be possible to fix it in the export script for November update?

**Comment by yroskov** [comment]
It was a bug in GSDs exported from TW. FIXED NOW: PREVIEW 2023-11-13
