### ISSUE TITLE
Fill CoL gap: order †Permopsocida (Insecta)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#578]
_For consideration by the Taxonomy Group (@dhobern & @olafbanki), 2023-11-02:_

**Dataset title**
**Permopsocida Species File**
http://paraneoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1236719

**Dataset contact & access**
Permopsocida Species File was presented by at Taxon Works Together meeting in Oct 2023 by Heidi Hopkins as a global checklist maintained and curated in TaxonWorks.
Data are available via Species Files software at http://paraneoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1236719 and will be available via new TaxonPages soon.

**Taxonomic group & CoL sector**

CoL sector:
kingdom: Animalia > phylum: Arthropoda > class: Insecta > order: †**Permopsocida**

SF classifiction: 
class: Insecta > subclass Pterygota > infraclass Neoptera > cohort Paraneoptera > order †Permopsocida

**Dataset description**
Global checklist of extinct order of insects with 39 known species.

**Comment by yroskov** [comment]
@dhobern, as soon as TG give a green light, data can be exported from TW into CLB and included in CoL.

**Comment by mdoering** [comment]
@yroskov I think it is always useful to have _all_ TW data in CLB - whether (parts of) it get included as a GSD is a TG matter. But even for decision making it is good to have it there to look at. And last not least as an addition to the XCOL.

**Comment by camiplata** [comment]
@yroskov would it be possible to export this data already to CLB? so when can discuss this with the TG via email.

**Comment by yroskov** [comment]
Done in October! The checklist is already in CLB https://www.checklistbank.org/dataset/285690/about and also integrated in the CoL https://www.catalogueoflife.org/data/dataset/285690
