### ISSUE TITLE
CilCat: The World Ciliate Catalog - Bardeliellidae misspelled

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#586]
**Describe the problem**:
The issue was logged in the GBIF Feedback Portal https://github.com/gbif/portal-feedback/issues/5017 by @kbseah

They wrote:

> The name of GBIF taxon 7806899 is currently spelled "Bardelielidae", but should be spelled "Bardeliellidae". There is already a GBIF taxon under that name

See https://www.irmng.org/aphia.php?p=taxdetails&id=114187

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/737

**Literature references**:
the original publication (page 104) here: http://www.zobodat.at/pdf/STAPFIA_0012_0001-0165.pdf

**Comment by yroskov** [comment]
Fixed in November edition
