### ISSUE TITLE
Nov-2023 download incomplete

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#591]
Nov-2023 COLDP download contains only files metadata.yaml and dataset-278910.tsv ??

**Comment by mdoering** [comment]
@aoern here is a full download https://download.checklistbank.org/job/25/25a13fe6-10b0-4615-a8e4-e2786d1e82d4.zip

We have changed the default download to be a simple one with just a single taxon file and basic information. That is enough for most users actually and saves a ton of processing resources. Unfortunately the [UI is still lacking](https://github.com/CatalogueOfLife/checklistbank/issues/1321) the needed button to request a complete download, but that'll come real soon!

**Comment by mdoering** [comment]
same is true for dwca btw

**Comment by aoern** [comment]
Thanks, @mdoering . Downloaded now.
