### ISSUE TITLE
Section ranks in WoRMS sources

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#595]
WoRMS databases seem to contain taxa ranked as sections and subsections, when looking at their own web pages.
However, CoL database does not contain a single WoRMS section taxon. The sections of WoRMS databases appear in CoL ranked as 'other'. Oct 2023 edition still contained 5 sections and subsections (Eubrachyura, Podotremata, Acanthostegomorpha, Crinocheta and Diplocheta), but now also they are 'others'.
Automated update process changing the rank?

**Comment by mdoering** [comment]
It is given correctly, apparently an importer problem I will chase:
https://www.checklistbank.org/dataset/1108/verbatim/14912

Leaving the rest of the issue to fix/discuss if sector names are missing in COL

**Comment by mdoering** [comment]
@yroskov please wait with importing WoRMS. This needs to be deployed to prod first

**Comment by mdoering** [comment]
@yroskov the fix was deployed to prod and I have reimported Brachyura as a test which now lists 16 such names:
https://www.checklistbank.org/dataset/1108/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&rank=section%20zoology&rank=subsection%20zoology&sortBy=taxonomic

**Comment by gdower** [comment]
It will automatically import tomorrow and sync on the following day, but I could adjust the schedule if needed.

**Comment by yroskov** [comment]
@mdoering, could you please confirm that we can do WoRMS import tomorrow, Sat, 2nd Dec ?

**Comment by mdoering** [comment]
As Ive said above the fix is already deployed some hours ago

**Comment by camiplata** [comment]
In wfo the section option appears on the search

<img width="2406" height="836" alt="Image" src="https://github.com/user-attachments/assets/e500a248-eda7-45c5-aa7b-2b5cc66e5dc8" />

but it does not appears for COL dataset

<img width="1174" height="751" alt="Image" src="https://github.com/user-attachments/assets/098777c8-1d86-45d7-8a36-38cd844af4a3" />

@mdoering is this the desire behavior? I understand the dropdown menu only shows hits with higher counts, but when the search is narrowed down as in the screenshot above, should the section appear?

**Comment by mdoering** [comment]
It works for me:

<img width="1051" height="289" alt="Image" src="https://github.com/user-attachments/assets/6d88e890-332d-4a71-aa99-10e9a4c17523" />

But I will increase the facet limit to 50 so we can see most ranks and taxonomic groups without narrowing down with some search first.

PS: can we leave links in addition to screenshots so its easier to reproduce please?

**Comment by mdoering** [comment]
btw, you can add facetLimit=50 or 100 already now by appending to the portal URL:

https://www.catalogueoflife.org/data/search?TAXON_ID=P&facet=rank&facet=authorship&facet=group&facet=authorshipYear&facetLimit=100
