### ISSUE TITLE
Misspelling of binomial of Glaucocharis chrysochyta

### ISSUE THREAD

**Issue by SiobhanLeachman** [CatalogueOfLife/data#604]
cc @dhobern

The New Zealand endemic moth species _Glaucocharis chrysochyta_ (Meyrick, 1882) is misspelt in the CoL as Glaucocharis chrysoclyta Meyrick, 1882. This appears to have originated from a typo in the [Global Lepidoptera Names Index](https://www.nhm.ac.uk/our-science/data/lepindex/detail/?taxonno=5698).

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3G696

**Literature references**:
Edward Meyrick (June 1882). _Descriptions of New Zealand Micro-Lepidoptera (I.)_ New Zealand Journal of Science. 1: 186. [BHL link](https://www.biodiversitylibrary.org/page/41865809) Original description
Edward Meyrick (May 1883). _Descriptions of New Zealand Microlepidoptera. I and II. Crambidae and Tortricina_  Transactions and Proceedings of the New Zealand Institute. 15: 12–13. [BHL link](https://www.biodiversitylibrary.org/page/33980370) 
John Stewart Dugdale (23 September 1988). [_Lepidoptera - annotated catalogue, and keys to family-group taxa_](https://www.biotaxa.org/fnz/article/view/fnz.14). Fauna of New Zealand. 14: 144. [DOI](https://doi.org/10.7931%2FJ2%2FFNZ.14).
[Biota of New Zealand link](https://biotanz.landcareresearch.co.nz/scientific-names/870b3b04-e5fb-40f8-afc1-048dbed303f2)

**Comment by yroskov** [comment]
@dhobern, for your attention.

**Comment by dhobern** [comment]
Fixed in TaxonWorks - will upload to CLB in the next few days
