### ISSUE TITLE
Wrong publication date for the New Zealand moth species Rhathamictis nocturna

### ISSUE THREAD

**Issue by SiobhanLeachman** [CatalogueOfLife/data#605]
**Describe the problem**: 
The CoL gives the wrong publication date for both the current species name (so instead of _Rhathamictis nocturna_ (Clarke, 1888) it should be _Rhathamictis nocturna_ (Clarke, 1926)), as well as the basionym. 

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/B72TY

**Literature references**:
Original description: Charles Edwin Clarke (12 July 1926). "[New species of Lepidoptera](https://paperspast.natlib.govt.nz/periodicals/TPRSNZ1926-56.2.7.1.40)" Transactions and Proceedings of the New Zealand Institute. 56: 421.
Recombination: John Stewart Dugdale (23 September 1988). ["Lepidoptera - annotated catalogue, and keys to family-group taxa"](https://www.biotaxa.org/fnz/article/view/fnz.14). Fauna of New Zealand. 14: 69. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.7931/J2/FNZ.14](https://doi.org/10.7931%2FJ2%2FFNZ.14).
BiotaNZ:["Rhathamictis nocturna (Clarke, 1926) - Biota of NZ"](https://biotanz.landcareresearch.co.nz/scientific-names/f02beaf2-baca-4029-b2c9-5843bb205b9b). biotanz.landcareresearch.co.nz. Retrieved 2024-01-01.

**Comment by yroskov** [comment]
@dhobern, for your attention.

**Comment by dhobern** [comment]
Fixed in TW - moving to CLB soon
