### ISSUE TITLE
Incorrect DOI for monthly update of the World Entiminae Database

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#606]
@Omias commented that DOI in CoL of **December** (https://www.catalogueoflife.org/data/dataset/1166) is pointed to the outdated version of World Entiminae Database  (**Jun 2021**): [https://doi.org/10.48580/dfp3-3f8](https://urldefense.com/v3/__https:/doi.org/10.48580/dfp3-3f8__;!!DZ3fjg!7EgkgT04cmpjfzGUnmf_Jjbtr98DJo2UpnMOeVPZ08Z3InTQRXHyQ1VvEwDmkNBPhulo7J2oBP2cb6cMcJkj$)

![image](https://github.com/CatalogueOfLife/data/assets/28574252/1c677934-3009-4ef4-bb2d-a5a398aa26e8)

![image](https://github.com/CatalogueOfLife/data/assets/28574252/0159ff68-b414-491f-9a38-5463cfa96c24)

**Comment by mdoering** [comment]
That would be correct if data had not changed since that edition. But it apparently did, so sth is not right:
<img width="1435" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/71464f92-7f6a-465a-9f4d-11f99933574c">

**Comment by yroskov** [comment]
Yes, we are updating Entiminae database every month.

**Comment by yroskov** [comment]
I have checked few other GSDs for their DOIs. Some of them have the same problem (DOI points to the old version), **many GSDs have no DOIs at all** - is it expecting behavior?

_Checked GSDs:_

**No DOI**:
3i Auchenorrhyncha: https://www.catalogueoflife.org/data/dataset/2317
GLI: https://www.catalogueoflife.org/data/dataset/55434
ITIS: https://www.catalogueoflife.org/data/dataset/2144
Scarabs: https://www.catalogueoflife.org/data/dataset/1027
SF Isoptera: https://www.catalogueoflife.org/data/dataset/1198
World Ferns: https://www.catalogueoflife.org/data/dataset/1140
World Plants: https://www.catalogueoflife.org/data/dataset/1141
WCO: https://www.catalogueoflife.org/data/dataset/2256 

**DOI points to the old version:**
WOL: https://www.catalogueoflife.org/data/dataset/125101, new version of 2023-12-07, DOI points to old of 2022

**Comment by yroskov** [comment]
I have killed incorrect DOI in the metadata

**Comment by yroskov** [comment]
New, more general ticket is opened: https://github.com/CatalogueOfLife/data/issues/608
