### ISSUE TITLE
Lepidopteria genus Ctenarchis and species Ctenarchis cramboides missing from CoL

### ISSUE THREAD

**Issue by SiobhanLeachman** [CatalogueOfLife/data#607]
**Describe the problem**:
The New Zealand endemic monotypic moth genus _Ctenarchis_ and the species _Ctenarchis cramboides_ currently appear to be missing from the CoL. 

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/7RQ 

**Literature references**:
Original description: Dugdale, J. S. (January 1995). ["A new genus and species of New Zealand Carposinidae (Lepidoptera)"](https://www.researchgate.net/publication/233339100_A_new_genus_and_species_of_New_Zealand_Carposinidae_Lepidoptera). New Zealand Journal of Zoology. 22 (2): 213–216. [doi](https://doi.org/10.1080%2F03014223.1995.9518036).
Gordon, Dennis P., ed. (2010). New Zealand inventory of biodiversity: Kingdom animalia : chaetognatha, ecdysozoa, ichnofossils. Vol. 2. p. 457. 
Genus: [Biota of New Zealand](https://biotanz.landcareresearch.co.nz/scientific-names/b63158c6-5bf9-4a1f-8770-fac9a88a642a) 
Species: [Biota of New Zealand](https://biotanz.landcareresearch.co.nz/scientific-names/444f3e65-f254-40ed-854c-af4b9f4f2e39)

**Comment by yroskov** [comment]
For attention of @dhobern

**Comment by dhobern** [comment]
I've added it to TaxonWorks and will move into COL later this week
