### ISSUE TITLE
Problems with DOIs application in CoL

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#608]
As we discovered after @Omias comment (https://github.com/CatalogueOfLife/data/issues/606), there is a significant problem with  DOI application to source checklists in the Checklistbank/CoL. **Neither of 33 checked source checklists has correct DOI**. 

As I can see, there are 4 groups of DOI cases:

_Points to the old version in CLB:_
**Entiminae** (checked 2023-01-02)
**WOL** (checked 2023-01-03)

_Points to the old version on GBIF webpage:_
**Alucitoidea** 1.1.23.298 (25 Oct 2023) / 2022-11-10 (checked 2023-01-03) doi  10.15468/ew9akc points to https://www.gbif.org/dataset/484039df-cd14-46d1-9a41-c406db8c7ced  and refers to August 17, 2021 
Brassicaceae 2021-08-31 (checked 2023-01-03) doi  10.15468/rb7kky  points to https://www.gbif.org/dataset/94308742-058c-46d5-b763-06e9207a6b15  and refers to August 31, 2021 = that is probably correct, but need to be confirmed with the dataset history 
**Pterophoroidea** 1.1.23.284 (11 Oct 2023) / 2023-01-05 (checked 2023-01-03) doi  10.15468/d9u533 points to https://www.gbif.org/dataset/c815ecb1-b036-4617-b545-1bb65e0339cd  and refers to August 17, 2021 
**SF Orthoptera** (checked 2023-01-03) doi 10.15468/nn7jhc points to GBIF page https://www.gbif.org/dataset/af66d4cf-0fd2-434b-9334-9806a5efa6f7 and refers to January 14, 2019

_Points to the original webpage of source GSD*:_
_(This case of DOI application is also incorrect, because CLB view of WoRMS data might be different from the view published at www.marinespecies.org. Copy of WoRMS data in CLB is not identical to the original data)._
WoRMS Foraminifera  (checked 2023-01-03) 10.14284/305 https://www.marinespecies.org/imis.php?dasid=3113&doiid=305 
WoRMS Copepoda  (checked 2023-01-03)  10.14284/356 https://www.checklistbank.org/dataset/1191/about
WoRMS Mollusca (checked 2023-01-03)  10.14284/448 https://www.marinespecies.org/imis.php?dasid=5275&doiid=448
WoRMS Nemertea (checked 2023-01-03)  10.14284/459 https://www.marinespecies.org/imis.php?dasid=4189&doiid=460
WoRMS Nemys (checked 2023-01-03)  10.14284/366 https://www.marinespecies.org/imis.php?dasid=66&doiid=366
WoRMS Porifera (checked 2023-01-03)  10.14284/359 https://www.marinespecies.org/imis.php?dasid=546&doiid=359
WoRMS Strepsiptera (checked 2023-01-03)  10.14284/484 https://www.marinespecies.org/imis.php?dasid=6715&doiid=485
etc.

_DOI absent (checked 2023-01-03):_
3i Auchenorrhyncha
AnnonBase
BdelloideaBase
Brentids
Bryonames
CarabCat
CCW
Collembola.org
COOL
Eumycetozoa.com
ITIS 
Scarabs 
SF Isoptera 
WCO 
WoRMS Chaetognatha 
WoRMS Merostomata 
WoRMS Oligochaeta 
WoRMS Polychaeta 
WoRMS Priapulida 
WoRMS Turbellarians 
WoRMS Xenoturbellida 
etc.

**Comment by yroskov** [comment]
**Expected "best practice":**
DOI should be issued for the source checklist/GSD after the sync in the Catalogue of Life.   

(Data & metadata synced in the CoL after application of Editorial Decisions quite possible are different from from data imported in the CLB. And data version in CLB after all modifications & cleanings are different from the checklist original view published on the website).

**Comment by mdoering** [comment]
The project contains a setting `Release Issue Source Dois` which was set to false. That means for no source any DOI was issued or reused. Just the ones that were already on the source dataset were kept - which explains why we see GBIF or WoRMS DOIs. Any COL DOI will start with `10.48580`, all others are cannot be managed by ChecklistBank.

I will do a test release now to see how DOIs are created when the setting is turned on.

**Comment by mdoering** [comment]
The latest 8.1.2024 release candidate has good source DOIs for Entiminae, Pterophoroidea and others. Looks like it is solved
