### ISSUE TITLE
Duplicate classification in Hemiptera

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#617]
The family Progonocimicidae and its descendants down to genus level are taxonomically classified under suborder Coleorrhyncha by SF Coleorrhyncha and directly under order Hemiptera by CoL ('source 0').

**Comment by yroskov** [comment]
Thank you, @aoern!

Hmm, I clearly see these two entries in the final version: 
https://www.catalogueoflife.org/?taxonKey=8NKPK
![image](https://github.com/CatalogueOfLife/data/assets/28574252/40d7737f-56fc-4925-bbd6-c6446015d0f4)

https://www.catalogueoflife.org/?taxonKey=BWB3V
![image](https://github.com/CatalogueOfLife/data/assets/28574252/b56c880c-da47-4fd6-9e35-3fd760be3d26)

But, I see only a single entry in CLB:
![image](https://github.com/CatalogueOfLife/data/assets/28574252/8ab9233e-7005-48ca-8d46-cba96c0d90a8)

Needs further investigation (@gdower, can we have a look together, please?)

**Comment by yroskov** [comment]
Finally, we found second entry in the Tree and deleted it. 2024-02-01.
