### ISSUE TITLE
GLI: Global Lepidoptera Index - Proterebia afra synonym of Proterebia phegea (Borkhausen, 1788)

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#619]
**Describe the problem**:
This feedback message originally came to the GBIF helpdesk:

> the most recent checklist of butterflies of Europe synonymised Proterebia afra with Proterebia phegea (Borkhausen, 1788)

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/947KW

**Literature references**:
Wiemers M, Balletto E, Dincă V, Fric ZF, Lamas G, Lukhtanov V, Munguira ML, van Swaay CAM, Vila R, Vliegenthart A, Wahlberg N, Verovnik R (2018) An updated checklist of the European Butterflies (Lepidoptera, Papilionoidea). ZooKeys 811: 9-45. https://doi.org/10.3897/zookeys.811.28712

**Comment by yroskov** [comment]
For attention of @dhobern

**Comment by dhobern** [comment]
Thanks - I am trying hard to get replacement datasets for all the butterflies, but I've fixed this one now.

**Comment by dhobern** [comment]
In GLI - will be available for COL in a few days
