### ISSUE TITLE
The World Odonata List - typo in metadata

### ISSUE THREAD

**Issue by CecSve** [CatalogueOfLife/data#620]
**Describe the problem**:
The description of the GBIF published checklist [The World Odonata List](https://www.gbif.org/dataset/1873a64d-e5fe-498b-8881-1cab2c39e6f6) contains a misspelling of one of the maintainers. Please see the following issue submitted to GBIF Helpdesk: https://github.com/gbif/portal-feedback/issues/5113. It seems the misspelling is corrected in Checklistbank (see link). I assume the fix might be implemented in the next backbone release? 

**Link to effected CoL webpages**:
https://www.checklistbank.org/dataset/125101/about

**Literature references**:
...

**Comment by yroskov** [comment]
Misspelled name was fixed in the CoL of 2024-01-24.
