### ISSUE TITLE
Missing Daesiidae species

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#621]
There are quite a few species missing from the [Daesiidae](https://www.catalogueoflife.org/data/taxon/8YJ) family in COL 24.1

The following (sub)species were existing in the iSpot species dicitonary, but not found in COL:

 - Bitonella roeweri
 - Blossiola alticursor
 - Blossiola brinki
 - Blossiola crepidulifera
 - Blossiola echinata
 - Blossiola grandicornis
 - Blossiola hessei
 - Blossiola karrooica
 - Blossiola laminicornis
 - Blossiola lapidicola
 - Blossiola litoralis
 - Blossiola longipalpis
 - Blossiola namaquensis
 - Blossiola orangica
 - Blossiola falcifera subsp. brachygnatha
 - Blossiola falcifera subsp. longicornis
 - Blossiola falcifera subsp. transvaalica
 - Bradornis infuscatus subsp. infuscatus

**Comment by yroskov** [comment]
Just in case, @DaveNicolson, is there anything from ITIS?

**Comment by DaveNicolson** [comment]
As a matter of fact, ITIS does have a full update of the Solifugae pretty much ready for loading, and we expect to have it in ITIS in the next load or two (end of February or end of April).

**Comment by yroskov** [comment]
Thank you! Great

**Comment by DaveNicolson** [comment]
Where did those names come from? I assumed they would be newly-described taxa, but they seem to be non-current combinations of valid taxa...

**Comment by DaveNicolson** [comment]
The last one uses a bird genus (Bradornis)...

**Comment by mdoering** [comment]
... the bird name is my bad, I had missed the different classification.
Otherwise these are from the [iSpot](https://www.ispotnature.org) dictionaries and might indeed not be current. Nice to see they can be mapped to existing species in COL.

**Comment by DaveNicolson** [comment]
The Solifugae update is in the pending load, so it won't have to wait 2 more months ;-)

**Comment by camiplata** [comment]
I understand this update was made last year so I'm closing the issue
