### ISSUE TITLE
GLI: Global Lepidoptera Index - Austrocaligula is a synonym

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#625]
**Describe the problem**:

The issue was originally reported on the GBIF Feedback portal: https://github.com/gbif/portal-feedback/issues/5188

> the genus Austrocaligula is a junior synonym of Opodiphthera
> Austrocaligula carnea (as Anthereae carnea Sonthonnax, 1899) is considered a junior synonym of Opodiphthera loranthi (T.P. Lucas, 1891)

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/95HSR
https://www.catalogueoflife.org/data/taxon/9627L

**Literature references**:
https://biodiversity.org.au/afd/taxa/Opodiphthera
https://biodiversity.org.au/afd/taxa/86175a79-7947-4730-83a3-f7470a8e6b93

**Comment by yroskov** [comment]
Dear @dhobern, it's for you

**Comment by dhobern** [comment]
In GLI now - will update a new snapshot in a few days, then it should fix in the next COL release.
