### ISSUE TITLE
Authorship transcription error - Neomolgus pallipes (L.) Koch, 1879

### ISSUE THREAD

**Issue by CecSve** [CatalogueOfLife/data#626]
**Describe the problem**:
A GBIF user has made us aware of [an issue](https://github.com/gbif/portal-feedback/issues/5184) in the authorship of the species _Neomolgus pallipes_ (L.) Koch, 1879. The species was described by Ludwig Koch in _Koch, L. Bdella oblonga. Kongliga Svenska Vetenskaps-Akademiens Handlinger, 16: 132. (1879)_, but the way the author's name is given, it seems Linnaeus was the one who gave the original combination and Koch then authored a recombination of the name. 

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/46N2Z

**Literature references**:
Koch, L. Bdella oblonga. Kongliga Svenska Vetenskaps-Akademiens Handlinger, 16: 132. (1879).

**Comment by yroskov** [comment]
Forwarded to the editors of BdelloideaBase for their consideration.

**Comment by yroskov** [comment]
Correction approved. It will appear in CoL of March.
