### ISSUE TITLE
Weird name parsing in ReptileDB

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#628]
Now that ReptileDB has been resynced, many invalid character and encoding problems have been fixed.
The following name parsing problem still exists. An authorship string beginning with a lower case letter seems to mess the parsing. The strange names are listed below (the | character is used to separate the scientific name and the authorship string):

Lepidophyma flavimaculatum flavimaculatum a. | Duméril, 1851
Liolaemus tenuis müller & | Hellmich, 1933
Liolaemus zapallarensis ater (müller& | Hellmich, 1933)
Phelsuma abbotti chekei (börner& | Minuth, 1984)
Phelsuma sundbergi böhme & | Meier, 1981
Phoenicolacerta kulzeri kulzeri (müller& | Wettstein, 1932)
Ptenopus garrulus garrulus (a. | Smith, 1849)
Trioceros quadricornis gracilior (böhme& | Klaver, 1981)
Vipera anatolica senliki göçmen | Mebert, Kariş, Oǧuz & Ursenbacher, 2017
Vipera berus böhme & | Joger, 1983

**Comment by yroskov** [comment]
I cleaned up such names 2024-03-04. Scheduled for re-sync.
