### ISSUE TITLE
Strange names in Species Fungorum Plus

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#659]
1. Jin F. Zhang, Jian K. Liu, K.D. Hyde & Zuo Y. Liu	
   There are two genera by this name !
   The 1st is supposed to be Ligninsphaeria and the 2nd Elongatopedicellata 

2. Jian L. Zhou & Kohlm.
   There is a genus by this name!
   It probably should be Diatrypasimilis

3. Pseudeurotiaceae_x000d_\\nPseudeurotiaceae	
   sic!

4. Pyrenopeziza poаe (Fuckel) Boud.
   In "poae", 'o' is Cyrillic o and 'а' is Cyrillic A

5. Salisapilia tartarea  (Nakagiri & S.Y. Newell) Hulvey, Nigrelli, _x000d_ Telle, Lamour & Thines
   Nonsense authorship

**Comment by yroskov** [comment]
Thank you! Fixed in June release
