### ISSUE TITLE
Self-synonymized taxa in UCD update

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#660]
There are 104 names in new UCD update that have a name usage record for an accepted taxon and an (ambiguous) synonym record by the same name and authorship.
Does this convention have a message or is it just a bug?

Adelencyrtus oceanica  (Doutt, 1951)
Ammonoencyrtus californicum  (Compere, 1925)
Aphytis hispanica  (Mercet, 1912)
Aprostocetus purpurea  (Cameron, 1913)
Asecodes politus  (Hansson, 1994)
Aulogymnus trilineata  (Mayr, 1877)
Baryscapus americanus  (Ashmead, 1888)
Blastothrix sericeus  (Dalman, 1820)
Brephonastes  Prinsloo
Callacnemus  Prinsloo
Centrodora oophagus  (Girault, 1917)
Centrodora speciosissimus  (Girault, 1911)
Ceratosolen ficophaga  (Girault, 1915)
Ceratosolen nota  (Baker, 1913)
Chartocerus elongata  (Girault, 1916)
Chartocerus nigra  (Ashmead, 1900)
Chartocerus subaenea  (Förster, 1878)
Closterocerus trifasciatus  Westwood, 1833
Coccidoctonus dubia  (Girault, 1915)
Coelopisthia extentus  (Walker, 1835)
Colpoclypeus florus  (Walker, 1839)
Copidosoma truncatellus  (Dalman, 1820)
Courtella peniculum  (Wiebes, 1974)
Cratomus  Dalman, 1820
Dimmockia incongruus  (Ashmead, 1898)
Dimmockia secundus  Crawford, 1910
Elasmus nuda  (Nees, 1834)
Encarsia citrina  (Craw, 1891)
Eoeurytomites  Hong
Eomonodontomerites  Hong
Eotorymites  Hong
Erotolepsiella  Girault, 1915
Euplectromorpha bicarinatus  (Ferrière, 1940)
Eurydinoteloides incertus  (Ashmead, 1893)
Eurytoma noxiale  (Portschinsky, 1881)
Eurytoma verticillatum  (Fabricius, 1798)
Eusemion longipennis  (Ashmead, 1888)
Fushuneurytomites  Hong
Halticoptera minutus  (Förster, 1861)
Hobbya stenonotus  (Ratzeburg, 1848)
Horismenus fraterna  (Fitch, 1856)
Huaxiatorymus  Hong
Indoclava  Gupta, Khan & Agnihotri
Leptacnemus  Prinsloo
Leptomastix flavus  Mercet, 1921
Leptotorymites  Hong
Liaoeurytomites  Hong
Marietta mexicanus  (Howard, 1895)
Marietta pictus  (André, 1878)
Marietta pulchellus  (Howard, 1881)
Merismomorpha  Girault, 1913
Microterys cuprina  (Nikol'skaya, 1952)
Neomegastigmus  Girault, 1915
Notanisomorphella borboricus  (Giard, 1903)
Notanisus sexramosa  (Erdös, 1946)
Ooencyrtus pinicolus  (Matsumura, 1926)
Ormyrus nitidula  (Fabricius, 1804)
Ormyrus vacciniicola  Ashmead, 1887
Pachyneuron solitarius  (Hartig, 1838)
Panstenon oxylus  (Walker, 1839)
Paraphyeina  Hoffer
Pareulophites  Hong
Pediobius polanensis  Bouček, 1965
Pegoscapus mexicana  (Ashmead, 1904)
Protaenasius  Fullaway
Pseudotorymus lazulella  (Ashmead, 1890)
Pteromalinites  Heer
Pteromalus coeruleus  Foerster, 1841
Ramalia  Mercet
Rubrencyrtus  Prinsloo
Signiphora flavopalliata  Ashmead, 1880
Sinoeurytomites  Hong
Sinoperilampites  Hong
Stenomesius japonica  (Ashmead, 1904)
Sycophila biguttatus  (Swederus, 1795)
Sympiesis stigmatus  Girault, 1917
Sympiesis viridulus  (Thomson, 1878)
Sympiesis xanthostomus  (Nees, 1834)
Szelenyia  Nowicki, 1940
Tamarixia radiatus  (Waterston, 1922)
Tetramesa aciculatum  (Schlechtendal, 1891)
Tetramesa brevicolle  (Walker, 1836)
Tetramesa brevicorne  (Walker, 1832)
Tetramesa cornutum  (Walker, 1832)
Tetramesa elymophaga  (Phillips, 1927)
Tetramesa eremitum  (Portschinsky, 1881)
Tetramesa eximium  (Giraud, 1863)
Tetramesa hyalipenne  (Walker, 1832)
Tetramesa lineare  (Walker, 1832)
Tetramesa longicorne  (Walker, 1832)
Tetramesa neocaptiva  (Peck, 1951)
Tetramesa rossicum  (Rimsky-Korsakov, 1914)
Tetramesa sulcata  (Ashmead, 1894)
Tetramesa vaginicolum  (Doane, 1916)
Thomsonisca amathus  (Walker, 1838)
Torymus capillaceum  (Huber, 1927)
Torymus cecidicola  (Brèthes, 1927)
Torymus hirsutum  (Huber, 1927)
Torymus umbilicata  (Gahan, 1919)
Trichomalopsis peregrinus  (Graham, 1969)
Trichospilus pupivora  Ferrière, 1930
Trigonopterites  Hong
Zarhopalus corvina  (Girault, 1915)
Zhuia  Hong

**Comment by yroskov** [comment]
Thank you! 

It looks like I was not able to see/resolve these cases in TASK tools. I need to do blocking one be one via Workbench.

**Comment by mdoering** [comment]
The project task board lists 33 such species, also from other sources:
https://www.checklistbank.org/dataset/3/duplicates?acceptedDifferent=false&authorshipDifferent=false&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym

**Comment by yroskov** [comment]
FIXED & re-synced 2024-06-03
