### ISSUE TITLE
Pachyrhynchus - misduplicated genus (insecta, beetles)

### ISSUE THREAD

**Issue by sjl197** [CatalogueOfLife/data#662]
The genus Pachyrhynchus (and at least some descendants) appears to come up in three different places in the taxonomy
...

Pachyrhynchus (genus in Curculionidae): 4 spp
https://www.catalogueoflife.org/?taxonKey=8HFQP
Pachyrhynchus (genus in Pachyrhynchini): many
https://www.catalogueoflife.org/data/taxon/B6LKH
Pachyrhynchus (prov. genus in Ithyceridae)
https://www.catalogueoflife.org/data/taxon/8HFQM

I know there's lots of beetle taxa in the world, but when you list the same three times then there's a problem.  :)

...

**Comment by yroskov** [comment]
Pachyrhynchus (genus in Curculionidae): 4 spp
https://www.catalogueoflife.org/?taxonKey=8HFQP

and 

Pachyrhynchus (genus in Pachyrhynchini): many
https://www.catalogueoflife.org/data/taxon/B6LKH

**are resolved now** (changes will appear in June release).

Pachyrhynchus (prov. genus in Ithyceridae)
https://www.catalogueoflife.org/data/taxon/8HFQM

is Provisionally accepted name in the CoL. Awaiting resolution by the authors of WTaxa.
