### ISSUE TITLE
Write new PBDB ColDP converter in java

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#666]
Using the API services documented at https://paleobiodb.org/data1.2/, e.g. https://paleobiodb.org/data1.2/taxa/single_doc.html

**Comment by mdoering** [comment]
There is a first ColDP archive existing now on dev: https://www.dev.checklistbank.org/dataset/293467

**Comment by mdoering** [comment]
Improved with temporal geotime and some fixed. Uploaded to prod now:
https://www.checklistbank.org/dataset/1174/about

**Comment by camiplata** [comment]
Having two PaleoDB datasets can be confusing. Is it possible to delete the [old one](https://www.checklistbank.org/dataset/268676/about) or change its title to indicate that it has been deprecated?

**Comment by mdoering** [comment]
Indeed. I am a big advocate of keeping the first dataset key and update that instead. @yroskov uses it already for the base COL, but I don't think it every gets synced so we should be able to import a new version?
