### ISSUE TITLE
ReptileDB - authorship brackets missing for some names

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#667]
Reptile database website shows this taxon authorship name within brackets [Chironius quadricarinatus (Boie, 1827)](https://reptile-database.reptarium.cz/species?genus=Chironius&species=quadricarinatus), but on [COL](https://www.catalogueoflife.org/data/taxon/5XT7P) are missing

**Comment by camiplata** [comment]
Reptile database website shows this taxon authorship name within brackets [Epictia magnamaculata (Taylor, 1940)](https://reptile-database.reptarium.cz/species?genus=Epictia&species=magnamaculata), but on [COL](https://www.catalogueoflife.org/data/taxon/6FR6D) are missing

**Comment by gdower** [comment]
Thanks, @camiplata! In the parentheses column, some records have YY instead of the usual Y. I loosened the converter to accept YY. That fixes 74 brackets including the ones above. @yroskov, it's imported and could be synced.

**Comment by camiplata** [comment]
Awesome thanks @gdower
