### ISSUE TITLE
xrelease reference information is leaking to main COL

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#668]
see: https://www.catalogueoflife.org/data/taxon/D5LL
<img width="1102" alt="Captura de pantalla 2024-06-06 a la(s) 6 55 52 p m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/ceb37886-7f6a-4c6c-8a32-325d1e770eec">

**Comment by mdoering** [comment]
I will try to reset the data so that authorship and published_in are empty again. The parent classification change I don't know how to fix. It might be best to sync effected sectors again. I will try to get an overview which these are, could be a lot...

**Comment by mdoering** [comment]
A PARENT case [Sciadophycus E.Y. Dawson, 1944](https://www.checklistbank.org/dataset/296511/taxon/7DZL) from [IRMNG](https://www.checklistbank.org/dataset/2007/taxon/urn:lsid:irmng.org:taxname:1073099) has the following classification:

>unranked: Biota
kingdom: Plantae
phylum: Rhodophyta
subphylum: Eurhodophytina
class: Florideophyceae Cronquist
order: Rhodymeniales F. Schmitz
family: Rhodymeniaceae Harvey, 1849
genus: Sciadophycus E.Y. Dawson, 1944

The original IRMNG one is this:

>unranked: Biota 
 kingdom: Plantae Haeckel, 1866 
 phylum: Rhodophyta 
 subphylum: Eurhodophytina 
 class: Florideophyceae Cronquist 
 order: Rhodymeniales F. Schmitz
 family: Rhodymeniales incertae sedis
 genus: Sciadophycus E.Y. Dawson, 1944
 
 ITIS has:
>kingdom: Plantae
 subkingdom: Biliphyta
 phylum: Rhodophyta
 subphylum: Eurhodophytina
 class: Florideophyceae
 subclass: Rhodymeniophycidae
 order: Rhodymeniales
 family: Rhodymeniaceae
 genus: Sciadophycus
 
 
You can see IRMNG did not have a family (_Rhodymeniales incertae sedis_), which was then added by the ITIS merge as _Rhodymeniaceae_.

**Comment by mdoering** [comment]
There are 55 sectors effected by the PARENT merge:

```
clb=> select u.sector_key, count(*) from verbatim_source_secondary v JOIN name_usage u ON u.dataset_key=v.dataset_key and u.id=v.id where v.dataset_key=296511 and v.type='PARENT' group by 1;
 sector_key | count 
------------+-------
        210 |     6
        230 |     3
        255 |     5
        260 |     7
        331 |     5
        459 |     2
        504 |     1
        521 |     2
        663 |    46
        670 |     2
        906 |     1
        919 |     1
        935 |     2
        990 |    17
       1012 |     1
       1023 |     1
       1075 |     4
       1191 |     3
       1201 |     1
       1204 |     1
       1266 |     1
       1275 |    15
       1283 |     1
       1290 |    14
       1293 |     4
       1294 |     4
       1297 |    19
       1302 |     7
       1312 |     3
       1320 |     1
       1321 |     1
       1324 |     1
       1327 |     1
       1328 |     1
       1336 |     6
       1386 |   408
       1614 |     1
       1615 |     5
       1700 |     8
       1707 |     7
       1755 |     2
       1759 |    27
       1778 |     3
       1790 |     2
       1793 |     3
       1808 |     4
       1996 |     2
       2009 |    32
       2033 |     1
       2034 |     1
       2089 |     4
       2095 |     4
       2136 |     4
       2145 |     1
       2149 |     1
            |     2
(56 rows)
```

**Comment by mdoering** [comment]
By far the largest is Systema Dipterorum with more than half of the records. @yroskov maybe we can resync that and the few other larger ones?

**Comment by mdoering** [comment]
I have reset the published in names. The added authorship can also be removed, but identifiers are different between releases as the authorship enforces an identifier change. Example _Lepidonotus dentatus_:

https://www.checklistbank.org/dataset/296511/taxon/CB73F
https://www.checklistbank.org/dataset/294826/taxon/85337

**Comment by mdoering** [comment]
I have just synced the small sector [The World List of Cycads](https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=1163) which resolved the authorship and parent merges. Since the last sync of that source was in 2020 we also were missing some track record of the actual source, it seems we have implemented that shortly after only. I would really be good to resync all sectors that last have been synced before 2021 or even 2022.

**Comment by mdoering** [comment]
authorship reset for 14.339 names:

```
UPDATE name n SET authorship=null, 
 basionym_authors='{}', basionym_ex_authors='{}', basionym_year=null, 
 combination_authors='{}', combination_ex_authors='{}', combination_year=null, 
 sanctioning_author=null

 FROM verbatim_source_secondary v, name_usage u  
 WHERE n.dataset_key=3 AND
  u.dataset_key=3 AND u.name_id=n.id AND
  v.dataset_key=3 AND v.type='AUTHORSHIP' AND v.id=u.id;
```

**Comment by mdoering** [comment]
Only  115 PARENT secondary sources left

**Comment by yroskov** [comment]
Well, if you take my advice in the beginning to leave Expended Catalog as a separate project, then we don't have such problems now.

Also, you now have a good illustration of the problem when the "old" version (i.e. one classification) does not match the new one in the merged sectors. Do we really have enough expertise to resolve conflicts?

**Comment by yroskov** [comment]
> By far the largest is Systema Dipterorum with more than half of the records. @yroskov maybe we can resync that and the few other larger ones?

Yes, we can re-sync SD without problem now. Last sync was done 2024-06-04 8:11 PM. @mdoering, let me know if CLB is ready for re-sync and I'll kick it off.

Potential resyncing of other GSDs needs to be discussed on a case-by-case basis, including @gdower recommendations.

**Comment by mdoering** [comment]
please give me 1.5h (18:30 CET) to deploy a new version, then you are welcome to sync or release as you like

**Comment by yroskov** [comment]
OK

**Comment by yroskov** [comment]
@mdoering, can I start syncs now?

**Comment by mdoering** [comment]
yes

**Comment by yroskov** [comment]
OK, I am going ahead with remaining re-syncs
