### ISSUE TITLE
Global Lepidoptera Index - Drepana bilineata

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#672]
**Describe the problem**:
This came from an issue originally logged in the GBIF Portal Feedback: https://github.com/gbif/portal-feedback/issues/5353
According to the feedback message.

Drepana rampartensis is missing and should be added as a junior synonym of Drepana bilineata (Packard, 1864). Drepana bilineata (Packard, 1864) is the valid name.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3DT4J

**Literature references**:
See Pohl et al. 2018 Annotated checklist of the moths and butterflies (Lepidoptera) of Canada and Alaska .

**Comment by yroskov** [comment]
@dhobern, it's for you

**Comment by dhobern** [comment]
![image](https://github.com/CatalogueOfLife/data/assets/26148454/6e77fe6c-9d7b-4a0f-a82b-9679e326dab9)

Pohl & Nanz 2023 has the Drepanini as shown here. I'll make GLI match this arrangement.

**Comment by dhobern** [comment]
Looking at it, it seems that GLI is currently correct because this species has now been returned to the genus where it has been in GLI for some time.

**Comment by dhobern** [comment]
Closing
