### ISSUE TITLE
WoRMS class Malacosporea has class as a parent

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#679]
The accepted [class Malacosporea](https://www.marinespecies.org/aphia.php?p=taxdetails&id=851298) has as its parent another class [Myxozoa](https://www.marinespecies.org/aphia.php?p=taxdetails&id=146271)

**Comment by yroskov** [comment]
Hmm... Exactly as in the WoRMS export:
![image](https://github.com/CatalogueOfLife/data/assets/28574252/5fb8498b-d0fd-43ac-ad86-a44340298204)

**Comment by mdoering** [comment]
Yes. But is that done on purpose?

**Comment by yroskov** [comment]
@bart-v, for your attention (just in case, if editors made mistake)

**Comment by bart-v** [comment]
OK, forwarded the issues to the editors

**Comment by bart-v** [comment]
This has been fixed in WoRMS, available in next version of 2024-07-01
