### ISSUE TITLE
ITIS - Phyllobrotica nigritarsi should be nigritarsis

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#684]
**Describe the problem**:
[Feedback originally from GBIF](https://github.com/gbif/backbone-feedback/issues/134) and evaluated with the current version of the xrelease and ITIS.

Phyllobrotica nigritarsi Linell, 189 should be Phyllobrotica nigritarsi`s` Linell, 1898

original description
https://www.biodiversitylibrary.org/page/15838278#page/570/mode/1up

The reference in [ITIS](https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=720360#null) also point towards `Phyllobrotica nigritarsis Linell, 1898`

<img width="697" alt="Captura de pantalla 2024-07-11 a la(s) 9 19 00 p m" src="https://github.com/user-attachments/assets/03c0f298-5b09-4d7f-b17d-2ad13807f773">

Hi @DaveNicolson for the xrelease we take this name from ITIS, by reviewing the references I think the recommended change is correct.

**Comment by DaveNicolson** [comment]
Thanks for noting this & checking the details! Clearly this is a typo that slipped through QA/QC. We'll get it fixed (probably this month). The existing name will become a "database artifact" that hides it from anyone not explicitly searching it up by name or TSN, but it'll still be in ITIS (not sure if @gdower filters out ITIS TSNs with "artifact" in the unacceptability_reason string, but it'd probably be a good idea, as we use that term for strings not found in the published literature but that are in ITIS).

**Comment by gdower** [comment]
I don't include database artifacts based on your previous instructions.

**Comment by DaveNicolson** [comment]
So it will disappear from ITIS in Checklist Bank and COL, and I would recommend dropping it completely. The new corrected version will appear in ITIS (etc.) with a new TSN once we get it loaded into ITIS (end of July).
