### ISSUE TITLE
World Plants version wrong

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#698]
COL claims to have [version 19.4](https://www.checklistbank.org/dataset/1141/about) from 30th of June while WP claims to be on version 24.8 from August 27th. That does not sound plausible.

**Comment by mdoering** [comment]
We also see to only have ~half the content from WP in CLB. 
WP claims to cover [355.300 accepted species](https://www.worldplants.de/world-plants-complete-list/complete-plant-list) while we have [207,093 species in CLB](https://www.checklistbank.org/dataset/1141/names?rank=species&status=accepted). This either needs to be reflected in the metadata or - much better - we get the entire WP list!

**Comment by yroskov** [comment]
CoL gets only part of WorldPlants and combines it with WCVP families. We have a permission to place in CLB only WP part granted to CoL.

I sent a question about version figure to Michael.

**Comment by yroskov** [comment]
Michael, 2024-09-06: _From July onwards I have changed the version numbers to simply reflect the year and month of release. Therefore 19.4 was immediately followed by 24.7 (July 2024). This is explained in the comments section of WorldPlants but not everybody reads this._

So, next WP update in the CoL will follow a new versioning.
