### ISSUE TITLE
ZooBank <Unspecified Agent>

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#709]
ZooBank names without authorship contain `<Unspecified Agent>` instead.
Contact ZooBank to remove this placeholder

https://www.checklistbank.org/dataset/2037/name/7935ed07-1b4e-424d-a9f6-8627a232df2b

**Comment by camiplata** [comment]
this issue was reported some time ago: https://github.com/CatalogueOfLife/xcol/issues/31
