### ISSUE TITLE
On the latest release diplura only goes down to genus

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#712]
**Describe the problem**:
 ITIS is the the current source with [163 species](https://www.checklistbank.org/dataset/2144/taxon/914186), nevertheless non are showing on the latest release, checking the old releases it looks like this is happening since COL24.8

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/8NKDJ

<img width="507" alt="Captura de pantalla 2024-10-25 a la(s) 1 37 55 p m" src="https://github.com/user-attachments/assets/1672b0b9-bd38-4228-8d19-7d1713597dfb">

**Comment by DaveNicolson** [comment]
ITIS does not have a Diplura GSD (it is clearly labelled as "partial"), although we would be happy to upgrade it...

**Comment by camiplata** [comment]
Yes indeed, I actually noticed the issue while evaluating the data  of a potential complete GSD (see https://github.com/CatalogueOfLife/data/issues/577).

**Comment by DaveNicolson** [comment]
I'm not following, I thought "regular" COL used only GSDs, and only the experimental extended releases would include non-GSD data... So excluding the ITIS data from COL would be correct, I understood...?

**Comment by yroskov** [comment]
Let me confirm please:

- Yes, **global COL** supposed to use **only GSDs**, and extended release includes also non-GSD data.
- Since the 2201 Annual Checklist (i.e. the first AC in a new environment), there have been no species data for Diplura in the CoL due to lack of a GSD for this taxon.

**Comment by yroskov** [comment]
and one more...

- CoL of today uses the Diplura classification from order down to genus preserved from ITIS of June 2017.
