### ISSUE TITLE
Regression for Pittosporum tobira (Murray) Aiton fil.

### ISSUE THREAD

**Issue by ahahn-gbif** [CatalogueOfLife/data#720]
Losing the species level information

```
{
  "count": 102087,
  "verbatim_taxonID": "null",
  "verbatim_taxonConceptID": "null",
  "verbatim_scientificNameID": "null",
  "verbatim_kingdom": "Plantae",
  "verbatim_phylum": "null",
  "verbatim_class": "null",
  "verbatim_order": "null",
  "verbatim_family": "null",
  "verbatim_genus": "null",
  "verbatim_species": "null",
  "verbatim_infra": "null",
  "verbatim_rank": "species",
  "verbatim_verbatimRank": "species",
  "verbatim_scientificName": "Pittosporum tobira (Thunb.) W.T.Aiton",
  "verbatim_generic": "null",
  "verbatim_author": "(Thunb.) W.T.Aiton",
  "current_kingdom": "Plantae",
  "current_phylum": "Tracheophyta",
  "current_class": "Magnoliopsida",
  "current_order": "Apiales",
  "current_family": "Pittosporaceae",
  "current_genus": "Pittosporum",
  "current_subGenus": "null",
  "current_species": "Pittosporum tobira",
  "current_scientificName": "Pittosporum tobira (Murray) Aiton fil.",
  "current_acceptedScientificName": "Pittosporum tobira (Murray) Aiton fil.",
  "proposed_kingdom": "Plantae",
  "proposed_phylum": "Tracheophyta",
  "proposed_class": "Magnoliopsida",
  "proposed_order": "Apiales",
  "proposed_family": "Pittosporaceae",
  "proposed_genus": "Pittosporum",
  "proposed_subGenus": "null",
  "proposed_species": "null",
  "proposed_scientificName": "Pittosporum Gaertn.",
  "proposed_acceptedScientificName": "Pittosporum Gaertn.",
  "debug_url": "http://backbonebuild-vh.gbif.org:9101/v2/species/match?&kingdom=Plantae&scientificName=Pittosporum tobira (Thunb.) W.T.Aiton&authorship=(Thunb.) W.T.Aiton&rank=species&strict=false",
  "_key": 6743,
  "changes": {
    "species": true,
    "scientificName": true,
    "acceptedScientificName": true
  },
  "reviewed": false
}
```

**Comment by djtfmartin** [comment]
The match to `Pittosporum tobira` fails due to the authorship comparison which has a big on the confidence score.

**Comment by mdoering** [comment]
The issue here is `filius` again. I have coded the authorship comparison to assure an author which hass filius in it to not match the same author without filius - as it is the son of it. But that obviously is not always true when filius is simply not given. Need to think how to get around this without hurting the comparison in other places...

**Comment by djtfmartin** [comment]
This is fixed now.

See http://backbonebuild-vh.gbif.org:9101/v2/species/match?&kingdom=Plantae&scientificName=Pittosporum%20tobira%20(Thunb.)%20W.T.Aiton&authorship=(Thunb.)%20W.T.Aiton&rank=species&strict=false

**Comment by DianRHR** [comment]
For Plants we can use the IPNI input we have ... however, eventhough in this [particular case](https://www.ipni.org/?q=Aiton), the son is not registered using the "fil" particle, and it is differentiated by using the initials. 
For other cases we can also take hand of the alternative abbreviations. 

The authorship in this name seems to have an error in the original source of the [baseCOL](https://www.checklistbank.org/dataset/304954/taxon/77M2Q) (already reported). #805
