### ISSUE TITLE
Regression for Macrocyprididae

### ISSUE THREAD

**Issue by ahahn-gbif** [CatalogueOfLife/data#730]
We have a bundle of those seemingly meaningless relationships (filter, e.g., for phylum "Cordata"): ignore (matching issue), or concern? I assume that "Gen novum" should not be an accepted name (https://www.checklistbank.org/dataset/304862/taxon/FDJCZ).

![image](https://github.com/user-attachments/assets/d060a3bd-32f5-43e0-8189-de2924fb38df)

```
{
  "count": 29406,
  "verbatim_taxonID": "null",
  "verbatim_taxonConceptID": "NZOR-6-41835",
  "verbatim_scientificNameID": "null",
  "verbatim_kingdom": "Animalia",
  "verbatim_phylum": "Arthropoda",
  "verbatim_class": "Ostracoda",
  "verbatim_order": "Podocopida",
  "verbatim_family": "Macrocyprididae",
  "verbatim_genus": "Gen",
  "verbatim_species": "sp.",
  "verbatim_infra": "null",
  "verbatim_rank": "genus",
  "verbatim_verbatimRank": "genus",
  "verbatim_scientificName": "Gen",
  "verbatim_generic": "null",
  "verbatim_author": "null",
  "current_kingdom": "Animalia",
  "current_phylum": "Arthropoda",
  "current_class": "Ostracoda",
  "current_order": "Podocopida",
  "current_family": "Macrocyprididae",
  "current_genus": "null",
  "current_subGenus": "null",
  "current_species": "null",
  "current_scientificName": "Macrocyprididae",
  "current_acceptedScientificName": "Macrocyprididae",
  "proposed_kingdom": "Animalia",
  "proposed_phylum": "Chordata",
  "proposed_class": "null",
  "proposed_order": "null",
  "proposed_family": "Tyrannosauridae",
  "proposed_genus": "Gen",
  "proposed_subGenus": "null",
  "proposed_species": "null",
  "proposed_scientificName": "Gen_Indet",
  "proposed_acceptedScientificName": "Gen_Indet",
  "debug_url": "http://backbonebuild-vh.gbif.org:9101/v2/species/match?&taxonConceptID=NZOR-6-41835&kingdom=Animalia&phylum=Arthropoda&class=Ostracoda&order=Podocopida&family=Macrocyprididae&genus=Gen&scientificName=Gen&rank=genus&specificEpithet=sp.&strict=false",
  "_key": 19082,
  "changes": {
    "phylum": true,
    "class": true,
    "order": true,
    "family": true,
    "genus": true,
    "scientificName": true,
    "acceptedScientificName": true
  },
  "reviewed": false
}
```

**Comment by camiplata** [comment]
[Gen novum](https://www.checklistbank.org/dataset/304862/classification?taxonKey=FDJCZ) blocked form bold
[Gen_Indet](https://www.checklistbank.org/dataset/304862/taxon/K9FTW) blocked form plazi and Issue to Plazi https://github.com/plazi/community/issues/334

**Comment by DianRHR** [comment]
just added Gen Indet (and its variants) in the blockedNames list in the [config file ](https://github.com/CatalogueOfLife/data/blob/master/xcol/xcol-config.yaml)

**Comment by camiplata** [comment]
<img width="1040" alt="Captura de pantalla 2024-11-04 a la(s) 9 24 01 p m" src="https://github.com/user-attachments/assets/b7c72606-cf3d-4962-b71e-84fbb028d09c">


<img width="908" alt="Captura de pantalla 2024-11-04 a la(s) 9 24 10 p m" src="https://github.com/user-attachments/assets/dfeb6266-e368-40a1-ae44-13148c8b484d">


fixed
