### ISSUE TITLE
Regression for Asellidae

### ISSUE THREAD

**Issue by CecSve** [CatalogueOfLife/data#735]
Probably the same family as https://www.checklistbank.org/dataset/304862/taxon/C66K3, just with a different authorship. Not a release issue.

```
{
  "count": 2952,
  "verbatim_taxonID": "null",
  "verbatim_taxonConceptID": "null",
  "verbatim_scientificNameID": "null",
  "verbatim_kingdom": "null",
  "verbatim_phylum": "null",
  "verbatim_class": "null",
  "verbatim_order": "null",
  "verbatim_family": "null",
  "verbatim_genus": "null",
  "verbatim_species": "null",
  "verbatim_infra": "null",
  "verbatim_rank": "family",
  "verbatim_verbatimRank": "family",
  "verbatim_scientificName": "Asellidae Rafinesque, 1815",
  "verbatim_generic": "null",
  "verbatim_author": "null",
  "current_kingdom": "Animalia",
  "current_phylum": "Arthropoda",
  "current_class": "Malacostraca",
  "current_order": "Isopoda",
  "current_family": "Asellidae",
  "current_genus": "null",
  "current_subGenus": "null",
  "current_species": "null",
  "current_scientificName": "Asellidae",
  "current_acceptedScientificName": "Asellidae",
  "proposed_kingdom": "incertae sedis",
  "proposed_phylum": "null",
  "proposed_class": "null",
  "proposed_order": "null",
  "proposed_family": "null",
  "proposed_genus": "null",
  "proposed_subGenus": "null",
  "proposed_species": "null",
  "proposed_scientificName": "incertae sedis",
  "proposed_acceptedScientificName": "null",
  "debug_url": "http://backbonebuild-vh.gbif.org:9101/v2/species/match?&scientificName=Asellidae Rafinesque, 1815&rank=family&strict=false",
  "_key": 8877,
  "changes": {
    "kingdom": true,
    "phylum": true,
    "class": true,
    "order": true,
    "family": true,
    "scientificName": true,
    "acceptedScientificName": true
  },
  "reviewed": false
}
```

**Comment by camiplata** [comment]
The occurrence lacks a H classification, but there is only one match, so it shouldn't be a problem


<img width="1114" alt="Captura de pantalla 2024-10-31 a la(s) 3 20 56 p m" src="https://github.com/user-attachments/assets/dd0159c8-1760-4b32-93cc-b9c8c8af17a0">


<img width="1043" alt="Captura de pantalla 2024-10-31 a la(s) 3 20 10 p m" src="https://github.com/user-attachments/assets/d1ab004a-f8bf-43ff-8ee8-aaca40711085">

**Comment by mdoering** [comment]
matches now:
http://backbonebuild-vh.gbif.org:9101/v2/species/match?&scientificName=Asellidae%20Rafinesque,%201815&rank=family&strict=false

<img width="430" alt="image" src="https://github.com/user-attachments/assets/810ec542-0336-4910-aeaa-6d7ba650e398">

**Comment by mdoering** [comment]
https://en.wikipedia.org/wiki/Asellidae goes under both [Rafinesque](https://en.wikipedia.org/wiki/Constantine_Samuel_Rafinesque), 1815 and 
[Latreille](https://en.wikipedia.org/wiki/Pierre_Andr%C3%A9_Latreille), 1802

@camiplata maybe we can add the Rafinesque one as a synonym

**Comment by DaveNicolson** [comment]
Just for reference, the apparent 1802 and 1815 citations seem to point to these two pages:
1802: https://www.biodiversitylibrary.org/page/24884897
1815: https://gallica.bnf.fr/ark:/12148/bpt6k98061z/f104.item

Whether one or both would formally make the name available is unclear to me, due to the complexities of French "vernaculars" vs. French "scientific vernaculars" (sometimes it qualifies, sometimes it doesn't, and my knowledge of French isn't good enough to predict).
