### ISSUE TITLE
WorldPlants -  May Sinapis arvensis be the accepted name for Rhamphospermum arvense?

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#786]
**Describe the problem**:

For  consideration of the source author: is  Sinapis arvensis L. the current accepted name of Rhamphospermum arvense (L.) Andrz. ex Besser 

Potencial change identified in: https://www.worldfloraonline.org/taxon/wfo-0000432651#synonyms, it looks like WFO did a recent revision of the taxon.

<img width="1005" alt="Captura de pantalla 2024-10-30 a la(s) 11 59 49 a m" src="https://github.com/user-attachments/assets/bad5de20-1cb9-47c3-9c68-4bfe137523a6">

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/C873Z

**Literature references**:
 The record derives from WCSP (in review) (data supplied on 2024-06-04) which reports it as an accepted name

**Comment by yroskov** [comment]
Forwarded to World Plants

**Comment by yroskov** [comment]
_This is a typical case of two alternative concepts. I am following Ihsan Al-Shehbaz in recognizing Rhamphospermum. He is the best authority for Brassicaceae.
WFO is quite inhomogeneous in who is “steering” their concepts. I have decided to completely ignore WFO for the foreseeable future, even with Rhakhis and else._

Michael
