### ISSUE TITLE
Is it possible for the merge to handle Fucus Linnaeus, 1853 and Fucus Linnaeus, 1753

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#788]
Is it possible for the merge to handle this duplicate pair with a date typo [ Fucus Linnaeus, 1853 and Fucus Linnaeus, 1753](
https://www.checklistbank.org/dataset/304862/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Fucus&type=EXACT) and partial match of the classification? Or should we block the name

<img width="1131" alt="Captura de pantalla 2024-10-30 a la(s) 10 33 11 p m" src="https://github.com/user-attachments/assets/d1030c03-ad00-4555-9814-98a13a67c630">

**Comment by mdoering** [comment]
you should add a name/authorship update decision in the [workbench](https://www.checklistbank.org/catalogue/3/dataset/1174/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Fucus) and if it occurrs multiple times keep it as a synonym by setting `keepOriginalName=true`

**Comment by camiplata** [comment]
Decision added
