### ISSUE TITLE
Error in authorship in Pittosporum tobira from World Plants

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/data#805]
**The species Pittosporum tobira (Murray) Aiton fil. seems to have an error in the authorship, as Murray is not the original author according to [WFO ](https://wfoplantlist.org/taxon/wfo-0000487958-2024-06?page=1) 
The references included in the [dataset ](https://www.checklistbank.org/dataset/1141/taxon/Apiales-Pittosporaceae-Pittosporum-tobira-(Murray)%20Aiton%20fil.)of World Plants don't include any of Murray**:
...

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/77M2Q

**Literature references**:
...

**Comment by yroskov** [comment]
Forwarded to World Plants editor

**Comment by yroskov** [comment]
Michael, 2024-11-06: will be corrected
