### ISSUE TITLE
Duplicate empty GLI dataset

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#814]
**Describe the problem**:

Hi @gdower,  a found what it looks like a duplicate  of GLI  without metadata  ans just one species https://www.checklistbank.org/dataset/264540/about, we are using this GLI as the starting point of the Project tutorial so this may create confusion. Is possible to remove this dataset?

cc @DianRHR

**Comment by gdower** [comment]
All set

**Comment by camiplata** [comment]
thanks :D
