### ISSUE TITLE
What to do if  the duplicates have the same accepted

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#879]
If two duplicates have the same accepted, should we still mark them as duplicates, is another category needed

https://www.checklistbank.org/dataset/306220/taxon/BSGLK

<img width="1062" alt="Captura de pantalla 2024-12-12 a la(s) 3 32 06 p m" src="https://github.com/user-attachments/assets/b51f0d59-cad5-4d36-a4f1-08a5422d2c68" />

**Comment by mdoering** [comment]
they have different authors. What exactly is the problem?
There is a regular check for synonyms with the same accepted name but different authors:
https://www.checklistbank.org/dataset/306220/duplicates?acceptedDifferent=false&authorshipDifferent=true&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=synonym
