### ISSUE TITLE
Testing assembly of other datasets

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/data#95]
Since Index Fungorum got sent in pieces, I decided to try to test the new catalogues/projects feature by merging the datasets together using assembly. I was able to get this far:

![image](https://user-images.githubusercontent.com/8573609/70819816-bf4fc080-1d9c-11ea-8a40-100cbe155893.png)

In order to get there, I had to create a uploaded dataset 30812 and provide the [root kingdom Fungi taxon in a CoLDP archive](https://github.com/Sp2000/colplus-repo/files/3962009/IF.zip). Without adding a root taxon, managed datasets get a 404 error in assembly:

![image](https://user-images.githubusercontent.com/8573609/70821029-a7c60700-1d9f-11ea-80aa-a0d330a5199f.png)

Probably we should automatically add the Biota taxon as root to new managed datasets to make that process easier for new people. Then I edited the meta data and switched it back to a managed dataset so that I could use the assembly system.

Syncing raises a [backend error that assembly is only allowed on the draft catalogue](https://github.com/Sp2000/colplus-backend/blob/cc513f507aa27c5a563d71f2c27c028e26c6560e/colplus-ws/src/main/java/life/catalogue/resources/AssemblyResource.java#L170):

![image](https://user-images.githubusercontent.com/8573609/70819847-d7274480-1d9c-11ea-9814-e58aaf5740cf.png)

Also, after attaching a dataset the frontend switches assembly back to catalogue 3, so I think somewhere in the frontend code there's still a hardcoded dataset 3 (or maybe it's a cookie?). 

![image](https://user-images.githubusercontent.com/8573609/70819911-fe7e1180-1d9c-11ea-8c5d-69bb017859d2.png)

In order to get the frontend to reset back to catalogue 30812, I had to browse the 30812 dataset and change the URL back to /catalogue/30812/dataset/30812. (I tried deleting the ?datasetKey=30811 parameter from the URL, but that didn't work. Also, doing a no cache reload on /catalogue/30812 didn't work.)

Despite some bugs still needing to be worked out, this is really impressive and I think projects will be a really strong feature. :+1:

**Comment by mdoering** [comment]
I removed the outdated restriction to only work with the draft dataset=3 in the assembly:
https://github.com/Sp2000/colplus-backend/commit/c52da2bbe423ccc4382e38fc847fde1c3df86b63

It now only requires a managed dataset which is not deleted and not locked (e.g. releases).

**Comment by gdower** [comment]
I tried again today using the same techniques as above and was able to successfully build a non-draft-3 assembly and export with just 1 GSD for testing:

http://api.dev.catalogue.life/download/export-2055.zip
